#------------------------------------------------------------------------------
# Name:                 simog.ini
# Type:                 Properties file
# Purpose:              See comments below
# Created:              12/03/2008
#=== COMPONENT-ID ===================================================
# Project:              SIMOG - AVCP
# Layer/partition:      Application Properties
# Developed by:         Step s.r.l.
# Copyright:            All rights reserved
#------------------------------------------------------------------------------

#----------------------------------------
#	Componenti COMUNI
#----------------------------------------

#	Identifica il SIMOG sui sistemi AVCP - RICHIESTO
SIMOG_IDENTIFIER=1

# Configurazione per la connessione a DB
#
#JDBC_DATASOURCE_NAME=java:comp/env/jdbc/SIMOG

JDBC_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
JDBC_STRING=jdbc:sqlserver://10.119.26.41:1433;SelectMethod=cursor;user=simog;password=simog.1;DatabaseName=simog;sendStringParametersAsUnicode=true;characterEncoding=UTF-8


#----------------------------------------
#	Componenti AUTENTICAZIONE
#----------------------------------------

# Richiede o meno l'autenticazione remota
# Se � presente e valorizzato: LOCAL
# Allora l'applicazione effettua una simulazione
# Per il puntamento ai sistemi AVCP indicare l'indirizzo dell'endpoint
WS_AUTH_TARGET_HOST=LOCAL
#WS_AUTH_TARGET_HOST=https://anagrafe.avcp.it:447/login.cgi/soap/Ilogin
# Commentato (AR)
#WS_AUTH_TARGET_HOST=http://autenticatore.avcp.local:1447/login.cgi/soap/Ilogin
#WS_AUTH_TARGET_HOST=NEW:http://10.119.26.36:8080/avcp-iam-service-v1.0/Ilogin


SAML_LOGIN_URL=/AVCP-SimogWeb/checkAuthentication
#SAML_LOGOUT_URL=https://servizi.avcp.local/portal/dologin?GLO=true
#SAML_PROFILE_URL=https://servizi.avcp.local/portal/classic/GestioneProfilo/SceltaProfilo


#----------------------------------------
#	Opzioni di PRESENTAZIONE
#----------------------------------------

# Viene aggiunto un parametro per la visualizzazione paginata degli
# elenchi

ELEMENTI_VISUALIZZATI=10

#----------------------------------------
#	Componenti AMMINISTRATIVE
#----------------------------------------

# Directory in cui vengono archiviate le informazioni di modifica tabelle di servizio
TABELLE_AGGIORNAMENTO_DIR=/opt/SIMOG/amministrazione
TABELLE_AGGIORNAMENTO_HISTORY=/opt/SIMOG/amministrazione/history

#----------------------------------------
#	Opzioni di UPLOAD FILE
#----------------------------------------

# Parametro che indica la dimensione massima in byte
# per i file di documentazione per i lotti

DIMENSIONE_DOCUMENTO_MAX=5000000

IMPORTO_LOTTO_AUX=-1.000

#importo minimo lotti per scheda A
IMPORTO_MIN_LOTTO=0

#importo minimo lotti per scheda b2
IMPORTO_MIN_LOTTO_B2=500000.000

# Parametro che indica l'abilitazione della gestione documentale (s/S - n/N)
ABILITAZIONE_DOCUMENTI=s

#durata della sessione in secondi, se non viene usata entro il tempo indicato scade
#l'applicazione ha una durata standard di 12 ore per le sessioni, dopo tale termine
#il server le chiude
DURATA_SESSIONE=720000

#SAML_CERTIFICATE=cert.9465_9358.cer
#SAML_LOGIN_URL=http://simog.avcp.it/AVCP-SimogWeb/InvalidateSession
#SAML_LOGOUT_URL=http://simog.avcp.it/AGLogout
#SAML_PROFILE_URL=http://simog.avcp.it/AVCP-SimogWeb/InvalidateSession

# Per ora commentato (AR)
#CLAMAV_HOST=localhost
#CLAMAV_PORT=3310
#CLAMAV_TIMEOUT=10000

PATH_ALLEGATI=C:\PROGETTI\ANAC\conf\Allegati

WSANAG_USER=AAAAAA00A01H501Z
WSANAG_PWD=provami
# Servizi anagrafici usati per parte amministrazione, migrare? (AR) 
WSANAG_URL=http://10.119.128.144:81/AnagrafeWS/

#Link corretto
CONTRIBUTO_URL=http://10.119.26.28:8080/GestioneContributoService/GestioneContributoWSBean

#Link errato per test collaudo
#CONTRIBUTO_URL=http://rilserv01.ril.avcp.local:8080/GestioneContributoService/GestioneContributoWSBeanERR

GIORNI_SCADENZA_ALLEGATI=1000
# 3.02.5
DATA_ATTIVAZIONE_REQUISITI=20110101

# 3.02.8
GIORNI_PUBB_SCADENZA=365
#WS_AVCPASS_HOST=http://rilserv01.ril.avcp.local:8080/avcpass-service-avcpass-service/GestioneSimogServiceBean

# 3.02.9.5
DATA_ATTIVAZIONE_ESCL_AVCPASS=20140101



DATA_ATTIVAZIONE_CUP=20140512
#TEST PICCININI
#DIPE_URL=http://cupwebwscoll.tesoro.local/CUPServicesCollaudo
#DIPE_URL=http://pddspccoll.mef.gov.it/openspcoop/PA/MEF/COLL/CIPE_CUP_ElaborazioniCUP_1

DIPE_URL=https://cupwebwsese.tesoro.it/CUPServicesEsercizio
DIPE_USER=alessandro.obino
#DIPE_PWD= sC4056
DIPE_PWD=UiN9xtveEpMhXbA4mV
DIPE_TIMEOUT=240
#CODICI_PROCEDURA_RISTRETTA = 2, 9, 13
CODICI_PROCEDURA_RISTRETTA=2,9,13,25,8,30,28x,34

#RGS
RGS_URL=http://localhost:8081/CUP




# 3.03.3.0
DATA_ATTIVAZIONE_DL133=20150211

DATA_ATTIVAZIONE_BLOCCOCIG=20991231

# 3.03.5.0
DATA_ATTIVAZIONE_ENTIAGGWEB = 20160201
DATA_ATTIVAZIONE_ENTIAGGWS = 20160201
LINK_ENTIAGG = http://www.anticorruzione.it/portal/public/classic/MenuServizio/FAQ/_NoteEsplRicorsoSoggAggreg

# 3.04.2
DATA_ATTIVAZIONE_3042 = 20181001
DATA_ATTIVAZIONE_ULTIMAZIONE_LAVORI = 20181002

# CEF ESPD
URL_ESPD_TOKEN=http://10.119.26.72:9080/AnacAuthorizationServer/oauth/token
DATA_ATTIVAZIONE_CEFESPD=20181020

# 3.04.3
DATA_ATTIVAZIONE_3043 = 20191018

# 3.04.4
DATA_ATTIVAZIONE_3044 = 20190620
CF_SA_ESCLUSE_SOGG_AGG = 00390090215
DATA_OBBLIGHI_COMUNICATIVI_SPECIALI = 20070201
GENERACIG_DB=S
ATTIVAZIONE_SOGG_AGGR=20200225

# 3.04.5
DATA_ATTIVAZIONE_3045=20200719
ELEMENTI_EXPORT=3000
#URL_WS_AUSA=http://10.119.26.28:8080/ServiziAUSA-ear-ServiziAUSA-ejb/RicercaSABean
DATA_SBLOCCA_CANTIERI=20190618
ESCLUSI_SOGLIA_ANOMALIA=80014890638,00337460224

# 3.04.5.1
DATA_ATTIVAZIONE_30451=20210127

# 3.04.5.2
DATA_ATTIVAZIONE_30452=20210227

# 3.04.6
DATA_ATTIVAZIONE_3046=20210314

#TED
URL_TED=https://esentool.ted.europa.eu/api/simulation/latest/notice/
USERNAME_TED=TEDUTDD8
PWD_TED=TEDeSender
XSD_TED=R2.0.9.S05

# 3.04.6.2
DATA_ATTIVAZIONE_30462=20211027

# PPP - Controllo CUP PPP
DATA_ATTIVAZIONE_PPP=20990101
IDMODREAL_PPP=4;5;8;13