#------------------------------------------------------------------------------
# Name:                 simog_log4j.properties - SIMOGWEB
# Type:                 Properties file
# Purpose:              See comments below
# Created:              30/11/2006
#=== COMPONENT-ID ===================================================
# Project:              SIMOG - AVCP
# Layer/partition:      Log Properties
# Developed by:         Step s.r.l.
# Copyright:            All rights reserved
#------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# Define appenders and root priority level definition
#-------------------------------------------------------------------------------
log4j.logger.SIMOG_LOGGER=DEBUG, SIMOG_APPENDER, FATAL_APPENDER, stdOut

#--------------------------------------------------------------------------------
# Define GISP Event Manager Logger
#--------------------------------------------------------------------------------
log4j.additivity.SIMOG_LOGGER=false

log4j.appender.stdOut.Threshold=FATAL
log4j.appender.stdOut=org.apache.log4j.ConsoleAppender
log4j.appender.stdOut.ImmediateFlush=true
log4j.appender.stdOut.layout=org.apache.log4j.PatternLayout
log4j.appender.stdOut.layout.ConversionPattern=[%d{yyyy:MM:dd HH:mm:ss,SSS}] %X{Jsession} [%C{1}] %-5p %x: %m%n

log4j.appender.SIMOG_APPENDER.threshold=DEBUG
log4j.appender.SIMOG_APPENDER=org.apache.log4j.DailyRollingFileAppender
log4j.appender.SIMOG_APPENDER.File=/opt/SimogWebLog/SIMOG.log
log4j.appender.SIMOG_APPENDER.DatePattern='.'yyyy-MM-dd
log4j.appender.SIMOG_APPENDER.layout=org.apache.log4j.PatternLayout
log4j.appender.SIMOG_APPENDER.layout.ConversionPattern=[%d{yyyy:MM:dd HH:mm:ss,SSS}] %X{Jsession} [%C{1}] %-5p %c %x - %m%n

log4j.appender.FATAL_APPENDER.Threshold=ERROR
log4j.appender.FATAL_APPENDER.File=/opt/SimogWebLog/SIMOG_FATAL.log
log4j.appender.FATAL_APPENDER=org.apache.log4j.DailyRollingFileAppender
log4j.appender.FATAL_APPENDER.layout=org.apache.log4j.PatternLayout
log4j.appender.FATAL_APPENDER.layout.ConversionPattern=[%d{yyyy:MM:dd HH:mm:ss,SSS}] %X{Jsession} [%C{1}] %-5p %x: %m%n

#-------------------------------------------------------------------------------
# END OF FILE
#-------------------------------------------------------------------------------
