//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 02:39:54 PM CEST 
//


package it.anticorruzione.ted.xml;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AppaltoTypeAgg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppaltoTypeAgg">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AWARDED_NOTICE" type="{http://xml.ted.anticorruzione.it}ContraenteType" maxOccurs="100" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CIG_AGG" use="required" type="{http://xml.ted.anticorruzione.it}CigType" />
 *       &lt;attribute name="AWARDED_CONTRACT" use="required" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *       &lt;attribute name="PROCUREMENT_UNSUCCESSFUL" type="{http://xml.ted.anticorruzione.it}ProcurementUnsuccessfulType" />
 *       &lt;attribute name="NB_TENDERS_RECEIVED">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NB_TENDERS_RECEIVED_SME">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NB_TENDERS_RECEIVED_OTHER_EU">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NB_TENDERS_RECEIVED_NON_EU">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NB_TENDERS_RECEIVED_EMEANS">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="AWARDED_TO_GROUP" use="required" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *       &lt;attribute name="VAL_ESTIMATED_TOTAL" type="{http://xml.ted.anticorruzione.it}ImportoType" />
 *       &lt;attribute name="VAL_TOTAL" type="{http://xml.ted.anticorruzione.it}ImportoType" />
 *       &lt;attribute name="VAL_RANGE_TOTAL_LOW" type="{http://xml.ted.anticorruzione.it}ImportoType" />
 *       &lt;attribute name="VAL_RANGE_TOTAL_HIGH" type="{http://xml.ted.anticorruzione.it}ImportoType" />
 *       &lt;attribute name="LIKELY_SUBCONTRACTED" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *       &lt;attribute name="VAL_SUBCONTRACTING" type="{http://xml.ted.anticorruzione.it}ImportoType" />
 *       &lt;attribute name="PCT_SUBCONTRACTING">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="100"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="INFO_ADD_SUBCONTRACTING">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="6000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DATA_APERTURA_OFFERTE" type="{http://xml.ted.anticorruzione.it}DbDateType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppaltoTypeAgg", propOrder = {
    "awardednotice"
})
public class AppaltoTypeAgg {

    @XmlElement(name = "AWARDED_NOTICE")
    protected List<ContraenteType> awardednotice;
    @XmlAttribute(name = "CIG_AGG", required = true)
    protected String cigagg;
    @XmlAttribute(name = "AWARDED_CONTRACT", required = true)
    protected FlagSNType awardedcontract;
    @XmlAttribute(name = "PROCUREMENT_UNSUCCESSFUL")
    protected String procurementunsuccessful;
    @XmlAttribute(name = "NB_TENDERS_RECEIVED")
    protected Integer nbtendersreceived;
    @XmlAttribute(name = "NB_TENDERS_RECEIVED_SME")
    protected Integer nbtendersreceivedsme;
    @XmlAttribute(name = "NB_TENDERS_RECEIVED_OTHER_EU")
    protected Integer nbtendersreceivedothereu;
    @XmlAttribute(name = "NB_TENDERS_RECEIVED_NON_EU")
    protected Integer nbtendersreceivednoneu;
    @XmlAttribute(name = "NB_TENDERS_RECEIVED_EMEANS")
    protected Integer nbtendersreceivedemeans;
    @XmlAttribute(name = "AWARDED_TO_GROUP", required = true)
    protected FlagSNType awardedtogroup;
    @XmlAttribute(name = "VAL_ESTIMATED_TOTAL")
    protected BigDecimal valestimatedtotal;
    @XmlAttribute(name = "VAL_TOTAL")
    protected BigDecimal valtotal;
    @XmlAttribute(name = "VAL_RANGE_TOTAL_LOW")
    protected BigDecimal valrangetotallow;
    @XmlAttribute(name = "VAL_RANGE_TOTAL_HIGH")
    protected BigDecimal valrangetotalhigh;
    @XmlAttribute(name = "LIKELY_SUBCONTRACTED")
    protected FlagSNType likelysubcontracted;
    @XmlAttribute(name = "VAL_SUBCONTRACTING")
    protected BigDecimal valsubcontracting;
    @XmlAttribute(name = "PCT_SUBCONTRACTING")
    protected Integer pctsubcontracting;
    @XmlAttribute(name = "INFO_ADD_SUBCONTRACTING")
    protected String infoaddsubcontracting;
    @XmlAttribute(name = "DATA_APERTURA_OFFERTE")
    protected XMLGregorianCalendar dataaperturaofferte;

    /**
     * Gets the value of the awardednotice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the awardednotice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAWARDEDNOTICE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContraenteType }
     * 
     * 
     */
    public List<ContraenteType> getAWARDEDNOTICE() {
        if (awardednotice == null) {
            awardednotice = new ArrayList<ContraenteType>();
        }
        return this.awardednotice;
    }

    /**
     * Gets the value of the cigagg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIGAGG() {
        return cigagg;
    }

    /**
     * Sets the value of the cigagg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIGAGG(String value) {
        this.cigagg = value;
    }

    /**
     * Gets the value of the awardedcontract property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getAWARDEDCONTRACT() {
        return awardedcontract;
    }

    /**
     * Sets the value of the awardedcontract property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setAWARDEDCONTRACT(FlagSNType value) {
        this.awardedcontract = value;
    }

    /**
     * Gets the value of the procurementunsuccessful property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROCUREMENTUNSUCCESSFUL() {
        return procurementunsuccessful;
    }

    /**
     * Sets the value of the procurementunsuccessful property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROCUREMENTUNSUCCESSFUL(String value) {
        this.procurementunsuccessful = value;
    }

    /**
     * Gets the value of the nbtendersreceived property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNBTENDERSRECEIVED() {
        return nbtendersreceived;
    }

    /**
     * Sets the value of the nbtendersreceived property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNBTENDERSRECEIVED(Integer value) {
        this.nbtendersreceived = value;
    }

    /**
     * Gets the value of the nbtendersreceivedsme property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNBTENDERSRECEIVEDSME() {
        return nbtendersreceivedsme;
    }

    /**
     * Sets the value of the nbtendersreceivedsme property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNBTENDERSRECEIVEDSME(Integer value) {
        this.nbtendersreceivedsme = value;
    }

    /**
     * Gets the value of the nbtendersreceivedothereu property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNBTENDERSRECEIVEDOTHEREU() {
        return nbtendersreceivedothereu;
    }

    /**
     * Sets the value of the nbtendersreceivedothereu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNBTENDERSRECEIVEDOTHEREU(Integer value) {
        this.nbtendersreceivedothereu = value;
    }

    /**
     * Gets the value of the nbtendersreceivednoneu property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNBTENDERSRECEIVEDNONEU() {
        return nbtendersreceivednoneu;
    }

    /**
     * Sets the value of the nbtendersreceivednoneu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNBTENDERSRECEIVEDNONEU(Integer value) {
        this.nbtendersreceivednoneu = value;
    }

    /**
     * Gets the value of the nbtendersreceivedemeans property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNBTENDERSRECEIVEDEMEANS() {
        return nbtendersreceivedemeans;
    }

    /**
     * Sets the value of the nbtendersreceivedemeans property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNBTENDERSRECEIVEDEMEANS(Integer value) {
        this.nbtendersreceivedemeans = value;
    }

    /**
     * Gets the value of the awardedtogroup property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getAWARDEDTOGROUP() {
        return awardedtogroup;
    }

    /**
     * Sets the value of the awardedtogroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setAWARDEDTOGROUP(FlagSNType value) {
        this.awardedtogroup = value;
    }

    /**
     * Gets the value of the valestimatedtotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVALESTIMATEDTOTAL() {
        return valestimatedtotal;
    }

    /**
     * Sets the value of the valestimatedtotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVALESTIMATEDTOTAL(BigDecimal value) {
        this.valestimatedtotal = value;
    }

    /**
     * Gets the value of the valtotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVALTOTAL() {
        return valtotal;
    }

    /**
     * Sets the value of the valtotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVALTOTAL(BigDecimal value) {
        this.valtotal = value;
    }

    /**
     * Gets the value of the valrangetotallow property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVALRANGETOTALLOW() {
        return valrangetotallow;
    }

    /**
     * Sets the value of the valrangetotallow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVALRANGETOTALLOW(BigDecimal value) {
        this.valrangetotallow = value;
    }

    /**
     * Gets the value of the valrangetotalhigh property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVALRANGETOTALHIGH() {
        return valrangetotalhigh;
    }

    /**
     * Sets the value of the valrangetotalhigh property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVALRANGETOTALHIGH(BigDecimal value) {
        this.valrangetotalhigh = value;
    }

    /**
     * Gets the value of the likelysubcontracted property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getLIKELYSUBCONTRACTED() {
        return likelysubcontracted;
    }

    /**
     * Sets the value of the likelysubcontracted property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setLIKELYSUBCONTRACTED(FlagSNType value) {
        this.likelysubcontracted = value;
    }

    /**
     * Gets the value of the valsubcontracting property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVALSUBCONTRACTING() {
        return valsubcontracting;
    }

    /**
     * Sets the value of the valsubcontracting property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVALSUBCONTRACTING(BigDecimal value) {
        this.valsubcontracting = value;
    }

    /**
     * Gets the value of the pctsubcontracting property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPCTSUBCONTRACTING() {
        return pctsubcontracting;
    }

    /**
     * Sets the value of the pctsubcontracting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPCTSUBCONTRACTING(Integer value) {
        this.pctsubcontracting = value;
    }

    /**
     * Gets the value of the infoaddsubcontracting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINFOADDSUBCONTRACTING() {
        return infoaddsubcontracting;
    }

    /**
     * Sets the value of the infoaddsubcontracting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINFOADDSUBCONTRACTING(String value) {
        this.infoaddsubcontracting = value;
    }

    /**
     * Gets the value of the dataaperturaofferte property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATAAPERTURAOFFERTE() {
        return dataaperturaofferte;
    }

    /**
     * Sets the value of the dataaperturaofferte property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATAAPERTURAOFFERTE(XMLGregorianCalendar value) {
        this.dataaperturaofferte = value;
    }

}
