//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 02:39:54 PM CEST 
//


package it.anticorruzione.ted.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CondizioniPartecipazioneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CondizioniPartecipazioneType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ELENCO_CONDIZIONI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="10000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CRITERI_ECONOMICI" use="required" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *       &lt;attribute name="ELENCO_CRITERI_ECONOMICI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="10000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="LIVELLI_CRITERI_ECONOMICI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="10000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CRITERI_TECNICI" use="required" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *       &lt;attribute name="ELENCO_CRITERI_TECNICI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="10000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="LIVELLI_CRITERI_TECNICI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="10000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="INTEGRAZIONE_DISABILI" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *       &lt;attribute name="LAVORI_PROTETTI" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *       &lt;attribute name="FLAG_PROFESSIONE_SERVIZI" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *       &lt;attribute name="PROFESSIONE_SERVIZI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="6000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CONDIZIONI_ESECUZIONE_CONTRATTO">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="4000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="OBBLIGO_NOMI_ESECUZIONE_CONTRATTO" use="required" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CondizioniPartecipazioneType")
public class CondizioniPartecipazioneType {

    @XmlAttribute(name = "ELENCO_CONDIZIONI")
    protected String elencocondizioni;
    @XmlAttribute(name = "CRITERI_ECONOMICI", required = true)
    protected FlagSNType criterieconomici;
    @XmlAttribute(name = "ELENCO_CRITERI_ECONOMICI")
    protected String elencocriterieconomici;
    @XmlAttribute(name = "LIVELLI_CRITERI_ECONOMICI")
    protected String livellicriterieconomici;
    @XmlAttribute(name = "CRITERI_TECNICI", required = true)
    protected FlagSNType criteritecnici;
    @XmlAttribute(name = "ELENCO_CRITERI_TECNICI")
    protected String elencocriteritecnici;
    @XmlAttribute(name = "LIVELLI_CRITERI_TECNICI")
    protected String livellicriteritecnici;
    @XmlAttribute(name = "INTEGRAZIONE_DISABILI")
    protected FlagSNType integrazionedisabili;
    @XmlAttribute(name = "LAVORI_PROTETTI")
    protected FlagSNType lavoriprotetti;
    @XmlAttribute(name = "FLAG_PROFESSIONE_SERVIZI")
    protected FlagSNType flagprofessioneservizi;
    @XmlAttribute(name = "PROFESSIONE_SERVIZI")
    protected String professioneservizi;
    @XmlAttribute(name = "CONDIZIONI_ESECUZIONE_CONTRATTO")
    protected String condizioniesecuzionecontratto;
    @XmlAttribute(name = "OBBLIGO_NOMI_ESECUZIONE_CONTRATTO", required = true)
    protected FlagSNType obbligonomiesecuzionecontratto;

    /**
     * Gets the value of the elencocondizioni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getELENCOCONDIZIONI() {
        return elencocondizioni;
    }

    /**
     * Sets the value of the elencocondizioni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setELENCOCONDIZIONI(String value) {
        this.elencocondizioni = value;
    }

    /**
     * Gets the value of the criterieconomici property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getCRITERIECONOMICI() {
        return criterieconomici;
    }

    /**
     * Sets the value of the criterieconomici property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setCRITERIECONOMICI(FlagSNType value) {
        this.criterieconomici = value;
    }

    /**
     * Gets the value of the elencocriterieconomici property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getELENCOCRITERIECONOMICI() {
        return elencocriterieconomici;
    }

    /**
     * Sets the value of the elencocriterieconomici property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setELENCOCRITERIECONOMICI(String value) {
        this.elencocriterieconomici = value;
    }

    /**
     * Gets the value of the livellicriterieconomici property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIVELLICRITERIECONOMICI() {
        return livellicriterieconomici;
    }

    /**
     * Sets the value of the livellicriterieconomici property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIVELLICRITERIECONOMICI(String value) {
        this.livellicriterieconomici = value;
    }

    /**
     * Gets the value of the criteritecnici property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getCRITERITECNICI() {
        return criteritecnici;
    }

    /**
     * Sets the value of the criteritecnici property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setCRITERITECNICI(FlagSNType value) {
        this.criteritecnici = value;
    }

    /**
     * Gets the value of the elencocriteritecnici property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getELENCOCRITERITECNICI() {
        return elencocriteritecnici;
    }

    /**
     * Sets the value of the elencocriteritecnici property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setELENCOCRITERITECNICI(String value) {
        this.elencocriteritecnici = value;
    }

    /**
     * Gets the value of the livellicriteritecnici property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIVELLICRITERITECNICI() {
        return livellicriteritecnici;
    }

    /**
     * Sets the value of the livellicriteritecnici property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIVELLICRITERITECNICI(String value) {
        this.livellicriteritecnici = value;
    }

    /**
     * Gets the value of the integrazionedisabili property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getINTEGRAZIONEDISABILI() {
        return integrazionedisabili;
    }

    /**
     * Sets the value of the integrazionedisabili property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setINTEGRAZIONEDISABILI(FlagSNType value) {
        this.integrazionedisabili = value;
    }

    /**
     * Gets the value of the lavoriprotetti property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getLAVORIPROTETTI() {
        return lavoriprotetti;
    }

    /**
     * Sets the value of the lavoriprotetti property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setLAVORIPROTETTI(FlagSNType value) {
        this.lavoriprotetti = value;
    }

    /**
     * Gets the value of the flagprofessioneservizi property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getFLAGPROFESSIONESERVIZI() {
        return flagprofessioneservizi;
    }

    /**
     * Sets the value of the flagprofessioneservizi property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setFLAGPROFESSIONESERVIZI(FlagSNType value) {
        this.flagprofessioneservizi = value;
    }

    /**
     * Gets the value of the professioneservizi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROFESSIONESERVIZI() {
        return professioneservizi;
    }

    /**
     * Sets the value of the professioneservizi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROFESSIONESERVIZI(String value) {
        this.professioneservizi = value;
    }

    /**
     * Gets the value of the condizioniesecuzionecontratto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONDIZIONIESECUZIONECONTRATTO() {
        return condizioniesecuzionecontratto;
    }

    /**
     * Sets the value of the condizioniesecuzionecontratto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONDIZIONIESECUZIONECONTRATTO(String value) {
        this.condizioniesecuzionecontratto = value;
    }

    /**
     * Gets the value of the obbligonomiesecuzionecontratto property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getOBBLIGONOMIESECUZIONECONTRATTO() {
        return obbligonomiesecuzionecontratto;
    }

    /**
     * Sets the value of the obbligonomiesecuzionecontratto property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setOBBLIGONOMIESECUZIONECONTRATTO(FlagSNType value) {
        this.obbligonomiesecuzionecontratto = value;
    }

}
