//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 02:39:54 PM CEST 
//


package it.anticorruzione.ted.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatiProceduraType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatiProceduraType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="FLAG_PROCEDURA_ACCELLERATA" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *       &lt;attribute name="MOTIVAZIONE_PROCEDURA_ACCELLERATA">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="1000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TIPO_OPERATORI_AQ" type="{http://xml.ted.anticorruzione.it}OperatoriAQType" />
 *       &lt;attribute name="NUM_MAX_PARTECIPANTI_AQ">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ALTRI_ACQUIRENTI_SIS_DINAMICO" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *       &lt;attribute name="NOTE_AQ_QUATTRO_ANNI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="2000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="AGGIUDICAZIONE_SENZA_NEGOZIAZIONE" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *       &lt;attribute name="RICORSO_ASTA_ELETTRONICA" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *       &lt;attribute name="NOTE_ASTA_ELETTRONICA">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="1000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="FLAG_APP" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiProceduraType")
public class DatiProceduraType {

    @XmlAttribute(name = "FLAG_PROCEDURA_ACCELLERATA")
    protected FlagSNType flagproceduraaccellerata;
    @XmlAttribute(name = "MOTIVAZIONE_PROCEDURA_ACCELLERATA")
    protected String motivazioneproceduraaccellerata;
    @XmlAttribute(name = "TIPO_OPERATORI_AQ")
    protected String tipooperatoriaq;
    @XmlAttribute(name = "NUM_MAX_PARTECIPANTI_AQ")
    protected Integer nummaxpartecipantiaq;
    @XmlAttribute(name = "ALTRI_ACQUIRENTI_SIS_DINAMICO")
    protected FlagSNType altriacquirentisisdinamico;
    @XmlAttribute(name = "NOTE_AQ_QUATTRO_ANNI")
    protected String noteaqquattroanni;
    @XmlAttribute(name = "AGGIUDICAZIONE_SENZA_NEGOZIAZIONE")
    protected FlagSNType aggiudicazionesenzanegoziazione;
    @XmlAttribute(name = "RICORSO_ASTA_ELETTRONICA")
    protected FlagSNType ricorsoastaelettronica;
    @XmlAttribute(name = "NOTE_ASTA_ELETTRONICA")
    protected String noteastaelettronica;
    @XmlAttribute(name = "FLAG_APP")
    protected FlagSNType flagapp;

    /**
     * Gets the value of the flagproceduraaccellerata property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getFLAGPROCEDURAACCELLERATA() {
        return flagproceduraaccellerata;
    }

    /**
     * Sets the value of the flagproceduraaccellerata property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setFLAGPROCEDURAACCELLERATA(FlagSNType value) {
        this.flagproceduraaccellerata = value;
    }

    /**
     * Gets the value of the motivazioneproceduraaccellerata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOTIVAZIONEPROCEDURAACCELLERATA() {
        return motivazioneproceduraaccellerata;
    }

    /**
     * Sets the value of the motivazioneproceduraaccellerata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOTIVAZIONEPROCEDURAACCELLERATA(String value) {
        this.motivazioneproceduraaccellerata = value;
    }

    /**
     * Gets the value of the tipooperatoriaq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIPOOPERATORIAQ() {
        return tipooperatoriaq;
    }

    /**
     * Sets the value of the tipooperatoriaq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIPOOPERATORIAQ(String value) {
        this.tipooperatoriaq = value;
    }

    /**
     * Gets the value of the nummaxpartecipantiaq property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNUMMAXPARTECIPANTIAQ() {
        return nummaxpartecipantiaq;
    }

    /**
     * Sets the value of the nummaxpartecipantiaq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNUMMAXPARTECIPANTIAQ(Integer value) {
        this.nummaxpartecipantiaq = value;
    }

    /**
     * Gets the value of the altriacquirentisisdinamico property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getALTRIACQUIRENTISISDINAMICO() {
        return altriacquirentisisdinamico;
    }

    /**
     * Sets the value of the altriacquirentisisdinamico property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setALTRIACQUIRENTISISDINAMICO(FlagSNType value) {
        this.altriacquirentisisdinamico = value;
    }

    /**
     * Gets the value of the noteaqquattroanni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOTEAQQUATTROANNI() {
        return noteaqquattroanni;
    }

    /**
     * Sets the value of the noteaqquattroanni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOTEAQQUATTROANNI(String value) {
        this.noteaqquattroanni = value;
    }

    /**
     * Gets the value of the aggiudicazionesenzanegoziazione property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getAGGIUDICAZIONESENZANEGOZIAZIONE() {
        return aggiudicazionesenzanegoziazione;
    }

    /**
     * Sets the value of the aggiudicazionesenzanegoziazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setAGGIUDICAZIONESENZANEGOZIAZIONE(FlagSNType value) {
        this.aggiudicazionesenzanegoziazione = value;
    }

    /**
     * Gets the value of the ricorsoastaelettronica property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getRICORSOASTAELETTRONICA() {
        return ricorsoastaelettronica;
    }

    /**
     * Sets the value of the ricorsoastaelettronica property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setRICORSOASTAELETTRONICA(FlagSNType value) {
        this.ricorsoastaelettronica = value;
    }

    /**
     * Gets the value of the noteastaelettronica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOTEASTAELETTRONICA() {
        return noteastaelettronica;
    }

    /**
     * Sets the value of the noteastaelettronica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOTEASTAELETTRONICA(String value) {
        this.noteastaelettronica = value;
    }

    /**
     * Gets the value of the flagapp property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getFLAGAPP() {
        return flagapp;
    }

    /**
     * Sets the value of the flagapp property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setFLAGAPP(FlagSNType value) {
        this.flagapp = value;
    }

}
