//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 02:39:54 PM CEST 
//


package it.anticorruzione.ted.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeltaGaraTED complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeltaGaraTED">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DATI_AMM_AGGIUDICATRICE" type="{http://xml.ted.anticorruzione.it}AddrS1Type" maxOccurs="500"/>
 *         &lt;element name="ALTRO_INDIRIZZO_IA" type="{http://xml.ted.anticorruzione.it}AddrS1Type" minOccurs="0"/>
 *         &lt;element name="ALTRO_INDIRIZZO_PARTECIPAZIONE" type="{http://xml.ted.anticorruzione.it}AddrS1Type" minOccurs="0"/>
 *         &lt;element name="ALTRE_INFO" type="{http://xml.ted.anticorruzione.it}AltreInfoType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="NORMATIVE_APP_CONGIUNTO">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="200"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="APPALTO_CC" use="required" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *       &lt;attribute name="DOCUMENTI_DISPONIBILI" use="required" type="{http://xml.ted.anticorruzione.it}DocDisponibiliType" />
 *       &lt;attribute name="URL_DOC_DISPONIBILI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="250"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="INFO_AGGIUNTIVE" use="required" type="{http://xml.ted.anticorruzione.it}AltroIndirizzoType" />
 *       &lt;attribute name="URL_VERSIONE_ELETTRONICA">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="250"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="URL_STRUMENTI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="250"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TIPO_AMM_AGG" use="required" type="{http://xml.ted.anticorruzione.it}AmmAggType" />
 *       &lt;attribute name="ALTRO_TIPO_AMM_AGG">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="400"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SETTORE_PRINCIPALE" use="required" type="{http://xml.ted.anticorruzione.it}SettorePrincipaleType" />
 *       &lt;attribute name="ALTRO_SETTORE_PRINCIPALE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="200"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeltaGaraTED", propOrder = {
    "datiammaggiudicatrice",
    "altroindirizzoia",
    "altroindirizzopartecipazione",
    "altreinfo"
})
public class DeltaGaraTED {

    @XmlElement(name = "DATI_AMM_AGGIUDICATRICE", required = true)
    protected List<AddrS1Type> datiammaggiudicatrice;
    @XmlElement(name = "ALTRO_INDIRIZZO_IA")
    protected AddrS1Type altroindirizzoia;
    @XmlElement(name = "ALTRO_INDIRIZZO_PARTECIPAZIONE")
    protected AddrS1Type altroindirizzopartecipazione;
    @XmlElement(name = "ALTRE_INFO", required = true)
    protected AltreInfoType altreinfo;
    @XmlAttribute(name = "NORMATIVE_APP_CONGIUNTO")
    protected String normativeappcongiunto;
    @XmlAttribute(name = "APPALTO_CC", required = true)
    protected FlagSNType appaltocc;
    @XmlAttribute(name = "DOCUMENTI_DISPONIBILI", required = true)
    protected String documentidisponibili;
    @XmlAttribute(name = "URL_DOC_DISPONIBILI")
    protected String urldocdisponibili;
    @XmlAttribute(name = "INFO_AGGIUNTIVE", required = true)
    protected String infoaggiuntive;
    @XmlAttribute(name = "URL_VERSIONE_ELETTRONICA")
    protected String urlversioneelettronica;
    @XmlAttribute(name = "URL_STRUMENTI")
    protected String urlstrumenti;
    @XmlAttribute(name = "TIPO_AMM_AGG", required = true)
    protected String tipoammagg;
    @XmlAttribute(name = "ALTRO_TIPO_AMM_AGG")
    protected String altrotipoammagg;
    @XmlAttribute(name = "SETTORE_PRINCIPALE", required = true)
    protected String settoreprincipale;
    @XmlAttribute(name = "ALTRO_SETTORE_PRINCIPALE")
    protected String altrosettoreprincipale;

    /**
     * Gets the value of the datiammaggiudicatrice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datiammaggiudicatrice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDATIAMMAGGIUDICATRICE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddrS1Type }
     * 
     * 
     */
    public List<AddrS1Type> getDATIAMMAGGIUDICATRICE() {
        if (datiammaggiudicatrice == null) {
            datiammaggiudicatrice = new ArrayList<AddrS1Type>();
        }
        return this.datiammaggiudicatrice;
    }

    /**
     * Gets the value of the altroindirizzoia property.
     * 
     * @return
     *     possible object is
     *     {@link AddrS1Type }
     *     
     */
    public AddrS1Type getALTROINDIRIZZOIA() {
        return altroindirizzoia;
    }

    /**
     * Sets the value of the altroindirizzoia property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddrS1Type }
     *     
     */
    public void setALTROINDIRIZZOIA(AddrS1Type value) {
        this.altroindirizzoia = value;
    }

    /**
     * Gets the value of the altroindirizzopartecipazione property.
     * 
     * @return
     *     possible object is
     *     {@link AddrS1Type }
     *     
     */
    public AddrS1Type getALTROINDIRIZZOPARTECIPAZIONE() {
        return altroindirizzopartecipazione;
    }

    /**
     * Sets the value of the altroindirizzopartecipazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddrS1Type }
     *     
     */
    public void setALTROINDIRIZZOPARTECIPAZIONE(AddrS1Type value) {
        this.altroindirizzopartecipazione = value;
    }

    /**
     * Gets the value of the altreinfo property.
     * 
     * @return
     *     possible object is
     *     {@link AltreInfoType }
     *     
     */
    public AltreInfoType getALTREINFO() {
        return altreinfo;
    }

    /**
     * Sets the value of the altreinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltreInfoType }
     *     
     */
    public void setALTREINFO(AltreInfoType value) {
        this.altreinfo = value;
    }

    /**
     * Gets the value of the normativeappcongiunto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNORMATIVEAPPCONGIUNTO() {
        return normativeappcongiunto;
    }

    /**
     * Sets the value of the normativeappcongiunto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNORMATIVEAPPCONGIUNTO(String value) {
        this.normativeappcongiunto = value;
    }

    /**
     * Gets the value of the appaltocc property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getAPPALTOCC() {
        return appaltocc;
    }

    /**
     * Sets the value of the appaltocc property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setAPPALTOCC(FlagSNType value) {
        this.appaltocc = value;
    }

    /**
     * Gets the value of the documentidisponibili property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCUMENTIDISPONIBILI() {
        return documentidisponibili;
    }

    /**
     * Sets the value of the documentidisponibili property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCUMENTIDISPONIBILI(String value) {
        this.documentidisponibili = value;
    }

    /**
     * Gets the value of the urldocdisponibili property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURLDOCDISPONIBILI() {
        return urldocdisponibili;
    }

    /**
     * Sets the value of the urldocdisponibili property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURLDOCDISPONIBILI(String value) {
        this.urldocdisponibili = value;
    }

    /**
     * Gets the value of the infoaggiuntive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINFOAGGIUNTIVE() {
        return infoaggiuntive;
    }

    /**
     * Sets the value of the infoaggiuntive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINFOAGGIUNTIVE(String value) {
        this.infoaggiuntive = value;
    }

    /**
     * Gets the value of the urlversioneelettronica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURLVERSIONEELETTRONICA() {
        return urlversioneelettronica;
    }

    /**
     * Sets the value of the urlversioneelettronica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURLVERSIONEELETTRONICA(String value) {
        this.urlversioneelettronica = value;
    }

    /**
     * Gets the value of the urlstrumenti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURLSTRUMENTI() {
        return urlstrumenti;
    }

    /**
     * Sets the value of the urlstrumenti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURLSTRUMENTI(String value) {
        this.urlstrumenti = value;
    }

    /**
     * Gets the value of the tipoammagg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIPOAMMAGG() {
        return tipoammagg;
    }

    /**
     * Sets the value of the tipoammagg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIPOAMMAGG(String value) {
        this.tipoammagg = value;
    }

    /**
     * Gets the value of the altrotipoammagg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getALTROTIPOAMMAGG() {
        return altrotipoammagg;
    }

    /**
     * Sets the value of the altrotipoammagg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setALTROTIPOAMMAGG(String value) {
        this.altrotipoammagg = value;
    }

    /**
     * Gets the value of the settoreprincipale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSETTOREPRINCIPALE() {
        return settoreprincipale;
    }

    /**
     * Sets the value of the settoreprincipale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSETTOREPRINCIPALE(String value) {
        this.settoreprincipale = value;
    }

    /**
     * Gets the value of the altrosettoreprincipale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getALTROSETTOREPRINCIPALE() {
        return altrosettoreprincipale;
    }

    /**
     * Sets the value of the altrosettoreprincipale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setALTROSETTOREPRINCIPALE(String value) {
        this.altrosettoreprincipale = value;
    }

}
