//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 02:39:54 PM CEST 
//


package it.anticorruzione.ted.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeltaLotto" type="{http://xml.ted.anticorruzione.it}DeltaLottoTED"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deltaLotto"
})
@XmlRootElement(name = "DeltaLottoWS")
public class DeltaLottoWS {

    @XmlElement(name = "DeltaLotto", required = true)
    protected DeltaLottoTED deltaLotto;

    /**
     * Gets the value of the deltaLotto property.
     * 
     * @return
     *     possible object is
     *     {@link DeltaLottoTED }
     *     
     */
    public DeltaLottoTED getDeltaLotto() {
        return deltaLotto;
    }

    /**
     * Sets the value of the deltaLotto property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeltaLottoTED }
     *     
     */
    public void setDeltaLotto(DeltaLottoTED value) {
        this.deltaLotto = value;
    }

}
