//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 02:39:54 PM CEST 
//


package it.anticorruzione.ted.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntitaAppaltoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntitaAppaltoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="TITOLO_PROCEDURA_GARA" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="400"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CPV_GARA" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="12"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="MAX_LOTTI_PARTECIPAZIONE" type="{http://xml.ted.anticorruzione.it}MaxLottiPartecipazioneType" />
 *       &lt;attribute name="NUM_MAX_LOTTI_PARTECIPAZIONE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="1000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NUM_MAX_LOTTI_OFFERENTE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="1000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="FLAG_SA_AGG_GRUPPI_LOTTI" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *       &lt;attribute name="SA_AGG_GRUPPI_LOTTI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="1000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntitaAppaltoType")
public class EntitaAppaltoType {

    @XmlAttribute(name = "TITOLO_PROCEDURA_GARA", required = true)
    protected String titoloproceduragara;
    @XmlAttribute(name = "CPV_GARA", required = true)
    protected String cpvgara;
    @XmlAttribute(name = "MAX_LOTTI_PARTECIPAZIONE")
    protected String maxlottipartecipazione;
    @XmlAttribute(name = "NUM_MAX_LOTTI_PARTECIPAZIONE")
    protected Integer nummaxlottipartecipazione;
    @XmlAttribute(name = "NUM_MAX_LOTTI_OFFERENTE")
    protected Integer nummaxlottiofferente;
    @XmlAttribute(name = "FLAG_SA_AGG_GRUPPI_LOTTI")
    protected FlagSNType flagsaagggruppilotti;
    @XmlAttribute(name = "SA_AGG_GRUPPI_LOTTI")
    protected String saagggruppilotti;

    /**
     * Gets the value of the titoloproceduragara property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTITOLOPROCEDURAGARA() {
        return titoloproceduragara;
    }

    /**
     * Sets the value of the titoloproceduragara property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTITOLOPROCEDURAGARA(String value) {
        this.titoloproceduragara = value;
    }

    /**
     * Gets the value of the cpvgara property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPVGARA() {
        return cpvgara;
    }

    /**
     * Sets the value of the cpvgara property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPVGARA(String value) {
        this.cpvgara = value;
    }

    /**
     * Gets the value of the maxlottipartecipazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAXLOTTIPARTECIPAZIONE() {
        return maxlottipartecipazione;
    }

    /**
     * Sets the value of the maxlottipartecipazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAXLOTTIPARTECIPAZIONE(String value) {
        this.maxlottipartecipazione = value;
    }

    /**
     * Gets the value of the nummaxlottipartecipazione property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNUMMAXLOTTIPARTECIPAZIONE() {
        return nummaxlottipartecipazione;
    }

    /**
     * Sets the value of the nummaxlottipartecipazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNUMMAXLOTTIPARTECIPAZIONE(Integer value) {
        this.nummaxlottipartecipazione = value;
    }

    /**
     * Gets the value of the nummaxlottiofferente property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNUMMAXLOTTIOFFERENTE() {
        return nummaxlottiofferente;
    }

    /**
     * Sets the value of the nummaxlottiofferente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNUMMAXLOTTIOFFERENTE(Integer value) {
        this.nummaxlottiofferente = value;
    }

    /**
     * Gets the value of the flagsaagggruppilotti property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getFLAGSAAGGGRUPPILOTTI() {
        return flagsaagggruppilotti;
    }

    /**
     * Sets the value of the flagsaagggruppilotti property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setFLAGSAAGGGRUPPILOTTI(FlagSNType value) {
        this.flagsaagggruppilotti = value;
    }

    /**
     * Gets the value of the saagggruppilotti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSAAGGGRUPPILOTTI() {
        return saagggruppilotti;
    }

    /**
     * Sets the value of the saagggruppilotti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSAAGGGRUPPILOTTI(String value) {
        this.saagggruppilotti = value;
    }

}
