//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 02:39:54 PM CEST 
//


package it.anticorruzione.ted.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for InfoAmministrativeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InfoAmministrativeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="PERIODO_VALIDITA_OFFERTE" type="{http://xml.ted.anticorruzione.it}DbDateType" />
 *       &lt;attribute name="MESI_VALIDITA_OFFERTE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DATA_APERTURA_OFFERTE" type="{http://xml.ted.anticorruzione.it}DbDateType" />
 *       &lt;attribute name="ORA_APERTURA_OFFERTE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;length value="5"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="LUOGO_APERTURA_OFFERTE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="400"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="PERSONE_APERTURA_OFFERTE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="1000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfoAmministrativeType")
public class InfoAmministrativeType {

    @XmlAttribute(name = "PERIODO_VALIDITA_OFFERTE")
    protected XMLGregorianCalendar periodovaliditaofferte;
    @XmlAttribute(name = "MESI_VALIDITA_OFFERTE")
    protected Integer mesivaliditaofferte;
    @XmlAttribute(name = "DATA_APERTURA_OFFERTE")
    protected XMLGregorianCalendar dataaperturaofferte;
    @XmlAttribute(name = "ORA_APERTURA_OFFERTE")
    protected String oraaperturaofferte;
    @XmlAttribute(name = "LUOGO_APERTURA_OFFERTE")
    protected String luogoaperturaofferte;
    @XmlAttribute(name = "PERSONE_APERTURA_OFFERTE")
    protected String personeaperturaofferte;

    /**
     * Gets the value of the periodovaliditaofferte property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPERIODOVALIDITAOFFERTE() {
        return periodovaliditaofferte;
    }

    /**
     * Sets the value of the periodovaliditaofferte property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPERIODOVALIDITAOFFERTE(XMLGregorianCalendar value) {
        this.periodovaliditaofferte = value;
    }

    /**
     * Gets the value of the mesivaliditaofferte property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMESIVALIDITAOFFERTE() {
        return mesivaliditaofferte;
    }

    /**
     * Sets the value of the mesivaliditaofferte property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMESIVALIDITAOFFERTE(Integer value) {
        this.mesivaliditaofferte = value;
    }

    /**
     * Gets the value of the dataaperturaofferte property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDATAAPERTURAOFFERTE() {
        return dataaperturaofferte;
    }

    /**
     * Sets the value of the dataaperturaofferte property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDATAAPERTURAOFFERTE(XMLGregorianCalendar value) {
        this.dataaperturaofferte = value;
    }

    /**
     * Gets the value of the oraaperturaofferte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORAAPERTURAOFFERTE() {
        return oraaperturaofferte;
    }

    /**
     * Sets the value of the oraaperturaofferte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORAAPERTURAOFFERTE(String value) {
        this.oraaperturaofferte = value;
    }

    /**
     * Gets the value of the luogoaperturaofferte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLUOGOAPERTURAOFFERTE() {
        return luogoaperturaofferte;
    }

    /**
     * Sets the value of the luogoaperturaofferte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLUOGOAPERTURAOFFERTE(String value) {
        this.luogoaperturaofferte = value;
    }

    /**
     * Gets the value of the personeaperturaofferte property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPERSONEAPERTURAOFFERTE() {
        return personeaperturaofferte;
    }

    /**
     * Sets the value of the personeaperturaofferte property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPERSONEAPERTURAOFFERTE(String value) {
        this.personeaperturaofferte = value;
    }

}
