//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 02:39:54 PM CEST 
//


package it.anticorruzione.ted.xml;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ModificaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModificaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CPV_SECONDARIE" type="{http://xml.ted.anticorruzione.it}ModificaCpvSecType" maxOccurs="100" minOccurs="0"/>
 *         &lt;element name="NUTS" type="{http://xml.ted.anticorruzione.it}LuogoNutsType" maxOccurs="20"/>
 *         &lt;element name="CONTRAENTE" type="{http://xml.ted.anticorruzione.it}ContraenteType" maxOccurs="100"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CPV_PRINCIPALE" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="12"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="LUOGO_ESEC_PRINCIPALE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="200"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DESC_PROCUREMENT" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="10000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DURATA_CONTRATTO_MESI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DURATA_CONTRATTO_GIORNI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="9999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="INIZIO_CONTRATTO_LOTTO" type="{http://xml.ted.anticorruzione.it}DbDateType" />
 *       &lt;attribute name="FINE_CONTRATTO_LOTTO" type="{http://xml.ted.anticorruzione.it}DbDateType" />
 *       &lt;attribute name="JUSTIFICATION">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="400"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="VAL_TOTAL" use="required" type="{http://xml.ted.anticorruzione.it}ImportoType" />
 *       &lt;attribute name="AWARDED_TO_GROUP" use="required" type="{http://xml.ted.anticorruzione.it}FlagSNType" />
 *       &lt;attribute name="DESC_NATURE_CHANGES" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="6000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="REASON_MODIFICATION" use="required" type="{http://xml.ted.anticorruzione.it}ReasonModificationType" />
 *       &lt;attribute name="DESC_REASON_MODIFICATION" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="6000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="VAL_TOTAL_BEFORE" use="required" type="{http://xml.ted.anticorruzione.it}ImportoType" />
 *       &lt;attribute name="VAL_TOTAL_AFTER" use="required" type="{http://xml.ted.anticorruzione.it}ImportoType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModificaType", propOrder = {
    "cpvsecondarie",
    "nuts",
    "contraente"
})
public class ModificaType {

    @XmlElement(name = "CPV_SECONDARIE")
    protected List<ModificaCpvSecType> cpvsecondarie;
    @XmlElement(name = "NUTS", required = true)
    protected List<String> nuts;
    @XmlElement(name = "CONTRAENTE", required = true)
    protected List<ContraenteType> contraente;
    @XmlAttribute(name = "CPV_PRINCIPALE", required = true)
    protected String cpvprincipale;
    @XmlAttribute(name = "LUOGO_ESEC_PRINCIPALE")
    protected String luogoesecprincipale;
    @XmlAttribute(name = "DESC_PROCUREMENT", required = true)
    protected String descprocurement;
    @XmlAttribute(name = "DURATA_CONTRATTO_MESI")
    protected Integer duratacontrattomesi;
    @XmlAttribute(name = "DURATA_CONTRATTO_GIORNI")
    protected Integer duratacontrattogiorni;
    @XmlAttribute(name = "INIZIO_CONTRATTO_LOTTO")
    protected XMLGregorianCalendar iniziocontrattolotto;
    @XmlAttribute(name = "FINE_CONTRATTO_LOTTO")
    protected XMLGregorianCalendar finecontrattolotto;
    @XmlAttribute(name = "JUSTIFICATION")
    protected String justification;
    @XmlAttribute(name = "VAL_TOTAL", required = true)
    protected BigDecimal valtotal;
    @XmlAttribute(name = "AWARDED_TO_GROUP", required = true)
    protected FlagSNType awardedtogroup;
    @XmlAttribute(name = "DESC_NATURE_CHANGES", required = true)
    protected String descnaturechanges;
    @XmlAttribute(name = "REASON_MODIFICATION", required = true)
    protected String reasonmodification;
    @XmlAttribute(name = "DESC_REASON_MODIFICATION", required = true)
    protected String descreasonmodification;
    @XmlAttribute(name = "VAL_TOTAL_BEFORE", required = true)
    protected BigDecimal valtotalbefore;
    @XmlAttribute(name = "VAL_TOTAL_AFTER", required = true)
    protected BigDecimal valtotalafter;

    /**
     * Gets the value of the cpvsecondarie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cpvsecondarie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCPVSECONDARIE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModificaCpvSecType }
     * 
     * 
     */
    public List<ModificaCpvSecType> getCPVSECONDARIE() {
        if (cpvsecondarie == null) {
            cpvsecondarie = new ArrayList<ModificaCpvSecType>();
        }
        return this.cpvsecondarie;
    }

    /**
     * Gets the value of the nuts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nuts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNUTS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNUTS() {
        if (nuts == null) {
            nuts = new ArrayList<String>();
        }
        return this.nuts;
    }

    /**
     * Gets the value of the contraente property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contraente property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCONTRAENTE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContraenteType }
     * 
     * 
     */
    public List<ContraenteType> getCONTRAENTE() {
        if (contraente == null) {
            contraente = new ArrayList<ContraenteType>();
        }
        return this.contraente;
    }

    /**
     * Gets the value of the cpvprincipale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPVPRINCIPALE() {
        return cpvprincipale;
    }

    /**
     * Sets the value of the cpvprincipale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPVPRINCIPALE(String value) {
        this.cpvprincipale = value;
    }

    /**
     * Gets the value of the luogoesecprincipale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLUOGOESECPRINCIPALE() {
        return luogoesecprincipale;
    }

    /**
     * Sets the value of the luogoesecprincipale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLUOGOESECPRINCIPALE(String value) {
        this.luogoesecprincipale = value;
    }

    /**
     * Gets the value of the descprocurement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCPROCUREMENT() {
        return descprocurement;
    }

    /**
     * Sets the value of the descprocurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCPROCUREMENT(String value) {
        this.descprocurement = value;
    }

    /**
     * Gets the value of the duratacontrattomesi property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDURATACONTRATTOMESI() {
        return duratacontrattomesi;
    }

    /**
     * Sets the value of the duratacontrattomesi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDURATACONTRATTOMESI(Integer value) {
        this.duratacontrattomesi = value;
    }

    /**
     * Gets the value of the duratacontrattogiorni property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDURATACONTRATTOGIORNI() {
        return duratacontrattogiorni;
    }

    /**
     * Sets the value of the duratacontrattogiorni property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDURATACONTRATTOGIORNI(Integer value) {
        this.duratacontrattogiorni = value;
    }

    /**
     * Gets the value of the iniziocontrattolotto property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getINIZIOCONTRATTOLOTTO() {
        return iniziocontrattolotto;
    }

    /**
     * Sets the value of the iniziocontrattolotto property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setINIZIOCONTRATTOLOTTO(XMLGregorianCalendar value) {
        this.iniziocontrattolotto = value;
    }

    /**
     * Gets the value of the finecontrattolotto property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFINECONTRATTOLOTTO() {
        return finecontrattolotto;
    }

    /**
     * Sets the value of the finecontrattolotto property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFINECONTRATTOLOTTO(XMLGregorianCalendar value) {
        this.finecontrattolotto = value;
    }

    /**
     * Gets the value of the justification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJUSTIFICATION() {
        return justification;
    }

    /**
     * Sets the value of the justification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJUSTIFICATION(String value) {
        this.justification = value;
    }

    /**
     * Gets the value of the valtotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVALTOTAL() {
        return valtotal;
    }

    /**
     * Sets the value of the valtotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVALTOTAL(BigDecimal value) {
        this.valtotal = value;
    }

    /**
     * Gets the value of the awardedtogroup property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getAWARDEDTOGROUP() {
        return awardedtogroup;
    }

    /**
     * Sets the value of the awardedtogroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setAWARDEDTOGROUP(FlagSNType value) {
        this.awardedtogroup = value;
    }

    /**
     * Gets the value of the descnaturechanges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCNATURECHANGES() {
        return descnaturechanges;
    }

    /**
     * Sets the value of the descnaturechanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCNATURECHANGES(String value) {
        this.descnaturechanges = value;
    }

    /**
     * Gets the value of the reasonmodification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREASONMODIFICATION() {
        return reasonmodification;
    }

    /**
     * Sets the value of the reasonmodification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREASONMODIFICATION(String value) {
        this.reasonmodification = value;
    }

    /**
     * Gets the value of the descreasonmodification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCREASONMODIFICATION() {
        return descreasonmodification;
    }

    /**
     * Sets the value of the descreasonmodification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCREASONMODIFICATION(String value) {
        this.descreasonmodification = value;
    }

    /**
     * Gets the value of the valtotalbefore property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVALTOTALBEFORE() {
        return valtotalbefore;
    }

    /**
     * Sets the value of the valtotalbefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVALTOTALBEFORE(BigDecimal value) {
        this.valtotalbefore = value;
    }

    /**
     * Gets the value of the valtotalafter property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVALTOTALAFTER() {
        return valtotalafter;
    }

    /**
     * Sets the value of the valtotalafter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVALTOTALAFTER(BigDecimal value) {
        this.valtotalafter = value;
    }

}
