//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 02:39:54 PM CEST 
//


package it.anticorruzione.ted.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RettificaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RettificaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RETTIFICA_CPV_SEC" type="{http://xml.ted.anticorruzione.it}RettificaCpvSecType" maxOccurs="100" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SECTION_NUMBER" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="20"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SECTION_TO_MODIFY">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="400"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="OLD_VALUE_TEXT">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="10000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NEW_VALUE_TEXT">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="10000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="OLD_MAIN_CPV">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="12"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NEW_MAIN_CPV">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="12"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="OLD_VALUE_DATE" type="{http://xml.ted.anticorruzione.it}DbDateType" />
 *       &lt;attribute name="NEW_VALUE_DATE" type="{http://xml.ted.anticorruzione.it}DbDateType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RettificaType", propOrder = {
    "rettificacpvsec"
})
public class RettificaType {

    @XmlElement(name = "RETTIFICA_CPV_SEC")
    protected List<RettificaCpvSecType> rettificacpvsec;
    @XmlAttribute(name = "SECTION_NUMBER", required = true)
    protected String sectionnumber;
    @XmlAttribute(name = "SECTION_TO_MODIFY")
    protected String sectiontomodify;
    @XmlAttribute(name = "OLD_VALUE_TEXT")
    protected String oldvaluetext;
    @XmlAttribute(name = "NEW_VALUE_TEXT")
    protected String newvaluetext;
    @XmlAttribute(name = "OLD_MAIN_CPV")
    protected String oldmaincpv;
    @XmlAttribute(name = "NEW_MAIN_CPV")
    protected String newmaincpv;
    @XmlAttribute(name = "OLD_VALUE_DATE")
    protected XMLGregorianCalendar oldvaluedate;
    @XmlAttribute(name = "NEW_VALUE_DATE")
    protected XMLGregorianCalendar newvaluedate;

    /**
     * Gets the value of the rettificacpvsec property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rettificacpvsec property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRETTIFICACPVSEC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RettificaCpvSecType }
     * 
     * 
     */
    public List<RettificaCpvSecType> getRETTIFICACPVSEC() {
        if (rettificacpvsec == null) {
            rettificacpvsec = new ArrayList<RettificaCpvSecType>();
        }
        return this.rettificacpvsec;
    }

    /**
     * Gets the value of the sectionnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECTIONNUMBER() {
        return sectionnumber;
    }

    /**
     * Sets the value of the sectionnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECTIONNUMBER(String value) {
        this.sectionnumber = value;
    }

    /**
     * Gets the value of the sectiontomodify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECTIONTOMODIFY() {
        return sectiontomodify;
    }

    /**
     * Sets the value of the sectiontomodify property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECTIONTOMODIFY(String value) {
        this.sectiontomodify = value;
    }

    /**
     * Gets the value of the oldvaluetext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOLDVALUETEXT() {
        return oldvaluetext;
    }

    /**
     * Sets the value of the oldvaluetext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOLDVALUETEXT(String value) {
        this.oldvaluetext = value;
    }

    /**
     * Gets the value of the newvaluetext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNEWVALUETEXT() {
        return newvaluetext;
    }

    /**
     * Sets the value of the newvaluetext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNEWVALUETEXT(String value) {
        this.newvaluetext = value;
    }

    /**
     * Gets the value of the oldmaincpv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOLDMAINCPV() {
        return oldmaincpv;
    }

    /**
     * Sets the value of the oldmaincpv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOLDMAINCPV(String value) {
        this.oldmaincpv = value;
    }

    /**
     * Gets the value of the newmaincpv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNEWMAINCPV() {
        return newmaincpv;
    }

    /**
     * Sets the value of the newmaincpv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNEWMAINCPV(String value) {
        this.newmaincpv = value;
    }

    /**
     * Gets the value of the oldvaluedate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOLDVALUEDATE() {
        return oldvaluedate;
    }

    /**
     * Sets the value of the oldvaluedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOLDVALUEDATE(XMLGregorianCalendar value) {
        this.oldvaluedate = value;
    }

    /**
     * Gets the value of the newvaluedate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNEWVALUEDATE() {
        return newvaluedate;
    }

    /**
     * Sets the value of the newvaluedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNEWVALUEDATE(XMLGregorianCalendar value) {
        this.newvaluedate = value;
    }

}
