//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 02:39:54 PM CEST 
//


package it.anticorruzione.ted.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SezioneType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SezioneType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PA"/>
 *     &lt;enumeration value="RA"/>
 *     &lt;enumeration value="IN"/>
 *     &lt;enumeration value="CO"/>
 *     &lt;enumeration value="RE"/>
 *     &lt;enumeration value="RS"/>
 *     &lt;enumeration value="RQ"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SezioneType")
@XmlEnum
public enum SezioneType {

    PA,
    RA,
    IN,
    CO,
    RE,
    RS,
    RQ;

    public String value() {
        return name();
    }

    public static SezioneType fromValue(String v) {
        return valueOf(v);
    }

}
