//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 02:39:54 PM CEST 
//


package it.anticorruzione.ted.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipiOperazioneType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TipiOperazioneType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="INSERIMENTO"/>
 *     &lt;enumeration value="MODIFICA"/>
 *     &lt;enumeration value="ELIMINAZIONE"/>
 *     &lt;enumeration value="VARIAZIONE_ANAG"/>
 *     &lt;enumeration value="VARIAZIONE_SA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TipiOperazioneType")
@XmlEnum
public enum TipiOperazioneType {

    INSERIMENTO,
    MODIFICA,
    ELIMINAZIONE,
    VARIAZIONE_ANAG,
    VARIAZIONE_SA;

    public String value() {
        return name();
    }

    public static TipiOperazioneType fromValue(String v) {
        return valueOf(v);
    }

}
