//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 02:39:54 PM CEST 
//


package it.anticorruzione.ted.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValoreAppaltoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValoreAppaltoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="VAL_TOTAL" type="{http://xml.ted.anticorruzione.it}ImportoType" />
 *       &lt;attribute name="VAL_RANGE_TOTAL_LOW" type="{http://xml.ted.anticorruzione.it}ImportoType" />
 *       &lt;attribute name="VAL_RANGE_TOTAL_HIGH" type="{http://xml.ted.anticorruzione.it}ImportoType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValoreAppaltoType")
public class ValoreAppaltoType {

    @XmlAttribute(name = "VAL_TOTAL")
    protected BigDecimal valtotal;
    @XmlAttribute(name = "VAL_RANGE_TOTAL_LOW")
    protected BigDecimal valrangetotallow;
    @XmlAttribute(name = "VAL_RANGE_TOTAL_HIGH")
    protected BigDecimal valrangetotalhigh;

    /**
     * Gets the value of the valtotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVALTOTAL() {
        return valtotal;
    }

    /**
     * Sets the value of the valtotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVALTOTAL(BigDecimal value) {
        this.valtotal = value;
    }

    /**
     * Gets the value of the valrangetotallow property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVALRANGETOTALLOW() {
        return valrangetotallow;
    }

    /**
     * Sets the value of the valrangetotallow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVALRANGETOTALLOW(BigDecimal value) {
        this.valrangetotallow = value;
    }

    /**
     * Gets the value of the valrangetotalhigh property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVALRANGETOTALHIGH() {
        return valrangetotalhigh;
    }

    /**
     * Sets the value of the valrangetotalhigh property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVALRANGETOTALHIGH(BigDecimal value) {
        this.valrangetotalhigh = value;
    }

}
