#------------------------------------------------------------------------------
# Name:                 massloader.properties
# Type:                 Properties file
# Purpose:              parametri configurazione si SIMOG - MassLoader
# Created:              03/08/2007
#=== COMPONENT-ID ===================================================
# Project:              SIMOG - AVLP
# Layer/partition:      Application Properties
# Developed by:         Step s.r.l.
# Copyright:            All rights reserved
#------------------------------------------------------------------------------

# Configurazione per la connessione a DB
JDBC_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
### produzione ### 
JDBC_STRING=jdbc:sqlserver://10.119.26.41:1433;QueryTimeout=60;SelectMethod=cursor;DatabaseName=simog;user=simog;password=simog.1;sendStringParametersAsUnicode=true;characterEncoding=UTF-8;lockTimeout=60000
#Nome utente da utilizzare nella traccia log di scrittura sul DB
USERNAME=ML_ASSTECN
