package it.avcp.avcpass;

public enum AVCPassFunzioneEnum {

//RUP   
   WEB_REQUISITI_CREATE("R01"),
   WEB_REQUISITI_UPDATE("R02"),
   WEB_REQUISITI_DELETE("R03"),
   WEB_DATI_RIPETIZIONI_UPDATE("R04"),
   WEB_CONTRATTO_ESCLUSO_UPDATE("R05"),
   WEB_MOV_TO_ACCORDO_QUADRO("R06"),
   WEB_PUBBLICA_RETTIFICA("R07"),
   WEB_PUBBLICA_RETTIFICA_AVVISO("R13"),
   WEB_GARA_PRESA_IN_CARICO("R08"),
   WEB_DATI_COMUNI_PRESA_IN_CARICO("R09"),
   WEB_ACQUISIZIONE_SCHEDE_AGGIUNTIVE("R10"),
   WEB_GESTIONE_ELENCO_INVITATI("R11"),
   WEB_LOTTO_PERF_PROC_RISTRETTA("R12"),
   WEB_PUBBLICA_AVVISO("R14"),
//ADMIN
   WEB_VARIAZIONE_SA("A01"),
   WEB_RIPRISTINO_LOTTI_CANCELLATI("A02"),
   WEB_GARA_DELETE("A10"),
   WEB_GARA_RIPRISTINA("A11"),
   WEB_GARA_UPDATE("A03"),
   //WEB_MODO_REAL_UPDATE("A04"),// Forse si sovrappone a WEB_MOV_TO_ACCORDO_QUADRO
   WEB_GARA_SBLOCCA("A05"),
   WEB_LOTTO_UPDATE("A06"),
   WEB_LOTTO_DELETE("A07"),
   WEB_LOTTO_PERFEZIONA("A08"),
   WEB_LOTTO_CREATE("A09"),
   WEB_CONFERMA_RETTIFICA("A12"),
//WS(RUP)
   WS_GARA_UPDATE("A03"),
   WS_LOTTO_UPDATE("A06"),
   WS_GARA_DELETE("W01"),
   WS_LOTTO_DELETE("A07"),
   WS_PUBBLICA_RETTIFICA("R07"),
   WS_PUBBLICA_RETTIFICA_AVVISO("R13"),
   WS_LOTTO_PERF_PROC_RISTRETTA("R12"),
   WS_PUBBLICA_AVVISO("R14"),   
   WS_LOTTO_CREATE("W03"),
   WS_REQUISITI_CREATE("R01"), 
   WS_REQUISITI_UPDATE("R02"),
   WS_REQUISITI_DELETE("R03"), 
   WS_GARA_PRESA_IN_CARICO("R08"),
   WS_DATI_COMUNI_PRESA_IN_CARICO("R09"), 
//ML(RUP)
   ML_SCHEDA_AGGIUNTIVE_UPDATE("M02"), 
   ML_SCHEDA_AGGIUNTIVE_DELETE("M03"),
   ML_VARIAZIONE_ANAGRAFICA("M04"),
   ML_VARIAZIONE_SA("A01")
   ;
   
   private String codice;

   private AVCPassFunzioneEnum(String codice) {
      this.codice = codice;
   }

   public String getCodice() {
      return codice;
   }

   public void setCodice(String codice) {
      this.codice = codice;
   }
   
}
