<div id="menu">
	<div class="title">SIMOG Manager</div>
	<ul>
		<li><a href="#">Esporta transazioni</a></li>
		<li><a href="#">Gestione utenze</a></li>
		<li><a href="consultazioneLog.jsp" accesskey="2">Consulta Log</a></li>
		<li><a href="tabelleManager.jsp" accesskey="3">Modifica tabelle di servizio</a></li>
		<li><a href="transazioniManager.jsp">Visualizza transazioni</a></li>
	</ul>
</div>



