<script type="text/javascript">
 
function changeTab(tabName, idmodificato) {  var scelta = true;  if (document.forms[0].elements[idmodificato].value == 1) {  scelta = (typeof i18n !== 'undefined' && i18n.confirm) ? i18n.confirm('error.dataChanged') : confirm("Attenzione ! I dati potrebbero essere cambiati. Prosegui con il rischio di perdere i dati?");  }  if (scelta) {  document.forms[0].elements['<%=PSBD.TAB%>'].value = tabName;  document.forms[0].elements['<%=PSBD.ACTION_TYPE%>'].value = "<%=PSBD.ACTION_LOAD%>";  document.forms[0].submit();  } }
function checkAndChange(tabName, idmodificato) {  if (typeof i18n !== 'undefined' && i18n.alert) { i18n.alert('error.obsoleteFunction'); } else { alert("checkAndChange - funzione obsoleta"); } }
function setFormModified(idmodificato) {  if (document.getElementById("Modificato") != null) document.getElementById("Modificato").value = 1;  document.getElementById(idmodificato).value = 1; }
function resetFormModified(idmodificato) {  document.getElementById(idmodificato).value = 0; }
function salva(tabName) {  if (validateRadios(tabName)) {  var confirmMsg = (typeof i18n !== 'undefined' && i18n.confirm) ? i18n.confirm('error.saveConfirm') : confirm("I dati verranno salvati. Procedere?");  if (confirmMsg) {  document.forms[0].elements['<%=PSBD.TAB%>'].value = tabName;  document.forms[0].elements['<%=PSBD.ACTION_TYPE%>'].value = "<%=PSBD.ACTION_SALVA%>";  if (tabName == "<%=PSBD.TAB_INFO_COMUNI%>") {  document.forms[0].elements['<%= ParametriServlet.SHOW_DATI_COMUNI %>'].value = "true";  }  document.forms[0].submit();  }  } }
function salvaDue(actiontype) {  var confirmMsg = (typeof i18n !== 'undefined' && i18n.confirm) ? i18n.confirm('error.saveConfirm') : confirm("I dati verranno salvati. Procedere?");  if (confirmMsg) {  document.forms[0].elements['<%=PSBD.ACTION_TYPE%>'].value = actiontype;  document.forms[0].submit();  } }
function conferma(tabName) {  var confirmMsg = (typeof i18n !== 'undefined' && i18n.confirm) ? i18n.confirm('error.confirmConfirm') : confirm("I dati verranno confermati. Procedere?");  if (confirmMsg) {  document.forms[0].elements['<%=PSBD.TAB%>'].value = tabName;  document.forms[0].elements['<%=PSBD.ACTION_TYPE%>'].value = "<%=PSBD.ACTION_CONFERMA%>";  if (tabName == "<%=PSBD.TAB_INFO_COMUNI%>") {  document.forms[0].elements['<%= ParametriServlet.SHOW_DATI_COMUNI %>'].value = "true";  }  document.forms[0].submit();  } }
function aggiungi(tabName) {  document.forms[0].elements['<%=PSBD.TAB%>'].value = tabName;  document.forms[0].elements['<%=PSBD.ACTION_TYPE%>'].value = "<%=PSBD.ACTION_AGGIUNGI%>";  setForwardPage(tabName);  document.forms[0].submit(); }
function setForwardPage(tabName) {  if (tabName == "<%=PSBD.TAB_AGGIUDICAZIONE%>") {  document.forms[0].elements['pagina'].value = "scheda1/aggiudicazioni.jsp";  }  if (tabName == "<%=PSBD.TAB_SOTTOSOGLIA%>") {  document.forms[0].elements['pagina'].value = "scheda1/schedaSottosoglia.jsp";  }  if (tabName == "<%=PSBD.TAB_PUBBLICAZIONE_ESITO%>") {  document.forms[0].elements['pagina'].value = "scheda1/pubblicazioneEsito.jsp";  }  if (tabName == "<%=PSBD.TAB_AFFIDATARIO%>") {  document.forms[0].elements['pagina'].value = "scheda1/affidatario.jsp";  }  if (tabName == "<%=PSBD.TAB_RESPONSABILE_PROCEDIMENTO%>") {  document.forms[0].elements['pagina'].value = "scheda1/responsabileProcedimento.jsp";  }  if (tabName == "<%=PSBD.TAB_CONTENZIOSO%>") {  document.forms[0].elements['pagina'].value = "scheda1/contenzioso.jsp";  }  if (tabName == "<%=PSBD.TAB_ADD_CONTENZIOSO%>") {  document.forms[0].elements['pagina'].value = "scheda1/addContenzioso.jsp";  }  if (tabName == "<%=PSBD.TAB_ADD_AFFIDATARIO%>") {  document.forms[0].elements['pagina'].value = "scheda1/addAffidatario.jsp";  }  if (tabName == "<%=PSBD.TAB_RUBRICA_AFFIDATARIO%>") {  document.forms[0].elements['pagina'].value = "scheda1/listaSoggettiPartecipanti.jsp";  }  if (tabName == "<%=PSBD.TAB_INFO_COMUNI%>") {  document.forms[0].elements['pagina'].value = "gestioneAggiudicazioni.jsp";  } }
function reimposta(tabName) {  var scelta = true;  if (tabName == "<%= PSBD.TAB_AGGIUDICAZIONE %>" || tabName == "<%= PSBD.TAB_SOTTOSOGLIA %>" || tabName == "<%= PSBD.TAB_ESCLUSI %>" || tabName == "<%= PSBD.TAB_ADESIONE %>") {  if (document.getElementById("Modificato").value == 1) {  scelta = (typeof i18n !== 'undefined' && i18n.confirm) ? i18n.confirm('error.changesLost') : confirm("Attenzione! In questo modo tutte le modifiche apportate al documento andranno perse. Continuare?");  if (scelta) {  document.forms[0].elements['<%=PSBD.TAB%>'].value = tabName;  document.forms[0].elements['<%=PSBD.ACTION_TYPE%>'].value = "<%=PSBD.ACTION_LOAD%>";  document.forms[0].submit();  }  }  } else {  if (document.getElementById("Modificato0").value == 1) {  scelta = (typeof i18n !== 'undefined' && i18n.confirm) ? i18n.confirm('error.changesLost') : confirm("Attenzione! In questo modo tutte le modifiche apportate al documento andranno perse. Continuare?");  if (scelta) {  document.forms[0].reset();  }  }  } }
function add(tabName) {  document.forms[0].elements['<%=PSBD.TAB%>'].value = tabName;  document.forms[0].elements['<%=PSBD.ACTION_TYPE%>'].value = "<%=PSBD.ACTION_ADD%>";  if (tabName == "<%=PSBD.TAB_CONTENZIOSO%>") {  document.forms[0].elements['pagina'].value = "scheda1/addContenzioso.jsp";  }  if (tabName == "<%=PSBD.TAB_AFFIDATARIO%>") {  document.forms[0].elements['pagina'].value = "scheda1/addAffidatario.jsp";  }  document.forms[0].submit(); }
function changePage(servletdacaricare, idmodificato) {  var scelta = true;  if (document.forms[0].elements[idmodificato].value == 1) {  scelta = (typeof i18n !== 'undefined' && i18n.confirm) ? i18n.confirm('error.dataChanged') : confirm("Attenzione ! I dati potrebbero essere cambiati. Prosegui con il rischio di perdere i dati?");  }  if (scelta) {  document.forms[0].action = servletdacaricare;  document.forms[0].submit();  } }
function cancella(tabName, args) {  var confirmMsg = (typeof i18n !== 'undefined' && i18n.confirm) ? i18n.confirm('error.deleteRecord') : confirm("Si sta per cancellare il record. Proseguire?");  if (confirmMsg) {  document.forms[0].elements['<%=PSBD.ACTION_TYPE%>'].value = tabName;  for (var i = 0; i < args.length; i++) {  document.forms[0].elements[args[i]].value = args[++i];  }  document.forms[0].submit();  } }
function modificaTab(tabName, args) {  document.forms[0].elements['<%=PSBD.TAB%>'].value = tabName;  document.forms[0].elements['<%=PSBD.ACTION_TYPE%>'].value = "<%=PSBD.ACTION_MODIFICA%>";  for (var i = 0; i < args.length; i++) {  document.forms[0].elements[args[i]].value = args[++i];  }  document.forms[0].submit(); }
function modifica(tabName, args) {  if (document.forms[0].elements['Modificato0'].value == 1) {  if (typeof i18n !== 'undefined' && i18n.alert) { i18n.alert('error.saveRequired'); } else { alert("Sono state apportate delle modifiche ai dati. E' necessario effettuare prima un salvataggio."); }  } else {  document.forms[0].elements['<%=PSBD.TAB%>'].value = tabName;  document.forms[0].elements['<%=PSBD.ACTION_TYPE%>'].value = "<%=PSBD.ACTION_LOAD%>";  for (var i = 0; i < args.length; i++) {  document.forms[0].elements[args[i]].value = args[++i];  }  document.forms[0].submit();  } }
function changeFromAffidatario(tabName, idPartecipante, denPartecipante, dataInizioAggiudicatario) {  document.forms[0].elements['<%=PSBD.TAB%>'].value = tabName;  document.forms[0].elements['<%=PSBD.ACTION_TYPE%>'].value = "<%=PSBD.ACTION_LOAD%>";  document.forms[0].elements['<%=PSBD.FIELD_NAME_AGG_ID_SOGGETTO_PARTECIPANTE%>'].value = idPartecipante;  document.forms[0].elements['<%=ParametriServletRubrica.FIELD_NAME_DENOMINAZIONE%>'].value = denPartecipante;  document.forms[0].elements['<%=ParametriServletRubrica.FIELD_NAME_DATA_INIZIO_SOGGETTO%>'].value = dataInizioAggiudicatario;  document.forms[0].elements['pagina'].value = "scheda1/addAffidatario.jsp";  document.forms[0].submit(); }
function cerca(tabName) {  document.forms[0].elements['<%=PSBD.TAB%>'].value = tabName;  document.forms[0].elements['<%=PSBD.ACTION_TYPE%>'].value = "<%=PSBD.ACTION_CERCA%>";  document.forms[0].submit(); }
function trim(stringa) {  while (stringa.substring(0, 1) == ' ') {  stringa = stringa.substring(1, stringa.length);  }  while (stringa.substring(0, 1) == '\n') {  stringa = stringa.substring(1, stringa.length);  }  while (stringa.substring(stringa.length - 1, stringa.length) == ' ') {  stringa = stringa.substring(0, stringa.length - 1);  }  tmpStringa = "";  for (i = 0; i < stringa.length; i = i + 1) {  if (stringa.charAt(i) == ' ' || stringa.charAt() == '%') {} else tmpStringa = tmpStringa + stringa.charAt(i);  }  return tmpStringa; }
function cercaInRubrica(tabName) {  document.forms[0].elements['<%=PSBD.TAB%>'].value = tabName;  codiceFiscale = trim(document.getElementById("codiceFiscale").value);  cognome = trim(document.getElementById('<%= ParametriServletRubrica.FIELD_NAME_COGNOME%>').value);  if (document.getElementById('<%= ParametriServletRubrica.FIELD_NAME_NOME%>') != null)  nome = trim(document.getElementById('<%= ParametriServletRubrica.FIELD_NAME_NOME%>').value);  else  nome = "";  if ((codiceFiscale == "" || codiceFiscale == null) && (cognome == "" || cognome == null) && (nome == "" || nome == null)) {  if (typeof i18n !== 'undefined' && i18n.alert) { i18n.alert('error.insertFilter'); } else { alert("Inserire almeno uno dei filtri di ricerca"); }  return;  }  if (codiceFiscale == "" || codiceFiscale == null) {  if (! ((nome.length > 1) || (cognome.length > 1))) {  if (typeof i18n !== 'undefined' && i18n.alert) { i18n.alert('error.filterMinChars'); } else { alert("I filtri di ricerca per Nome e Cognome o Denominazione devono contenere almeno due caratteri"); }  return;  }  }  document.getElementById('cerca').disabled = true;  document.forms[0].action = 'rubrica?' + "<%=ParametriServletRubrica.OPERAZIONE%>=Cerca in rubrica";  var paramsString = "?" + "<%=ParametriServletRubrica.OPERAZIONE%>=" + "Cerca in rubrica";  document.forms[0].submit(); }
function cercaInRubricaDittaAusiliaria(tabName) {  document.forms[0].elements['<%=PSBD.TAB%>'].value = tabName;  codiceFiscale = trim(document.getElementById("codiceFiscale").value);  cognome = trim(document.getElementById('<%= ParametriServletRubrica.FIELD_NAME_COGNOME%>').value);  if (document.getElementById('<%= ParametriServletRubrica.FIELD_NAME_NOME%>') != null)  nome = trim(document.getElementById('<%= ParametriServletRubrica.FIELD_NAME_NOME%>').value);  else  nome = "";  if ((codiceFiscale == "" || codiceFiscale == null) && (cognome == "" || cognome == null) && (nome == "" || nome == null)) {  if (typeof i18n !== 'undefined' && i18n.alert) { i18n.alert('error.insertFilter'); } else { alert("Inserire almeno uno dei filtri di ricerca"); }  return;  }  if (codiceFiscale == "" || codiceFiscale == null) {  if (! ((nome.length > 1) || (cognome.length > 1))) {  if (typeof i18n !== 'undefined' && i18n.alert) { i18n.alert('error.filterMinChars'); } else { alert("I filtri di ricerca per Nome e Cognome o Denominazione devono contenere almeno due caratteri"); }  return;  }  }  document.getElementById('cerca').disabled = true;  document.forms[0].action = 'rubricaDittaAusiliaria?' + "<%=ParametriServletRubrica.OPERAZIONE%>=Cerca in rubrica";  var paramsString = "?" + "<%=ParametriServletRubrica.OPERAZIONE%>=" + "Cerca in rubrica";  document.forms[0].submit(); }
function loadAnnullamentJSP(tabName) {  var scelta = (typeof i18n !== 'undefined' && i18n.get) ? i18n.get('error.requestModification') : "Richiedere la modifica del blocco dati in esame?";  var codiceContratto = document.getElementById("CODICE_CONTRATTO");  if (codiceContratto != null && codiceContratto.value != "") {  scelta = (typeof i18n !== 'undefined' && i18n.get) ? i18n.get('error.multiLottoWarning') : "ATTENZIONE: L'Aggiudicazione fa parte di un contratto multi lotto. Procedendo oltre, la presente Aggiudicazione e tutte le altre Aggiudicazioni partecipanti al contratto saranno svincolate dallo stesso. Si desidera proseguire?";  }  var confirmMsg = (typeof i18n !== 'undefined' && i18n.confirm) ? i18n.confirm('error.requestModification') : confirm(scelta);  if (confirmMsg) {  document.forms[0].elements['<%=PSBD.TAB%>'].value = tabName;  if (document.forms[0].elements['toDo']) document.forms[0].elements['toDo'].value = "<%=PSBD.ACTION_CARICA_JSP_ANNULLAMENTO%>";  document.forms[0].elements['<%=PSBD.ACTION_TYPE%>'].value = "<%=PSBD.ACTION_CARICA_JSP_ANNULLAMENTO%>";  document.forms[0].submit();  } }
function richiediAnnullamento2(idMotivazioneEsito) {  var motivazione = document.forms[0].elements[idMotivazioneEsito].value;  if (trim(motivazione).length >= 10 && trim(motivazione).length <= 1000) {  return true;  } else {  if (typeof i18n !== 'undefined' && i18n.alert) { i18n.alert('error.motivationLength'); } else { alert('Inserire una motivazione di almeno 10 caratteri e minore di 1000'); }  return false;  } }
function loadPages(srv, param) {  document.forms[0].elements['<%= ParametriServlet.ACTION_GET_LIST %>'].value = param;  document.forms[0].elements['<%= ParametriServlet.SHOW_DATI_COMUNI %>'].value = "false";  changePage(srv); }
function urlCallFromCombo(combo) {  var pick = combo.options[combo.selectedIndex].value;  if (pick != "") window.location.replace(pick); }
function inputRadio() {  var radio1 = document.getElementById('radio1');  var radio2 = document.getElementById('radio2');  if (radio1.checked == false && radio2.checked == false) {  if (typeof i18n !== 'undefined' && i18n.alert) { i18n.alert('error.selectRequestType'); } else { alert("Scegliere un tipo di richiesta"); }  return false;  } else {  return true;  } }
//-->
</script>