<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	
	<parent>
	  <groupId>it.anticorruzione.simog</groupId>
	  <artifactId>SimogParent</artifactId>
  <version>3.04.16-i18n</version>
	</parent>
	
	<modelVersion>4.0.0</modelVersion>
	<groupId>it.anticorruzione.simog</groupId>
	<artifactId>SimogAVCPLogin</artifactId>

	<dependencies>
		<dependency>
			<groupId>it.anticorruzione.simog</groupId>
			<artifactId>SimogCommon</artifactId>
			<version>3.04.16</version>
		</dependency>
		<dependency>
			<groupId>it.anticorruzione.simog</groupId>
			<artifactId>XmlAuth</artifactId>
			<version>3.04.5</version>
		</dependency>
		<dependency>
			<groupId>opensaml</groupId>
			<artifactId>opensaml</artifactId>
			<version>2.0</version>
		</dependency>
		<dependency>
			<groupId>opensaml</groupId>
			<artifactId>xmltooling</artifactId>
			<version>1.1.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.axis</groupId>
			<artifactId>axis</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>axis</groupId>
			<artifactId>axis-jaxrpc</artifactId>
			<version>1.2.1</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.13</version>
		</dependency>
	</dependencies>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<testSourceDirectory>XmlLoginTest</testSourceDirectory>
		<resources>
			<resource>
				<directory>src</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</resource>
			<resource>
				<directory>XmlLoginTest</directory>
				<includes>
					<include>*</include>
				</includes>
			</resource>
		</resources>
		<testResources>
			<testResource>
				<directory>XmlLoginTest</directory>
				<excludes>
					<exclude>**/*.java</exclude>
				</excludes>
			</testResource>
		</testResources>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
		<repositories>
        <repository>
            <id>anac-central</id>
            <name>ANAC Maven Repository-releases</name>
            <url>http://mvnrepo.lab.anticorruzione.local/artifactory/ext-release-local</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>anac-central1</id>
            <name>ANAC Maven Repository-releases</name>
            <url>http://mvnrepo.lab.anticorruzione.local/artifactory/libs-release-local</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>anac-central2</id>
            <name>ANAC Maven Repository-releases</name>
            <url>http://mvnrepo.lab.anticorruzione.local/artifactory/libs-snapshot-local</url>
            <releases>
                <enabled>false</enabled>
            </releases>
        </repository>
    </repositories>
</project>