//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccordoBonarioType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccordoBonarioType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DATA_ACCORDO" use="required" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="ONERI_DERIVANTI" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="NUM_RISERVE" use="required" type="{xmlbeans.massload.simog.avlp.it}InteroType" />
 *       &lt;attribute name="ID_SCHEDA_LOCALE" type="{xmlbeans.massload.simog.avlp.it}IdSchedaType" />
 *       &lt;attribute name="ID_SCHEDA_SIMOG" type="{xmlbeans.massload.simog.avlp.it}IdSchedaType" />
 *       &lt;attribute name="ID_STATO_SCHEDA" type="{xmlbeans.massload.simog.avlp.it}StatoSchedaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccordoBonarioType")
public class AccordoBonarioType {

    @XmlAttribute(name = "DATA_ACCORDO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected DbDateType dataaccordo;
    @XmlAttribute(name = "ONERI_DERIVANTI", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType oneriderivanti;
    @XmlAttribute(name = "NUM_RISERVE", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected InteroType numriserve;
    @XmlAttribute(name = "ID_SCHEDA_LOCALE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected IdSchedaType idschedalocale;
    @XmlAttribute(name = "ID_SCHEDA_SIMOG", namespace = "xmlbeans.massload.simog.avlp.it")
    protected IdSchedaType idschedasimog;
    @XmlAttribute(name = "ID_STATO_SCHEDA", namespace = "xmlbeans.massload.simog.avlp.it")
    protected StatoSchedaType idstatoscheda;

    /**
     * Gets the value of the dataaccordo property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATAACCORDO() {
        return dataaccordo;
    }

    /**
     * Sets the value of the dataaccordo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATAACCORDO(DbDateType value) {
        this.dataaccordo = value;
    }

    /**
     * Gets the value of the oneriderivanti property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getONERIDERIVANTI() {
        return oneriderivanti;
    }

    /**
     * Sets the value of the oneriderivanti property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setONERIDERIVANTI(ImportoType value) {
        this.oneriderivanti = value;
    }

    /**
     * Gets the value of the numriserve property.
     * 
     * @return
     *     possible object is
     *     {@link InteroType }
     *     
     */
    public InteroType getNUMRISERVE() {
        return numriserve;
    }

    /**
     * Sets the value of the numriserve property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteroType }
     *     
     */
    public void setNUMRISERVE(InteroType value) {
        this.numriserve = value;
    }

    /**
     * Gets the value of the idschedalocale property.
     * 
     * @return
     *     possible object is
     *     {@link IdSchedaType }
     *     
     */
    public IdSchedaType getIDSCHEDALOCALE() {
        return idschedalocale;
    }

    /**
     * Sets the value of the idschedalocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdSchedaType }
     *     
     */
    public void setIDSCHEDALOCALE(IdSchedaType value) {
        this.idschedalocale = value;
    }

    /**
     * Gets the value of the idschedasimog property.
     * 
     * @return
     *     possible object is
     *     {@link IdSchedaType }
     *     
     */
    public IdSchedaType getIDSCHEDASIMOG() {
        return idschedasimog;
    }

    /**
     * Sets the value of the idschedasimog property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdSchedaType }
     *     
     */
    public void setIDSCHEDASIMOG(IdSchedaType value) {
        this.idschedasimog = value;
    }

    /**
     * Gets the value of the idstatoscheda property.
     * 
     * @return
     *     possible object is
     *     {@link StatoSchedaType }
     *     
     */
    public StatoSchedaType getIDSTATOSCHEDA() {
        return idstatoscheda;
    }

    /**
     * Sets the value of the idstatoscheda property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatoSchedaType }
     *     
     */
    public void setIDSTATOSCHEDA(StatoSchedaType value) {
        this.idstatoscheda = value;
    }

}
