//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AggiudicazioneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AggiudicazioneType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Appalto" type="{xmlbeans.massload.simog.avlp.it}AppaltoType"/>
 *         &lt;element name="TipiAppaltoLav" type="{xmlbeans.massload.simog.avlp.it}TipiAppaltoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TipiAppaltoForn" type="{xmlbeans.massload.simog.avlp.it}TipiAppaltoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Condizioni" type="{xmlbeans.massload.simog.avlp.it}CondizioneType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Requisiti" type="{xmlbeans.massload.simog.avlp.it}RequisitoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Finanziamenti" type="{xmlbeans.massload.simog.avlp.it}FinanziamentoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Aggiudicatari" type="{xmlbeans.massload.simog.avlp.it}SoggAggiudicatarioType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Incaricati" type="{xmlbeans.massload.simog.avlp.it}IncaricatoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DitteAusiliarie" type="{xmlbeans.massload.simog.avlp.it}DittaAusiliariaType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CUPLOTTO" type="{xmlbeans.massload.simog.avlp.it}CUPLOTTOType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AggiudicazioneType", propOrder = {
    "appalto",
    "tipiAppaltoLav",
    "tipiAppaltoForn",
    "condizioni",
    "requisiti",
    "finanziamenti",
    "aggiudicatari",
    "incaricati",
    "ditteAusiliarie",
    "cuplotto"
})
public class AggiudicazioneType {

    @XmlElement(name = "Appalto", required = true)
    protected AppaltoType appalto;
    @XmlElement(name = "TipiAppaltoLav")
    protected List<TipiAppaltoType> tipiAppaltoLav;
    @XmlElement(name = "TipiAppaltoForn")
    protected List<TipiAppaltoType> tipiAppaltoForn;
    @XmlElement(name = "Condizioni")
    protected List<CondizioneType> condizioni;
    @XmlElement(name = "Requisiti")
    protected List<RequisitoType> requisiti;
    @XmlElement(name = "Finanziamenti")
    protected List<FinanziamentoType> finanziamenti;
    @XmlElement(name = "Aggiudicatari")
    protected List<SoggAggiudicatarioType> aggiudicatari;
    @XmlElement(name = "Incaricati")
    protected List<IncaricatoType> incaricati;
    @XmlElement(name = "DitteAusiliarie")
    protected List<DittaAusiliariaType> ditteAusiliarie;
    @XmlElement(name = "CUPLOTTO")
    protected CUPLOTTOType cuplotto;

    /**
     * Gets the value of the appalto property.
     * 
     * @return
     *     possible object is
     *     {@link AppaltoType }
     *     
     */
    public AppaltoType getAppalto() {
        return appalto;
    }

    /**
     * Sets the value of the appalto property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppaltoType }
     *     
     */
    public void setAppalto(AppaltoType value) {
        this.appalto = value;
    }

    /**
     * Gets the value of the tipiAppaltoLav property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tipiAppaltoLav property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTipiAppaltoLav().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipiAppaltoType }
     * 
     * 
     */
    public List<TipiAppaltoType> getTipiAppaltoLav() {
        if (tipiAppaltoLav == null) {
            tipiAppaltoLav = new ArrayList<TipiAppaltoType>();
        }
        return this.tipiAppaltoLav;
    }

    /**
     * Gets the value of the tipiAppaltoForn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tipiAppaltoForn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTipiAppaltoForn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipiAppaltoType }
     * 
     * 
     */
    public List<TipiAppaltoType> getTipiAppaltoForn() {
        if (tipiAppaltoForn == null) {
            tipiAppaltoForn = new ArrayList<TipiAppaltoType>();
        }
        return this.tipiAppaltoForn;
    }

    /**
     * Gets the value of the condizioni property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the condizioni property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCondizioni().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CondizioneType }
     * 
     * 
     */
    public List<CondizioneType> getCondizioni() {
        if (condizioni == null) {
            condizioni = new ArrayList<CondizioneType>();
        }
        return this.condizioni;
    }

    /**
     * Gets the value of the requisiti property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requisiti property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequisiti().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequisitoType }
     * 
     * 
     */
    public List<RequisitoType> getRequisiti() {
        if (requisiti == null) {
            requisiti = new ArrayList<RequisitoType>();
        }
        return this.requisiti;
    }

    /**
     * Gets the value of the finanziamenti property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the finanziamenti property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFinanziamenti().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinanziamentoType }
     * 
     * 
     */
    public List<FinanziamentoType> getFinanziamenti() {
        if (finanziamenti == null) {
            finanziamenti = new ArrayList<FinanziamentoType>();
        }
        return this.finanziamenti;
    }

    /**
     * Gets the value of the aggiudicatari property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aggiudicatari property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAggiudicatari().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SoggAggiudicatarioType }
     * 
     * 
     */
    public List<SoggAggiudicatarioType> getAggiudicatari() {
        if (aggiudicatari == null) {
            aggiudicatari = new ArrayList<SoggAggiudicatarioType>();
        }
        return this.aggiudicatari;
    }

    /**
     * Gets the value of the incaricati property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incaricati property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncaricati().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncaricatoType }
     * 
     * 
     */
    public List<IncaricatoType> getIncaricati() {
        if (incaricati == null) {
            incaricati = new ArrayList<IncaricatoType>();
        }
        return this.incaricati;
    }

    /**
     * Gets the value of the ditteAusiliarie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ditteAusiliarie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDitteAusiliarie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DittaAusiliariaType }
     * 
     * 
     */
    public List<DittaAusiliariaType> getDitteAusiliarie() {
        if (ditteAusiliarie == null) {
            ditteAusiliarie = new ArrayList<DittaAusiliariaType>();
        }
        return this.ditteAusiliarie;
    }

    /**
     * Gets the value of the cuplotto property.
     * 
     * @return
     *     possible object is
     *     {@link CUPLOTTOType }
     *     
     */
    public CUPLOTTOType getCUPLOTTO() {
        return cuplotto;
    }

    /**
     * Sets the value of the cuplotto property.
     * 
     * @param value
     *     allowed object is
     *     {@link CUPLOTTOType }
     *     
     */
    public void setCUPLOTTO(CUPLOTTOType value) {
        this.cuplotto = value;
    }

}
