//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.03 at 10:48:06 PM CEST 
//


package it.avlp.simog.ws.massload.xmlbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AppaltoTypeAgg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppaltoTypeAgg">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AWARDED_NOTICE" type="{xmlbeans.massload.simog.avlp.it}ContraenteType" maxOccurs="100" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CIG_AGG" use="required" type="{xmlbeans.massload.simog.avlp.it}CigType" />
 *       &lt;attribute name="AWARDED_CONTRACT" use="required" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *       &lt;attribute name="PROCUREMENT_UNSUCCESSFUL" type="{xmlbeans.massload.simog.avlp.it}ProcurementUnsuccessfulType" />
 *       &lt;attribute name="NB_TENDERS_RECEIVED_SME">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NB_TENDERS_RECEIVED_OTHER_EU">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NB_TENDERS_RECEIVED_NON_EU">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NB_TENDERS_RECEIVED_EMEANS">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="LIKELY_SUBCONTRACTED" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *       &lt;attribute name="VAL_SUBCONTRACTING" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="PCT_SUBCONTRACTING">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="100"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="INFO_ADD_SUBCONTRACTING">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="6000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DATE_CONCLUSION_CONTRACT" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppaltoTypeAgg", propOrder = {
    "awardednotice"
})
public class AppaltoTypeAgg {

    @XmlElement(name = "AWARDED_NOTICE")
    protected List<ContraenteType> awardednotice;
    @XmlAttribute(name = "CIG_AGG", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected CigType cigagg;
    @XmlAttribute(name = "AWARDED_CONTRACT", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected FlagSNType awardedcontract;
    @XmlAttribute(name = "PROCUREMENT_UNSUCCESSFUL", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ProcurementUnsuccessfulType procurementunsuccessful;
    @XmlAttribute(name = "NB_TENDERS_RECEIVED_SME", namespace = "xmlbeans.massload.simog.avlp.it")
    protected Integer nbtendersreceivedsme;
    @XmlAttribute(name = "NB_TENDERS_RECEIVED_OTHER_EU", namespace = "xmlbeans.massload.simog.avlp.it")
    protected Integer nbtendersreceivedothereu;
    @XmlAttribute(name = "NB_TENDERS_RECEIVED_NON_EU", namespace = "xmlbeans.massload.simog.avlp.it")
    protected Integer nbtendersreceivednoneu;
    @XmlAttribute(name = "NB_TENDERS_RECEIVED_EMEANS", namespace = "xmlbeans.massload.simog.avlp.it")
    protected Integer nbtendersreceivedemeans;
    @XmlAttribute(name = "LIKELY_SUBCONTRACTED", namespace = "xmlbeans.massload.simog.avlp.it")
    protected FlagSNType likelysubcontracted;
    @XmlAttribute(name = "VAL_SUBCONTRACTING", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType valsubcontracting;
    @XmlAttribute(name = "PCT_SUBCONTRACTING", namespace = "xmlbeans.massload.simog.avlp.it")
    protected Integer pctsubcontracting;
    @XmlAttribute(name = "INFO_ADD_SUBCONTRACTING", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String infoaddsubcontracting;
    @XmlAttribute(name = "DATE_CONCLUSION_CONTRACT", namespace = "xmlbeans.massload.simog.avlp.it")
    protected DbDateType dateconclusioncontract;

    /**
     * Gets the value of the awardednotice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the awardednotice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAWARDEDNOTICE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContraenteType }
     * 
     * 
     */
    public List<ContraenteType> getAWARDEDNOTICE() {
        if (awardednotice == null) {
            awardednotice = new ArrayList<ContraenteType>();
        }
        return this.awardednotice;
    }

    /**
     * Gets the value of the cigagg property.
     * 
     * @return
     *     possible object is
     *     {@link CigType }
     *     
     */
    public CigType getCIGAGG() {
        return cigagg;
    }

    /**
     * Sets the value of the cigagg property.
     * 
     * @param value
     *     allowed object is
     *     {@link CigType }
     *     
     */
    public void setCIGAGG(CigType value) {
        this.cigagg = value;
    }

    /**
     * Gets the value of the awardedcontract property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getAWARDEDCONTRACT() {
        return awardedcontract;
    }

    /**
     * Sets the value of the awardedcontract property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setAWARDEDCONTRACT(FlagSNType value) {
        this.awardedcontract = value;
    }

    /**
     * Gets the value of the procurementunsuccessful property.
     * 
     * @return
     *     possible object is
     *     {@link ProcurementUnsuccessfulType }
     *     
     */
    public ProcurementUnsuccessfulType getPROCUREMENTUNSUCCESSFUL() {
        return procurementunsuccessful;
    }

    /**
     * Sets the value of the procurementunsuccessful property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcurementUnsuccessfulType }
     *     
     */
    public void setPROCUREMENTUNSUCCESSFUL(ProcurementUnsuccessfulType value) {
        this.procurementunsuccessful = value;
    }

    /**
     * Gets the value of the nbtendersreceivedsme property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNBTENDERSRECEIVEDSME() {
        return nbtendersreceivedsme;
    }

    /**
     * Sets the value of the nbtendersreceivedsme property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNBTENDERSRECEIVEDSME(Integer value) {
        this.nbtendersreceivedsme = value;
    }

    /**
     * Gets the value of the nbtendersreceivedothereu property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNBTENDERSRECEIVEDOTHEREU() {
        return nbtendersreceivedothereu;
    }

    /**
     * Sets the value of the nbtendersreceivedothereu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNBTENDERSRECEIVEDOTHEREU(Integer value) {
        this.nbtendersreceivedothereu = value;
    }

    /**
     * Gets the value of the nbtendersreceivednoneu property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNBTENDERSRECEIVEDNONEU() {
        return nbtendersreceivednoneu;
    }

    /**
     * Sets the value of the nbtendersreceivednoneu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNBTENDERSRECEIVEDNONEU(Integer value) {
        this.nbtendersreceivednoneu = value;
    }

    /**
     * Gets the value of the nbtendersreceivedemeans property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNBTENDERSRECEIVEDEMEANS() {
        return nbtendersreceivedemeans;
    }

    /**
     * Sets the value of the nbtendersreceivedemeans property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNBTENDERSRECEIVEDEMEANS(Integer value) {
        this.nbtendersreceivedemeans = value;
    }

    /**
     * Gets the value of the likelysubcontracted property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getLIKELYSUBCONTRACTED() {
        return likelysubcontracted;
    }

    /**
     * Sets the value of the likelysubcontracted property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setLIKELYSUBCONTRACTED(FlagSNType value) {
        this.likelysubcontracted = value;
    }

    /**
     * Gets the value of the valsubcontracting property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getVALSUBCONTRACTING() {
        return valsubcontracting;
    }

    /**
     * Sets the value of the valsubcontracting property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setVALSUBCONTRACTING(ImportoType value) {
        this.valsubcontracting = value;
    }

    /**
     * Gets the value of the pctsubcontracting property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPCTSUBCONTRACTING() {
        return pctsubcontracting;
    }

    /**
     * Sets the value of the pctsubcontracting property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPCTSUBCONTRACTING(Integer value) {
        this.pctsubcontracting = value;
    }

    /**
     * Gets the value of the infoaddsubcontracting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINFOADDSUBCONTRACTING() {
        return infoaddsubcontracting;
    }

    /**
     * Sets the value of the infoaddsubcontracting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINFOADDSUBCONTRACTING(String value) {
        this.infoaddsubcontracting = value;
    }

    /**
     * Gets the value of the dateconclusioncontract property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATECONCLUSIONCONTRACT() {
        return dateconclusioncontract;
    }

    /**
     * Sets the value of the dateconclusioncontract property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATECONCLUSIONCONTRACT(DbDateType value) {
        this.dateconclusioncontract = value;
    }

}
