//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AvanzamentoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AvanzamentoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="FLAG_PAGAMENTO" use="required" type="{xmlbeans.massload.simog.avlp.it}FlagPagamentoType" />
 *       &lt;attribute name="DATA_ANTICIPAZIONE" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="IMPORTO_ANTICIPAZIONE" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="DATA_RAGGIUNGIMENTO" use="required" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="IMPORTO_SAL" use="required" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="DATA_CERTIFICATO" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="IMPORTO_CERTIFICATO" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="FLAG_RITARDO" use="required" type="{xmlbeans.massload.simog.avlp.it}FlagRitardoType" />
 *       &lt;attribute name="NUM_GIORNI_SCOST" type="{xmlbeans.massload.simog.avlp.it}InteroType" />
 *       &lt;attribute name="NUM_GIORNI_PROROGA" type="{xmlbeans.massload.simog.avlp.it}InteroType" />
 *       &lt;attribute name="DENOM_AVANZAMENTO">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="250"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ID_SCHEDA_LOCALE" type="{xmlbeans.massload.simog.avlp.it}IdSchedaType" />
 *       &lt;attribute name="ID_SCHEDA_SIMOG" type="{xmlbeans.massload.simog.avlp.it}IdSchedaType" />
 *       &lt;attribute name="ID_STATO_SCHEDA" type="{xmlbeans.massload.simog.avlp.it}StatoSchedaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AvanzamentoType")
public class AvanzamentoType {

    @XmlAttribute(name = "FLAG_PAGAMENTO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected FlagPagamentoType flagpagamento;
    @XmlAttribute(name = "DATA_ANTICIPAZIONE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected DbDateType dataanticipazione;
    @XmlAttribute(name = "IMPORTO_ANTICIPAZIONE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType importoanticipazione;
    @XmlAttribute(name = "DATA_RAGGIUNGIMENTO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected DbDateType dataraggiungimento;
    @XmlAttribute(name = "IMPORTO_SAL", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected ImportoType importosal;
    @XmlAttribute(name = "DATA_CERTIFICATO", namespace = "xmlbeans.massload.simog.avlp.it")
    protected DbDateType datacertificato;
    @XmlAttribute(name = "IMPORTO_CERTIFICATO", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType importocertificato;
    @XmlAttribute(name = "FLAG_RITARDO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected FlagRitardoType flagritardo;
    @XmlAttribute(name = "NUM_GIORNI_SCOST", namespace = "xmlbeans.massload.simog.avlp.it")
    protected InteroType numgiorniscost;
    @XmlAttribute(name = "NUM_GIORNI_PROROGA", namespace = "xmlbeans.massload.simog.avlp.it")
    protected InteroType numgiorniproroga;
    @XmlAttribute(name = "DENOM_AVANZAMENTO", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String denomavanzamento;
    @XmlAttribute(name = "ID_SCHEDA_LOCALE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected IdSchedaType idschedalocale;
    @XmlAttribute(name = "ID_SCHEDA_SIMOG", namespace = "xmlbeans.massload.simog.avlp.it")
    protected IdSchedaType idschedasimog;
    @XmlAttribute(name = "ID_STATO_SCHEDA", namespace = "xmlbeans.massload.simog.avlp.it")
    protected StatoSchedaType idstatoscheda;

    /**
     * Gets the value of the flagpagamento property.
     * 
     * @return
     *     possible object is
     *     {@link FlagPagamentoType }
     *     
     */
    public FlagPagamentoType getFLAGPAGAMENTO() {
        return flagpagamento;
    }

    /**
     * Sets the value of the flagpagamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagPagamentoType }
     *     
     */
    public void setFLAGPAGAMENTO(FlagPagamentoType value) {
        this.flagpagamento = value;
    }

    /**
     * Gets the value of the dataanticipazione property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATAANTICIPAZIONE() {
        return dataanticipazione;
    }

    /**
     * Sets the value of the dataanticipazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATAANTICIPAZIONE(DbDateType value) {
        this.dataanticipazione = value;
    }

    /**
     * Gets the value of the importoanticipazione property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getIMPORTOANTICIPAZIONE() {
        return importoanticipazione;
    }

    /**
     * Sets the value of the importoanticipazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setIMPORTOANTICIPAZIONE(ImportoType value) {
        this.importoanticipazione = value;
    }

    /**
     * Gets the value of the dataraggiungimento property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATARAGGIUNGIMENTO() {
        return dataraggiungimento;
    }

    /**
     * Sets the value of the dataraggiungimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATARAGGIUNGIMENTO(DbDateType value) {
        this.dataraggiungimento = value;
    }

    /**
     * Gets the value of the importosal property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getIMPORTOSAL() {
        return importosal;
    }

    /**
     * Sets the value of the importosal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setIMPORTOSAL(ImportoType value) {
        this.importosal = value;
    }

    /**
     * Gets the value of the datacertificato property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATACERTIFICATO() {
        return datacertificato;
    }

    /**
     * Sets the value of the datacertificato property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATACERTIFICATO(DbDateType value) {
        this.datacertificato = value;
    }

    /**
     * Gets the value of the importocertificato property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getIMPORTOCERTIFICATO() {
        return importocertificato;
    }

    /**
     * Sets the value of the importocertificato property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setIMPORTOCERTIFICATO(ImportoType value) {
        this.importocertificato = value;
    }

    /**
     * Gets the value of the flagritardo property.
     * 
     * @return
     *     possible object is
     *     {@link FlagRitardoType }
     *     
     */
    public FlagRitardoType getFLAGRITARDO() {
        return flagritardo;
    }

    /**
     * Sets the value of the flagritardo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagRitardoType }
     *     
     */
    public void setFLAGRITARDO(FlagRitardoType value) {
        this.flagritardo = value;
    }

    /**
     * Gets the value of the numgiorniscost property.
     * 
     * @return
     *     possible object is
     *     {@link InteroType }
     *     
     */
    public InteroType getNUMGIORNISCOST() {
        return numgiorniscost;
    }

    /**
     * Sets the value of the numgiorniscost property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteroType }
     *     
     */
    public void setNUMGIORNISCOST(InteroType value) {
        this.numgiorniscost = value;
    }

    /**
     * Gets the value of the numgiorniproroga property.
     * 
     * @return
     *     possible object is
     *     {@link InteroType }
     *     
     */
    public InteroType getNUMGIORNIPROROGA() {
        return numgiorniproroga;
    }

    /**
     * Sets the value of the numgiorniproroga property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteroType }
     *     
     */
    public void setNUMGIORNIPROROGA(InteroType value) {
        this.numgiorniproroga = value;
    }

    /**
     * Gets the value of the denomavanzamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDENOMAVANZAMENTO() {
        return denomavanzamento;
    }

    /**
     * Sets the value of the denomavanzamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDENOMAVANZAMENTO(String value) {
        this.denomavanzamento = value;
    }

    /**
     * Gets the value of the idschedalocale property.
     * 
     * @return
     *     possible object is
     *     {@link IdSchedaType }
     *     
     */
    public IdSchedaType getIDSCHEDALOCALE() {
        return idschedalocale;
    }

    /**
     * Sets the value of the idschedalocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdSchedaType }
     *     
     */
    public void setIDSCHEDALOCALE(IdSchedaType value) {
        this.idschedalocale = value;
    }

    /**
     * Gets the value of the idschedasimog property.
     * 
     * @return
     *     possible object is
     *     {@link IdSchedaType }
     *     
     */
    public IdSchedaType getIDSCHEDASIMOG() {
        return idschedasimog;
    }

    /**
     * Sets the value of the idschedasimog property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdSchedaType }
     *     
     */
    public void setIDSCHEDASIMOG(IdSchedaType value) {
        this.idschedasimog = value;
    }

    /**
     * Gets the value of the idstatoscheda property.
     * 
     * @return
     *     possible object is
     *     {@link StatoSchedaType }
     *     
     */
    public StatoSchedaType getIDSTATOSCHEDA() {
        return idstatoscheda;
    }

    /**
     * Sets the value of the idstatoscheda property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatoSchedaType }
     *     
     */
    public void setIDSTATOSCHEDA(StatoSchedaType value) {
        this.idstatoscheda = value;
    }

}
