//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CollaudoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CollaudoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DATA_REGOLARE_ESEC" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="DATA_COLLAUDO_STAT" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="MODO_COLLAUDO" type="{xmlbeans.massload.simog.avlp.it}FlagModoCollaudoType" />
 *       &lt;attribute name="DATA_NOMINA_COLL" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="DATA_INIZIO_OPER" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="DATA_CERT_COLLAUDO" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="DATA_DELIBERA" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="ESITO_COLLAUDO" use="required" type="{xmlbeans.massload.simog.avlp.it}FlagEsitoCollaudoType" />
 *       &lt;attribute name="IMP_FINALE_LAVORI" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="IMP_FINALE_SERVIZI" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="IMP_FINALE_FORNIT" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="IMP_FINALE_SECUR" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="IMP_PROGETTAZIONE" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="IMP_DISPOSIZIONE" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="AMM_NUM_DEFINITE" type="{xmlbeans.massload.simog.avlp.it}InteroType" />
 *       &lt;attribute name="AMM_NUM_DADEF" type="{xmlbeans.massload.simog.avlp.it}InteroType" />
 *       &lt;attribute name="AMM_IMPORTO_RICH" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="AMM_IMPORTO_DEF" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="ARB_NUM_DEFINITE" type="{xmlbeans.massload.simog.avlp.it}InteroType" />
 *       &lt;attribute name="ARB_NUM_DADEF" type="{xmlbeans.massload.simog.avlp.it}InteroType" />
 *       &lt;attribute name="ARB_IMPORTO_RICH" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="ARB_IMPORTO_DEF" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="GIU_NUM_DEFINITE" type="{xmlbeans.massload.simog.avlp.it}InteroType" />
 *       &lt;attribute name="GIU_NUM_DADEF" type="{xmlbeans.massload.simog.avlp.it}InteroType" />
 *       &lt;attribute name="GIU_IMPORTO_RICH" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="GIU_IMPORTO_DEF" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="TRA_NUM_DEFINITE" type="{xmlbeans.massload.simog.avlp.it}InteroType" />
 *       &lt;attribute name="TRA_NUM_DADEF" type="{xmlbeans.massload.simog.avlp.it}InteroType" />
 *       &lt;attribute name="TRA_IMPORTO_RICH" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="TRA_IMPORTO_DEF" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *       &lt;attribute name="LAVORI_ESTESI" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *       &lt;attribute name="ID_SCHEDA_LOCALE" type="{xmlbeans.massload.simog.avlp.it}IdSchedaType" />
 *       &lt;attribute name="ID_SCHEDA_SIMOG" type="{xmlbeans.massload.simog.avlp.it}IdSchedaType" />
 *       &lt;attribute name="ID_STATO_SCHEDA" type="{xmlbeans.massload.simog.avlp.it}StatoSchedaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CollaudoType")
public class CollaudoType {

    @XmlAttribute(name = "DATA_REGOLARE_ESEC", namespace = "xmlbeans.massload.simog.avlp.it")
    protected DbDateType dataregolareesec;
    @XmlAttribute(name = "DATA_COLLAUDO_STAT", namespace = "xmlbeans.massload.simog.avlp.it")
    protected DbDateType datacollaudostat;
    @XmlAttribute(name = "MODO_COLLAUDO", namespace = "xmlbeans.massload.simog.avlp.it")
    protected FlagModoCollaudoType modocollaudo;
    @XmlAttribute(name = "DATA_NOMINA_COLL", namespace = "xmlbeans.massload.simog.avlp.it")
    protected DbDateType datanominacoll;
    @XmlAttribute(name = "DATA_INIZIO_OPER", namespace = "xmlbeans.massload.simog.avlp.it")
    protected DbDateType datainiziooper;
    @XmlAttribute(name = "DATA_CERT_COLLAUDO", namespace = "xmlbeans.massload.simog.avlp.it")
    protected DbDateType datacertcollaudo;
    @XmlAttribute(name = "DATA_DELIBERA", namespace = "xmlbeans.massload.simog.avlp.it")
    protected DbDateType datadelibera;
    @XmlAttribute(name = "ESITO_COLLAUDO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected FlagEsitoCollaudoType esitocollaudo;
    @XmlAttribute(name = "IMP_FINALE_LAVORI", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType impfinalelavori;
    @XmlAttribute(name = "IMP_FINALE_SERVIZI", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType impfinaleservizi;
    @XmlAttribute(name = "IMP_FINALE_FORNIT", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType impfinalefornit;
    @XmlAttribute(name = "IMP_FINALE_SECUR", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType impfinalesecur;
    @XmlAttribute(name = "IMP_PROGETTAZIONE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType impprogettazione;
    @XmlAttribute(name = "IMP_DISPOSIZIONE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType impdisposizione;
    @XmlAttribute(name = "AMM_NUM_DEFINITE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected InteroType ammnumdefinite;
    @XmlAttribute(name = "AMM_NUM_DADEF", namespace = "xmlbeans.massload.simog.avlp.it")
    protected InteroType ammnumdadef;
    @XmlAttribute(name = "AMM_IMPORTO_RICH", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType ammimportorich;
    @XmlAttribute(name = "AMM_IMPORTO_DEF", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType ammimportodef;
    @XmlAttribute(name = "ARB_NUM_DEFINITE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected InteroType arbnumdefinite;
    @XmlAttribute(name = "ARB_NUM_DADEF", namespace = "xmlbeans.massload.simog.avlp.it")
    protected InteroType arbnumdadef;
    @XmlAttribute(name = "ARB_IMPORTO_RICH", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType arbimportorich;
    @XmlAttribute(name = "ARB_IMPORTO_DEF", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType arbimportodef;
    @XmlAttribute(name = "GIU_NUM_DEFINITE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected InteroType giunumdefinite;
    @XmlAttribute(name = "GIU_NUM_DADEF", namespace = "xmlbeans.massload.simog.avlp.it")
    protected InteroType giunumdadef;
    @XmlAttribute(name = "GIU_IMPORTO_RICH", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType giuimportorich;
    @XmlAttribute(name = "GIU_IMPORTO_DEF", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType giuimportodef;
    @XmlAttribute(name = "TRA_NUM_DEFINITE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected InteroType tranumdefinite;
    @XmlAttribute(name = "TRA_NUM_DADEF", namespace = "xmlbeans.massload.simog.avlp.it")
    protected InteroType tranumdadef;
    @XmlAttribute(name = "TRA_IMPORTO_RICH", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType traimportorich;
    @XmlAttribute(name = "TRA_IMPORTO_DEF", namespace = "xmlbeans.massload.simog.avlp.it")
    protected ImportoType traimportodef;
    @XmlAttribute(name = "LAVORI_ESTESI", namespace = "xmlbeans.massload.simog.avlp.it")
    protected FlagSNType lavoriestesi;
    @XmlAttribute(name = "ID_SCHEDA_LOCALE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected IdSchedaType idschedalocale;
    @XmlAttribute(name = "ID_SCHEDA_SIMOG", namespace = "xmlbeans.massload.simog.avlp.it")
    protected IdSchedaType idschedasimog;
    @XmlAttribute(name = "ID_STATO_SCHEDA", namespace = "xmlbeans.massload.simog.avlp.it")
    protected StatoSchedaType idstatoscheda;

    /**
     * Gets the value of the dataregolareesec property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATAREGOLAREESEC() {
        return dataregolareesec;
    }

    /**
     * Sets the value of the dataregolareesec property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATAREGOLAREESEC(DbDateType value) {
        this.dataregolareesec = value;
    }

    /**
     * Gets the value of the datacollaudostat property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATACOLLAUDOSTAT() {
        return datacollaudostat;
    }

    /**
     * Sets the value of the datacollaudostat property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATACOLLAUDOSTAT(DbDateType value) {
        this.datacollaudostat = value;
    }

    /**
     * Gets the value of the modocollaudo property.
     * 
     * @return
     *     possible object is
     *     {@link FlagModoCollaudoType }
     *     
     */
    public FlagModoCollaudoType getMODOCOLLAUDO() {
        return modocollaudo;
    }

    /**
     * Sets the value of the modocollaudo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagModoCollaudoType }
     *     
     */
    public void setMODOCOLLAUDO(FlagModoCollaudoType value) {
        this.modocollaudo = value;
    }

    /**
     * Gets the value of the datanominacoll property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATANOMINACOLL() {
        return datanominacoll;
    }

    /**
     * Sets the value of the datanominacoll property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATANOMINACOLL(DbDateType value) {
        this.datanominacoll = value;
    }

    /**
     * Gets the value of the datainiziooper property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATAINIZIOOPER() {
        return datainiziooper;
    }

    /**
     * Sets the value of the datainiziooper property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATAINIZIOOPER(DbDateType value) {
        this.datainiziooper = value;
    }

    /**
     * Gets the value of the datacertcollaudo property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATACERTCOLLAUDO() {
        return datacertcollaudo;
    }

    /**
     * Sets the value of the datacertcollaudo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATACERTCOLLAUDO(DbDateType value) {
        this.datacertcollaudo = value;
    }

    /**
     * Gets the value of the datadelibera property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATADELIBERA() {
        return datadelibera;
    }

    /**
     * Sets the value of the datadelibera property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATADELIBERA(DbDateType value) {
        this.datadelibera = value;
    }

    /**
     * Gets the value of the esitocollaudo property.
     * 
     * @return
     *     possible object is
     *     {@link FlagEsitoCollaudoType }
     *     
     */
    public FlagEsitoCollaudoType getESITOCOLLAUDO() {
        return esitocollaudo;
    }

    /**
     * Sets the value of the esitocollaudo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagEsitoCollaudoType }
     *     
     */
    public void setESITOCOLLAUDO(FlagEsitoCollaudoType value) {
        this.esitocollaudo = value;
    }

    /**
     * Gets the value of the impfinalelavori property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getIMPFINALELAVORI() {
        return impfinalelavori;
    }

    /**
     * Sets the value of the impfinalelavori property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setIMPFINALELAVORI(ImportoType value) {
        this.impfinalelavori = value;
    }

    /**
     * Gets the value of the impfinaleservizi property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getIMPFINALESERVIZI() {
        return impfinaleservizi;
    }

    /**
     * Sets the value of the impfinaleservizi property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setIMPFINALESERVIZI(ImportoType value) {
        this.impfinaleservizi = value;
    }

    /**
     * Gets the value of the impfinalefornit property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getIMPFINALEFORNIT() {
        return impfinalefornit;
    }

    /**
     * Sets the value of the impfinalefornit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setIMPFINALEFORNIT(ImportoType value) {
        this.impfinalefornit = value;
    }

    /**
     * Gets the value of the impfinalesecur property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getIMPFINALESECUR() {
        return impfinalesecur;
    }

    /**
     * Sets the value of the impfinalesecur property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setIMPFINALESECUR(ImportoType value) {
        this.impfinalesecur = value;
    }

    /**
     * Gets the value of the impprogettazione property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getIMPPROGETTAZIONE() {
        return impprogettazione;
    }

    /**
     * Sets the value of the impprogettazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setIMPPROGETTAZIONE(ImportoType value) {
        this.impprogettazione = value;
    }

    /**
     * Gets the value of the impdisposizione property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getIMPDISPOSIZIONE() {
        return impdisposizione;
    }

    /**
     * Sets the value of the impdisposizione property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setIMPDISPOSIZIONE(ImportoType value) {
        this.impdisposizione = value;
    }

    /**
     * Gets the value of the ammnumdefinite property.
     * 
     * @return
     *     possible object is
     *     {@link InteroType }
     *     
     */
    public InteroType getAMMNUMDEFINITE() {
        return ammnumdefinite;
    }

    /**
     * Sets the value of the ammnumdefinite property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteroType }
     *     
     */
    public void setAMMNUMDEFINITE(InteroType value) {
        this.ammnumdefinite = value;
    }

    /**
     * Gets the value of the ammnumdadef property.
     * 
     * @return
     *     possible object is
     *     {@link InteroType }
     *     
     */
    public InteroType getAMMNUMDADEF() {
        return ammnumdadef;
    }

    /**
     * Sets the value of the ammnumdadef property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteroType }
     *     
     */
    public void setAMMNUMDADEF(InteroType value) {
        this.ammnumdadef = value;
    }

    /**
     * Gets the value of the ammimportorich property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getAMMIMPORTORICH() {
        return ammimportorich;
    }

    /**
     * Sets the value of the ammimportorich property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setAMMIMPORTORICH(ImportoType value) {
        this.ammimportorich = value;
    }

    /**
     * Gets the value of the ammimportodef property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getAMMIMPORTODEF() {
        return ammimportodef;
    }

    /**
     * Sets the value of the ammimportodef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setAMMIMPORTODEF(ImportoType value) {
        this.ammimportodef = value;
    }

    /**
     * Gets the value of the arbnumdefinite property.
     * 
     * @return
     *     possible object is
     *     {@link InteroType }
     *     
     */
    public InteroType getARBNUMDEFINITE() {
        return arbnumdefinite;
    }

    /**
     * Sets the value of the arbnumdefinite property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteroType }
     *     
     */
    public void setARBNUMDEFINITE(InteroType value) {
        this.arbnumdefinite = value;
    }

    /**
     * Gets the value of the arbnumdadef property.
     * 
     * @return
     *     possible object is
     *     {@link InteroType }
     *     
     */
    public InteroType getARBNUMDADEF() {
        return arbnumdadef;
    }

    /**
     * Sets the value of the arbnumdadef property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteroType }
     *     
     */
    public void setARBNUMDADEF(InteroType value) {
        this.arbnumdadef = value;
    }

    /**
     * Gets the value of the arbimportorich property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getARBIMPORTORICH() {
        return arbimportorich;
    }

    /**
     * Sets the value of the arbimportorich property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setARBIMPORTORICH(ImportoType value) {
        this.arbimportorich = value;
    }

    /**
     * Gets the value of the arbimportodef property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getARBIMPORTODEF() {
        return arbimportodef;
    }

    /**
     * Sets the value of the arbimportodef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setARBIMPORTODEF(ImportoType value) {
        this.arbimportodef = value;
    }

    /**
     * Gets the value of the giunumdefinite property.
     * 
     * @return
     *     possible object is
     *     {@link InteroType }
     *     
     */
    public InteroType getGIUNUMDEFINITE() {
        return giunumdefinite;
    }

    /**
     * Sets the value of the giunumdefinite property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteroType }
     *     
     */
    public void setGIUNUMDEFINITE(InteroType value) {
        this.giunumdefinite = value;
    }

    /**
     * Gets the value of the giunumdadef property.
     * 
     * @return
     *     possible object is
     *     {@link InteroType }
     *     
     */
    public InteroType getGIUNUMDADEF() {
        return giunumdadef;
    }

    /**
     * Sets the value of the giunumdadef property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteroType }
     *     
     */
    public void setGIUNUMDADEF(InteroType value) {
        this.giunumdadef = value;
    }

    /**
     * Gets the value of the giuimportorich property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getGIUIMPORTORICH() {
        return giuimportorich;
    }

    /**
     * Sets the value of the giuimportorich property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setGIUIMPORTORICH(ImportoType value) {
        this.giuimportorich = value;
    }

    /**
     * Gets the value of the giuimportodef property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getGIUIMPORTODEF() {
        return giuimportodef;
    }

    /**
     * Sets the value of the giuimportodef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setGIUIMPORTODEF(ImportoType value) {
        this.giuimportodef = value;
    }

    /**
     * Gets the value of the tranumdefinite property.
     * 
     * @return
     *     possible object is
     *     {@link InteroType }
     *     
     */
    public InteroType getTRANUMDEFINITE() {
        return tranumdefinite;
    }

    /**
     * Sets the value of the tranumdefinite property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteroType }
     *     
     */
    public void setTRANUMDEFINITE(InteroType value) {
        this.tranumdefinite = value;
    }

    /**
     * Gets the value of the tranumdadef property.
     * 
     * @return
     *     possible object is
     *     {@link InteroType }
     *     
     */
    public InteroType getTRANUMDADEF() {
        return tranumdadef;
    }

    /**
     * Sets the value of the tranumdadef property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteroType }
     *     
     */
    public void setTRANUMDADEF(InteroType value) {
        this.tranumdadef = value;
    }

    /**
     * Gets the value of the traimportorich property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getTRAIMPORTORICH() {
        return traimportorich;
    }

    /**
     * Sets the value of the traimportorich property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setTRAIMPORTORICH(ImportoType value) {
        this.traimportorich = value;
    }

    /**
     * Gets the value of the traimportodef property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getTRAIMPORTODEF() {
        return traimportodef;
    }

    /**
     * Sets the value of the traimportodef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setTRAIMPORTODEF(ImportoType value) {
        this.traimportodef = value;
    }

    /**
     * Gets the value of the lavoriestesi property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getLAVORIESTESI() {
        return lavoriestesi;
    }

    /**
     * Sets the value of the lavoriestesi property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setLAVORIESTESI(FlagSNType value) {
        this.lavoriestesi = value;
    }

    /**
     * Gets the value of the idschedalocale property.
     * 
     * @return
     *     possible object is
     *     {@link IdSchedaType }
     *     
     */
    public IdSchedaType getIDSCHEDALOCALE() {
        return idschedalocale;
    }

    /**
     * Sets the value of the idschedalocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdSchedaType }
     *     
     */
    public void setIDSCHEDALOCALE(IdSchedaType value) {
        this.idschedalocale = value;
    }

    /**
     * Gets the value of the idschedasimog property.
     * 
     * @return
     *     possible object is
     *     {@link IdSchedaType }
     *     
     */
    public IdSchedaType getIDSCHEDASIMOG() {
        return idschedasimog;
    }

    /**
     * Sets the value of the idschedasimog property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdSchedaType }
     *     
     */
    public void setIDSCHEDASIMOG(IdSchedaType value) {
        this.idschedasimog = value;
    }

    /**
     * Gets the value of the idstatoscheda property.
     * 
     * @return
     *     possible object is
     *     {@link StatoSchedaType }
     *     
     */
    public StatoSchedaType getIDSTATOSCHEDA() {
        return idstatoscheda;
    }

    /**
     * Sets the value of the idstatoscheda property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatoSchedaType }
     *     
     */
    public void setIDSTATOSCHEDA(StatoSchedaType value) {
        this.idstatoscheda = value;
    }

}
