//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:33:20 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CondizioneLtType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CondizioneLtType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ID_CONDIZIONE" use="required" type="{xmlbeans.massload.simog.avlp.it}CondizioneLottoType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CondizioneLtType")
public class CondizioneLtType {

    @XmlAttribute(name = "ID_CONDIZIONE", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected CondizioneLottoType idcondizione;

    /**
     * Gets the value of the idcondizione property.
     * 
     * @return
     *     possible object is
     *     {@link CondizioneLottoType }
     *     
     */
    public CondizioneLottoType getIDCONDIZIONE() {
        return idcondizione;
    }

    /**
     * Sets the value of the idcondizione property.
     * 
     * @param value
     *     allowed object is
     *     {@link CondizioneLottoType }
     *     
     */
    public void setIDCONDIZIONE(CondizioneLottoType value) {
        this.idcondizione = value;
    }

}
