//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CUPLOTTOType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CUPLOTTOType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CODICICUP" type="{xmlbeans.massload.simog.avlp.it}DatiCUPType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CIG" type="{xmlbeans.massload.simog.avlp.it}CigType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CUPLOTTOType", propOrder = {
    "codicicup"
})
public class CUPLOTTOType {

    @XmlElement(name = "CODICICUP", required = true)
    protected List<DatiCUPType> codicicup;
    @XmlAttribute(name = "CIG", namespace = "xmlbeans.massload.simog.avlp.it")
    protected CigType cig;

    /**
     * Gets the value of the codicicup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codicicup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCODICICUP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatiCUPType }
     * 
     * 
     */
    public List<DatiCUPType> getCODICICUP() {
        if (codicicup == null) {
            codicicup = new ArrayList<DatiCUPType>();
        }
        return this.codicicup;
    }

    /**
     * Gets the value of the cig property.
     * 
     * @return
     *     possible object is
     *     {@link CigType }
     *     
     */
    public CigType getCIG() {
        return cig;
    }

    /**
     * Sets the value of the cig property.
     * 
     * @param value
     *     allowed object is
     *     {@link CigType }
     *     
     */
    public void setCIG(CigType value) {
        this.cig = value;
    }

}
