//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatiAggiudicazioneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatiAggiudicazioneType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatiComuni" type="{xmlbeans.massload.simog.avlp.it}DatiComuniType"/>
 *         &lt;element name="Pubblicazione" type="{xmlbeans.massload.simog.avlp.it}PubblicazioneType" minOccurs="0"/>
 *         &lt;element name="SchedaCompleta" type="{xmlbeans.massload.simog.avlp.it}SchedaCompletaType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiAggiudicazioneType", propOrder = {
    "datiComuni",
    "pubblicazione",
    "schedaCompleta"
})
public class DatiAggiudicazioneType {

    @XmlElement(name = "DatiComuni", required = true)
    protected DatiComuniType datiComuni;
    @XmlElement(name = "Pubblicazione")
    protected PubblicazioneType pubblicazione;
    @XmlElement(name = "SchedaCompleta")
    protected List<SchedaCompletaType> schedaCompleta;

    /**
     * Gets the value of the datiComuni property.
     * 
     * @return
     *     possible object is
     *     {@link DatiComuniType }
     *     
     */
    public DatiComuniType getDatiComuni() {
        return datiComuni;
    }

    /**
     * Sets the value of the datiComuni property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiComuniType }
     *     
     */
    public void setDatiComuni(DatiComuniType value) {
        this.datiComuni = value;
    }

    /**
     * Gets the value of the pubblicazione property.
     * 
     * @return
     *     possible object is
     *     {@link PubblicazioneType }
     *     
     */
    public PubblicazioneType getPubblicazione() {
        return pubblicazione;
    }

    /**
     * Sets the value of the pubblicazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link PubblicazioneType }
     *     
     */
    public void setPubblicazione(PubblicazioneType value) {
        this.pubblicazione = value;
    }

    /**
     * Gets the value of the schedaCompleta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the schedaCompleta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSchedaCompleta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchedaCompletaType }
     * 
     * 
     */
    public List<SchedaCompletaType> getSchedaCompleta() {
        if (schedaCompleta == null) {
            schedaCompleta = new ArrayList<SchedaCompletaType>();
        }
        return this.schedaCompleta;
    }

}
