//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.22 at 05:23:58 PM CEST 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id_soggetto_titolare" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="concentratore" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="soggetto_titolare" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id_uo_soggetto_titolare" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="uo_soggetto_titolare" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="user_titolare" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id_soggetto_richiedente" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="soggetto_richiedente" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DATI_TITOLARE_RICHIEDENTE")
public class DATITITOLARERICHIEDENTE {

    @XmlAttribute(name = "id_soggetto_titolare")
    protected String idSoggettoTitolare;
    @XmlAttribute
    protected String concentratore;
    @XmlAttribute(name = "soggetto_titolare")
    protected String soggettoTitolare;
    @XmlAttribute(name = "id_uo_soggetto_titolare")
    protected String idUoSoggettoTitolare;
    @XmlAttribute(name = "uo_soggetto_titolare")
    protected String uoSoggettoTitolare;
    @XmlAttribute(name = "user_titolare")
    protected String userTitolare;
    @XmlAttribute(name = "id_soggetto_richiedente", required = true)
    protected String idSoggettoRichiedente;
    @XmlAttribute(name = "soggetto_richiedente", required = true)
    protected String soggettoRichiedente;

    /**
     * Gets the value of the idSoggettoTitolare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSoggettoTitolare() {
        return idSoggettoTitolare;
    }

    /**
     * Sets the value of the idSoggettoTitolare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSoggettoTitolare(String value) {
        this.idSoggettoTitolare = value;
    }

    /**
     * Gets the value of the concentratore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConcentratore() {
        return concentratore;
    }

    /**
     * Sets the value of the concentratore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConcentratore(String value) {
        this.concentratore = value;
    }

    /**
     * Gets the value of the soggettoTitolare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoggettoTitolare() {
        return soggettoTitolare;
    }

    /**
     * Sets the value of the soggettoTitolare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoggettoTitolare(String value) {
        this.soggettoTitolare = value;
    }

    /**
     * Gets the value of the idUoSoggettoTitolare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdUoSoggettoTitolare() {
        return idUoSoggettoTitolare;
    }

    /**
     * Sets the value of the idUoSoggettoTitolare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdUoSoggettoTitolare(String value) {
        this.idUoSoggettoTitolare = value;
    }

    /**
     * Gets the value of the uoSoggettoTitolare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUoSoggettoTitolare() {
        return uoSoggettoTitolare;
    }

    /**
     * Sets the value of the uoSoggettoTitolare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUoSoggettoTitolare(String value) {
        this.uoSoggettoTitolare = value;
    }

    /**
     * Gets the value of the userTitolare property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserTitolare() {
        return userTitolare;
    }

    /**
     * Sets the value of the userTitolare property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserTitolare(String value) {
        this.userTitolare = value;
    }

    /**
     * Gets the value of the idSoggettoRichiedente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSoggettoRichiedente() {
        return idSoggettoRichiedente;
    }

    /**
     * Sets the value of the idSoggettoRichiedente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSoggettoRichiedente(String value) {
        this.idSoggettoRichiedente = value;
    }

    /**
     * Gets the value of the soggettoRichiedente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoggettoRichiedente() {
        return soggettoRichiedente;
    }

    /**
     * Sets the value of the soggettoRichiedente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoggettoRichiedente(String value) {
        this.soggettoRichiedente = value;
    }

}
