//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.08 at 01:35:23 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="codice_progetto" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="codice_cup" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="codice_cup_provvisorio" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="anno_decisione" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cumulativo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="codifica_locale" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id_natura" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="natura" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id_tipologia" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tipologia" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id_settore" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="settore" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id_sottosettore" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sottosettore" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id_categoria" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="categoria" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cpv1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cpv2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cpv3" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cpv4" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cpv5" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cpv6" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cpv7" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="stato" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="provvisorio" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pubblico" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tipo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="data_generazione" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="utente_generatore_provvisorio" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="utente_generatore_completo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="utente_riferimento" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="data_generazione_completo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="data_generazione_provvisorio" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="utente_ultima_modifica" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="data_ultima_modifica" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="utente_ultima_modifica_utente" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="data_ultima_modifica_utente" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="data_ultima_modifica_ssc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fase" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cup_in_relazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ruolo_cup_in_relazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tipo_relazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="note_relazione" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="data_chiusura_prevista" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cod_template" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tematica" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DATI_GENERALI_PROGETTO")
public class DATIGENERALIPROGETTO {

    @XmlAttribute(name = "codice_progetto", required = true)
    protected String codiceProgetto;
    @XmlAttribute(name = "codice_cup", required = true)
    protected String codiceCup;
    @XmlAttribute(name = "codice_cup_provvisorio")
    protected String codiceCupProvvisorio;
    @XmlAttribute(name = "anno_decisione", required = true)
    protected String annoDecisione;
    @XmlAttribute
    protected String cumulativo;
    @XmlAttribute(name = "codifica_locale")
    protected String codificaLocale;
    @XmlAttribute(name = "id_natura", required = true)
    protected String idNatura;
    @XmlAttribute(required = true)
    protected String natura;
    @XmlAttribute(name = "id_tipologia", required = true)
    protected String idTipologia;
    @XmlAttribute(required = true)
    protected String tipologia;
    @XmlAttribute(name = "id_settore", required = true)
    protected String idSettore;
    @XmlAttribute(required = true)
    protected String settore;
    @XmlAttribute(name = "id_sottosettore", required = true)
    protected String idSottosettore;
    @XmlAttribute(required = true)
    protected String sottosettore;
    @XmlAttribute(name = "id_categoria", required = true)
    protected String idCategoria;
    @XmlAttribute(required = true)
    protected String categoria;
    @XmlAttribute
    protected String cpv1;
    @XmlAttribute
    protected String cpv2;
    @XmlAttribute
    protected String cpv3;
    @XmlAttribute
    protected String cpv4;
    @XmlAttribute
    protected String cpv5;
    @XmlAttribute
    protected String cpv6;
    @XmlAttribute
    protected String cpv7;
    @XmlAttribute
    protected String stato;
    @XmlAttribute
    protected String provvisorio;
    @XmlAttribute
    protected String pubblico;
    @XmlAttribute
    protected String tipo;
    @XmlAttribute(name = "data_generazione", required = true)
    protected String dataGenerazione;
    @XmlAttribute(name = "utente_generatore_provvisorio")
    protected String utenteGeneratoreProvvisorio;
    @XmlAttribute(name = "utente_generatore_completo")
    protected String utenteGeneratoreCompleto;
    @XmlAttribute(name = "utente_riferimento")
    protected String utenteRiferimento;
    @XmlAttribute(name = "data_generazione_completo")
    protected String dataGenerazioneCompleto;
    @XmlAttribute(name = "data_generazione_provvisorio")
    protected String dataGenerazioneProvvisorio;
    @XmlAttribute(name = "utente_ultima_modifica")
    protected String utenteUltimaModifica;
    @XmlAttribute(name = "data_ultima_modifica", required = true)
    protected String dataUltimaModifica;
    @XmlAttribute(name = "utente_ultima_modifica_utente")
    protected String utenteUltimaModificaUtente;
    @XmlAttribute(name = "data_ultima_modifica_utente")
    protected String dataUltimaModificaUtente;
    @XmlAttribute(name = "data_ultima_modifica_ssc")
    protected String dataUltimaModificaSsc;
    @XmlAttribute
    protected String fase;
    @XmlAttribute(name = "cup_in_relazione")
    protected String cupInRelazione;
    @XmlAttribute(name = "ruolo_cup_in_relazione")
    protected String ruoloCupInRelazione;
    @XmlAttribute(name = "tipo_relazione")
    protected String tipoRelazione;
    @XmlAttribute(name = "note_relazione")
    protected String noteRelazione;
    @XmlAttribute(name = "data_chiusura_prevista")
    protected String dataChiusuraPrevista;
    @XmlAttribute(name = "cod_template")
    protected String codTemplate;
    @XmlAttribute
    protected String tematica;

    /**
     * Gets the value of the codiceProgetto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceProgetto() {
        return codiceProgetto;
    }

    /**
     * Sets the value of the codiceProgetto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceProgetto(String value) {
        this.codiceProgetto = value;
    }

    /**
     * Gets the value of the codiceCup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceCup() {
        return codiceCup;
    }

    /**
     * Sets the value of the codiceCup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceCup(String value) {
        this.codiceCup = value;
    }

    /**
     * Gets the value of the codiceCupProvvisorio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceCupProvvisorio() {
        return codiceCupProvvisorio;
    }

    /**
     * Sets the value of the codiceCupProvvisorio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceCupProvvisorio(String value) {
        this.codiceCupProvvisorio = value;
    }

    /**
     * Gets the value of the annoDecisione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnoDecisione() {
        return annoDecisione;
    }

    /**
     * Sets the value of the annoDecisione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnoDecisione(String value) {
        this.annoDecisione = value;
    }

    /**
     * Gets the value of the cumulativo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCumulativo() {
        return cumulativo;
    }

    /**
     * Sets the value of the cumulativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCumulativo(String value) {
        this.cumulativo = value;
    }

    /**
     * Gets the value of the codificaLocale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodificaLocale() {
        return codificaLocale;
    }

    /**
     * Sets the value of the codificaLocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodificaLocale(String value) {
        this.codificaLocale = value;
    }

    /**
     * Gets the value of the idNatura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdNatura() {
        return idNatura;
    }

    /**
     * Sets the value of the idNatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdNatura(String value) {
        this.idNatura = value;
    }

    /**
     * Gets the value of the natura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNatura() {
        return natura;
    }

    /**
     * Sets the value of the natura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNatura(String value) {
        this.natura = value;
    }

    /**
     * Gets the value of the idTipologia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdTipologia() {
        return idTipologia;
    }

    /**
     * Sets the value of the idTipologia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdTipologia(String value) {
        this.idTipologia = value;
    }

    /**
     * Gets the value of the tipologia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipologia() {
        return tipologia;
    }

    /**
     * Sets the value of the tipologia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipologia(String value) {
        this.tipologia = value;
    }

    /**
     * Gets the value of the idSettore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSettore() {
        return idSettore;
    }

    /**
     * Sets the value of the idSettore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSettore(String value) {
        this.idSettore = value;
    }

    /**
     * Gets the value of the settore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettore() {
        return settore;
    }

    /**
     * Sets the value of the settore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettore(String value) {
        this.settore = value;
    }

    /**
     * Gets the value of the idSottosettore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSottosettore() {
        return idSottosettore;
    }

    /**
     * Sets the value of the idSottosettore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSottosettore(String value) {
        this.idSottosettore = value;
    }

    /**
     * Gets the value of the sottosettore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSottosettore() {
        return sottosettore;
    }

    /**
     * Sets the value of the sottosettore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSottosettore(String value) {
        this.sottosettore = value;
    }

    /**
     * Gets the value of the idCategoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdCategoria() {
        return idCategoria;
    }

    /**
     * Sets the value of the idCategoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdCategoria(String value) {
        this.idCategoria = value;
    }

    /**
     * Gets the value of the categoria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoria() {
        return categoria;
    }

    /**
     * Sets the value of the categoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoria(String value) {
        this.categoria = value;
    }

    /**
     * Gets the value of the cpv1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpv1() {
        return cpv1;
    }

    /**
     * Sets the value of the cpv1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpv1(String value) {
        this.cpv1 = value;
    }

    /**
     * Gets the value of the cpv2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpv2() {
        return cpv2;
    }

    /**
     * Sets the value of the cpv2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpv2(String value) {
        this.cpv2 = value;
    }

    /**
     * Gets the value of the cpv3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpv3() {
        return cpv3;
    }

    /**
     * Sets the value of the cpv3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpv3(String value) {
        this.cpv3 = value;
    }

    /**
     * Gets the value of the cpv4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpv4() {
        return cpv4;
    }

    /**
     * Sets the value of the cpv4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpv4(String value) {
        this.cpv4 = value;
    }

    /**
     * Gets the value of the cpv5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpv5() {
        return cpv5;
    }

    /**
     * Sets the value of the cpv5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpv5(String value) {
        this.cpv5 = value;
    }

    /**
     * Gets the value of the cpv6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpv6() {
        return cpv6;
    }

    /**
     * Sets the value of the cpv6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpv6(String value) {
        this.cpv6 = value;
    }

    /**
     * Gets the value of the cpv7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpv7() {
        return cpv7;
    }

    /**
     * Sets the value of the cpv7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpv7(String value) {
        this.cpv7 = value;
    }

    /**
     * Gets the value of the stato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStato() {
        return stato;
    }

    /**
     * Sets the value of the stato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStato(String value) {
        this.stato = value;
    }

    /**
     * Gets the value of the provvisorio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvvisorio() {
        return provvisorio;
    }

    /**
     * Sets the value of the provvisorio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvvisorio(String value) {
        this.provvisorio = value;
    }

    /**
     * Gets the value of the pubblico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPubblico() {
        return pubblico;
    }

    /**
     * Sets the value of the pubblico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPubblico(String value) {
        this.pubblico = value;
    }

    /**
     * Gets the value of the tipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the dataGenerazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataGenerazione() {
        return dataGenerazione;
    }

    /**
     * Sets the value of the dataGenerazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataGenerazione(String value) {
        this.dataGenerazione = value;
    }

    /**
     * Gets the value of the utenteGeneratoreProvvisorio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtenteGeneratoreProvvisorio() {
        return utenteGeneratoreProvvisorio;
    }

    /**
     * Sets the value of the utenteGeneratoreProvvisorio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtenteGeneratoreProvvisorio(String value) {
        this.utenteGeneratoreProvvisorio = value;
    }

    /**
     * Gets the value of the utenteGeneratoreCompleto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtenteGeneratoreCompleto() {
        return utenteGeneratoreCompleto;
    }

    /**
     * Sets the value of the utenteGeneratoreCompleto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtenteGeneratoreCompleto(String value) {
        this.utenteGeneratoreCompleto = value;
    }

    /**
     * Gets the value of the utenteRiferimento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtenteRiferimento() {
        return utenteRiferimento;
    }

    /**
     * Sets the value of the utenteRiferimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtenteRiferimento(String value) {
        this.utenteRiferimento = value;
    }

    /**
     * Gets the value of the dataGenerazioneCompleto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataGenerazioneCompleto() {
        return dataGenerazioneCompleto;
    }

    /**
     * Sets the value of the dataGenerazioneCompleto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataGenerazioneCompleto(String value) {
        this.dataGenerazioneCompleto = value;
    }

    /**
     * Gets the value of the dataGenerazioneProvvisorio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataGenerazioneProvvisorio() {
        return dataGenerazioneProvvisorio;
    }

    /**
     * Sets the value of the dataGenerazioneProvvisorio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataGenerazioneProvvisorio(String value) {
        this.dataGenerazioneProvvisorio = value;
    }

    /**
     * Gets the value of the utenteUltimaModifica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtenteUltimaModifica() {
        return utenteUltimaModifica;
    }

    /**
     * Sets the value of the utenteUltimaModifica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtenteUltimaModifica(String value) {
        this.utenteUltimaModifica = value;
    }

    /**
     * Gets the value of the dataUltimaModifica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataUltimaModifica() {
        return dataUltimaModifica;
    }

    /**
     * Sets the value of the dataUltimaModifica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataUltimaModifica(String value) {
        this.dataUltimaModifica = value;
    }

    /**
     * Gets the value of the utenteUltimaModificaUtente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtenteUltimaModificaUtente() {
        return utenteUltimaModificaUtente;
    }

    /**
     * Sets the value of the utenteUltimaModificaUtente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtenteUltimaModificaUtente(String value) {
        this.utenteUltimaModificaUtente = value;
    }

    /**
     * Gets the value of the dataUltimaModificaUtente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataUltimaModificaUtente() {
        return dataUltimaModificaUtente;
    }

    /**
     * Sets the value of the dataUltimaModificaUtente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataUltimaModificaUtente(String value) {
        this.dataUltimaModificaUtente = value;
    }

    /**
     * Gets the value of the dataUltimaModificaSsc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataUltimaModificaSsc() {
        return dataUltimaModificaSsc;
    }

    /**
     * Sets the value of the dataUltimaModificaSsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataUltimaModificaSsc(String value) {
        this.dataUltimaModificaSsc = value;
    }

    /**
     * Gets the value of the fase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFase() {
        return fase;
    }

    /**
     * Sets the value of the fase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFase(String value) {
        this.fase = value;
    }

    /**
     * Gets the value of the cupInRelazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCupInRelazione() {
        return cupInRelazione;
    }

    /**
     * Sets the value of the cupInRelazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCupInRelazione(String value) {
        this.cupInRelazione = value;
    }

    /**
     * Gets the value of the ruoloCupInRelazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuoloCupInRelazione() {
        return ruoloCupInRelazione;
    }

    /**
     * Sets the value of the ruoloCupInRelazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuoloCupInRelazione(String value) {
        this.ruoloCupInRelazione = value;
    }

    /**
     * Gets the value of the tipoRelazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoRelazione() {
        return tipoRelazione;
    }

    /**
     * Sets the value of the tipoRelazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoRelazione(String value) {
        this.tipoRelazione = value;
    }

    /**
     * Gets the value of the noteRelazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoteRelazione() {
        return noteRelazione;
    }

    /**
     * Sets the value of the noteRelazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoteRelazione(String value) {
        this.noteRelazione = value;
    }

    /**
     * Gets the value of the dataChiusuraPrevista property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataChiusuraPrevista() {
        return dataChiusuraPrevista;
    }

    /**
     * Sets the value of the dataChiusuraPrevista property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataChiusuraPrevista(String value) {
        this.dataChiusuraPrevista = value;
    }

    /**
     * Gets the value of the codTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodTemplate() {
        return codTemplate;
    }

    /**
     * Sets the value of the codTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodTemplate(String value) {
        this.codTemplate = value;
    }

    /**
     * Gets the value of the tematica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTematica() {
        return tematica;
    }

    /**
     * Sets the value of the tematica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTematica(String value) {
        this.tematica = value;
    }

}
