//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatiStipulaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatiStipulaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PubblicazioneEsito" type="{xmlbeans.massload.simog.avlp.it}PubblicazioneType"/>
 *         &lt;element name="Stipula" type="{xmlbeans.massload.simog.avlp.it}StipulaType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiStipulaType", propOrder = {
    "pubblicazioneEsito",
    "stipula"
})
public class DatiStipulaType {

    @XmlElement(name = "PubblicazioneEsito", required = true)
    protected PubblicazioneType pubblicazioneEsito;
    @XmlElement(name = "Stipula", required = true)
    protected StipulaType stipula;

    /**
     * Gets the value of the pubblicazioneEsito property.
     * 
     * @return
     *     possible object is
     *     {@link PubblicazioneType }
     *     
     */
    public PubblicazioneType getPubblicazioneEsito() {
        return pubblicazioneEsito;
    }

    /**
     * Sets the value of the pubblicazioneEsito property.
     * 
     * @param value
     *     allowed object is
     *     {@link PubblicazioneType }
     *     
     */
    public void setPubblicazioneEsito(PubblicazioneType value) {
        this.pubblicazioneEsito = value;
    }

    /**
     * Gets the value of the stipula property.
     * 
     * @return
     *     possible object is
     *     {@link StipulaType }
     *     
     */
    public StipulaType getStipula() {
        return stipula;
    }

    /**
     * Sets the value of the stipula property.
     * 
     * @param value
     *     allowed object is
     *     {@link StipulaType }
     *     
     */
    public void setStipula(StipulaType value) {
        this.stipula = value;
    }

}
