//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:30:08 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatiGara" type="{xmlbeans.massload.simog.avlp.it}DatiGaraType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datiGara"
})
@XmlRootElement(name = "DatiGaraLotto")
public class DatiGaraLotto {

    @XmlElement(name = "DatiGara", required = true)
    protected DatiGaraType datiGara;

    /**
     * Gets the value of the datiGara property.
     * 
     * @return
     *     possible object is
     *     {@link DatiGaraType }
     *     
     */
    public DatiGaraType getDatiGara() {
        return datiGara;
    }

    /**
     * Sets the value of the datiGara property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiGaraType }
     *     
     */
    public void setDatiGara(DatiGaraType value) {
        this.datiGara = value;
    }

}
