//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.03 at 10:47:25 PM CEST 
//


package it.avlp.simog.ws.massload.xmlbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeltaGaraTED complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeltaGaraTED">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ENTITA_APPALTO" type="{xmlbeans.massload.simog.avlp.it}EntitaAppaltoType"/>
 *         &lt;element name="DATI_AMM_AGGIUDICATRICE" type="{xmlbeans.massload.simog.avlp.it}AddrS1Type" maxOccurs="500"/>
 *         &lt;element name="ALTRO_INDIRIZZO_IA" type="{xmlbeans.massload.simog.avlp.it}AddrS1Type" minOccurs="0"/>
 *         &lt;element name="ALTRO_INDIRIZZO_PARTECIPAZIONE" type="{xmlbeans.massload.simog.avlp.it}AddrS1Type" minOccurs="0"/>
 *         &lt;element name="ALTRE_INFO" type="{xmlbeans.massload.simog.avlp.it}AltreInfoType"/>
 *         &lt;element name="CONDIZIONI_PARTECIPAZIONE" type="{xmlbeans.massload.simog.avlp.it}CondizioniPartecipazioneType" minOccurs="0"/>
 *         &lt;element name="DATI_PROCEDURA" type="{xmlbeans.massload.simog.avlp.it}DatiProceduraType"/>
 *         &lt;element name="INFO_AMMINISTRATIVE" type="{xmlbeans.massload.simog.avlp.it}InfoAmministrativeType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="NORMATIVE_APP_CONGIUNTO">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="200"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="APPALTO_CC" use="required" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *       &lt;attribute name="DOCUMENTI_DISPONIBILI" use="required" type="{xmlbeans.massload.simog.avlp.it}DocDisponibiliType" />
 *       &lt;attribute name="URL_DOC_DISPONIBILI" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="250"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="INFO_AGGIUNTIVE" use="required" type="{xmlbeans.massload.simog.avlp.it}AltroIndirizzoType" />
 *       &lt;attribute name="URL_VERSIONE_ELETTRONICA">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="250"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="URL_STRUMENTI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="250"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TIPO_AMM_AGG" use="required" type="{xmlbeans.massload.simog.avlp.it}AmmAggType" />
 *       &lt;attribute name="ALTRO_TIPO_AMM_AGG">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="400"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SETTORE_PRINCIPALE" use="required" type="{xmlbeans.massload.simog.avlp.it}SettorePrincipaleType" />
 *       &lt;attribute name="ALTRO_SETTORE_PRINCIPALE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="200"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeltaGaraTED", propOrder = {
    "entitaappalto",
    "datiammaggiudicatrice",
    "altroindirizzoia",
    "altroindirizzopartecipazione",
    "altreinfo",
    "condizionipartecipazione",
    "datiprocedura",
    "infoamministrative"
})
public class DeltaGaraTED {

    @XmlElement(name = "ENTITA_APPALTO", required = true)
    protected EntitaAppaltoType entitaappalto;
    @XmlElement(name = "DATI_AMM_AGGIUDICATRICE", required = true)
    protected List<AddrS1Type> datiammaggiudicatrice;
    @XmlElement(name = "ALTRO_INDIRIZZO_IA")
    protected AddrS1Type altroindirizzoia;
    @XmlElement(name = "ALTRO_INDIRIZZO_PARTECIPAZIONE")
    protected AddrS1Type altroindirizzopartecipazione;
    @XmlElement(name = "ALTRE_INFO", required = true)
    protected AltreInfoType altreinfo;
    @XmlElement(name = "CONDIZIONI_PARTECIPAZIONE")
    protected CondizioniPartecipazioneType condizionipartecipazione;
    @XmlElement(name = "DATI_PROCEDURA", required = true)
    protected DatiProceduraType datiprocedura;
    @XmlElement(name = "INFO_AMMINISTRATIVE", required = true)
    protected InfoAmministrativeType infoamministrative;
    @XmlAttribute(name = "NORMATIVE_APP_CONGIUNTO", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String normativeappcongiunto;
    @XmlAttribute(name = "APPALTO_CC", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected FlagSNType appaltocc;
    @XmlAttribute(name = "DOCUMENTI_DISPONIBILI", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected DocDisponibiliType documentidisponibili;
    @XmlAttribute(name = "URL_DOC_DISPONIBILI", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected String urldocdisponibili;
    @XmlAttribute(name = "INFO_AGGIUNTIVE", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected AltroIndirizzoType infoaggiuntive;
    @XmlAttribute(name = "URL_VERSIONE_ELETTRONICA", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String urlversioneelettronica;
    @XmlAttribute(name = "URL_STRUMENTI", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String urlstrumenti;
    @XmlAttribute(name = "TIPO_AMM_AGG", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected AmmAggType tipoammagg;
    @XmlAttribute(name = "ALTRO_TIPO_AMM_AGG", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String altrotipoammagg;
    @XmlAttribute(name = "SETTORE_PRINCIPALE", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected SettorePrincipaleType settoreprincipale;
    @XmlAttribute(name = "ALTRO_SETTORE_PRINCIPALE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String altrosettoreprincipale;

    /**
     * Gets the value of the entitaappalto property.
     * 
     * @return
     *     possible object is
     *     {@link EntitaAppaltoType }
     *     
     */
    public EntitaAppaltoType getENTITAAPPALTO() {
        return entitaappalto;
    }

    /**
     * Sets the value of the entitaappalto property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntitaAppaltoType }
     *     
     */
    public void setENTITAAPPALTO(EntitaAppaltoType value) {
        this.entitaappalto = value;
    }

    /**
     * Gets the value of the datiammaggiudicatrice property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datiammaggiudicatrice property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDATIAMMAGGIUDICATRICE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddrS1Type }
     * 
     * 
     */
    public List<AddrS1Type> getDATIAMMAGGIUDICATRICE() {
        if (datiammaggiudicatrice == null) {
            datiammaggiudicatrice = new ArrayList<AddrS1Type>();
        }
        return this.datiammaggiudicatrice;
    }

    /**
     * Gets the value of the altroindirizzoia property.
     * 
     * @return
     *     possible object is
     *     {@link AddrS1Type }
     *     
     */
    public AddrS1Type getALTROINDIRIZZOIA() {
        return altroindirizzoia;
    }

    /**
     * Sets the value of the altroindirizzoia property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddrS1Type }
     *     
     */
    public void setALTROINDIRIZZOIA(AddrS1Type value) {
        this.altroindirizzoia = value;
    }

    /**
     * Gets the value of the altroindirizzopartecipazione property.
     * 
     * @return
     *     possible object is
     *     {@link AddrS1Type }
     *     
     */
    public AddrS1Type getALTROINDIRIZZOPARTECIPAZIONE() {
        return altroindirizzopartecipazione;
    }

    /**
     * Sets the value of the altroindirizzopartecipazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddrS1Type }
     *     
     */
    public void setALTROINDIRIZZOPARTECIPAZIONE(AddrS1Type value) {
        this.altroindirizzopartecipazione = value;
    }

    /**
     * Gets the value of the altreinfo property.
     * 
     * @return
     *     possible object is
     *     {@link AltreInfoType }
     *     
     */
    public AltreInfoType getALTREINFO() {
        return altreinfo;
    }

    /**
     * Sets the value of the altreinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltreInfoType }
     *     
     */
    public void setALTREINFO(AltreInfoType value) {
        this.altreinfo = value;
    }

    /**
     * Gets the value of the condizionipartecipazione property.
     * 
     * @return
     *     possible object is
     *     {@link CondizioniPartecipazioneType }
     *     
     */
    public CondizioniPartecipazioneType getCONDIZIONIPARTECIPAZIONE() {
        return condizionipartecipazione;
    }

    /**
     * Sets the value of the condizionipartecipazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link CondizioniPartecipazioneType }
     *     
     */
    public void setCONDIZIONIPARTECIPAZIONE(CondizioniPartecipazioneType value) {
        this.condizionipartecipazione = value;
    }

    /**
     * Gets the value of the datiprocedura property.
     * 
     * @return
     *     possible object is
     *     {@link DatiProceduraType }
     *     
     */
    public DatiProceduraType getDATIPROCEDURA() {
        return datiprocedura;
    }

    /**
     * Sets the value of the datiprocedura property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiProceduraType }
     *     
     */
    public void setDATIPROCEDURA(DatiProceduraType value) {
        this.datiprocedura = value;
    }

    /**
     * Gets the value of the infoamministrative property.
     * 
     * @return
     *     possible object is
     *     {@link InfoAmministrativeType }
     *     
     */
    public InfoAmministrativeType getINFOAMMINISTRATIVE() {
        return infoamministrative;
    }

    /**
     * Sets the value of the infoamministrative property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoAmministrativeType }
     *     
     */
    public void setINFOAMMINISTRATIVE(InfoAmministrativeType value) {
        this.infoamministrative = value;
    }

    /**
     * Gets the value of the normativeappcongiunto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNORMATIVEAPPCONGIUNTO() {
        return normativeappcongiunto;
    }

    /**
     * Sets the value of the normativeappcongiunto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNORMATIVEAPPCONGIUNTO(String value) {
        this.normativeappcongiunto = value;
    }

    /**
     * Gets the value of the appaltocc property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getAPPALTOCC() {
        return appaltocc;
    }

    /**
     * Sets the value of the appaltocc property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setAPPALTOCC(FlagSNType value) {
        this.appaltocc = value;
    }

    /**
     * Gets the value of the documentidisponibili property.
     * 
     * @return
     *     possible object is
     *     {@link DocDisponibiliType }
     *     
     */
    public DocDisponibiliType getDOCUMENTIDISPONIBILI() {
        return documentidisponibili;
    }

    /**
     * Sets the value of the documentidisponibili property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocDisponibiliType }
     *     
     */
    public void setDOCUMENTIDISPONIBILI(DocDisponibiliType value) {
        this.documentidisponibili = value;
    }

    /**
     * Gets the value of the urldocdisponibili property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURLDOCDISPONIBILI() {
        return urldocdisponibili;
    }

    /**
     * Sets the value of the urldocdisponibili property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURLDOCDISPONIBILI(String value) {
        this.urldocdisponibili = value;
    }

    /**
     * Gets the value of the infoaggiuntive property.
     * 
     * @return
     *     possible object is
     *     {@link AltroIndirizzoType }
     *     
     */
    public AltroIndirizzoType getINFOAGGIUNTIVE() {
        return infoaggiuntive;
    }

    /**
     * Sets the value of the infoaggiuntive property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltroIndirizzoType }
     *     
     */
    public void setINFOAGGIUNTIVE(AltroIndirizzoType value) {
        this.infoaggiuntive = value;
    }

    /**
     * Gets the value of the urlversioneelettronica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURLVERSIONEELETTRONICA() {
        return urlversioneelettronica;
    }

    /**
     * Sets the value of the urlversioneelettronica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURLVERSIONEELETTRONICA(String value) {
        this.urlversioneelettronica = value;
    }

    /**
     * Gets the value of the urlstrumenti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURLSTRUMENTI() {
        return urlstrumenti;
    }

    /**
     * Sets the value of the urlstrumenti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURLSTRUMENTI(String value) {
        this.urlstrumenti = value;
    }

    /**
     * Gets the value of the tipoammagg property.
     * 
     * @return
     *     possible object is
     *     {@link AmmAggType }
     *     
     */
    public AmmAggType getTIPOAMMAGG() {
        return tipoammagg;
    }

    /**
     * Sets the value of the tipoammagg property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmmAggType }
     *     
     */
    public void setTIPOAMMAGG(AmmAggType value) {
        this.tipoammagg = value;
    }

    /**
     * Gets the value of the altrotipoammagg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getALTROTIPOAMMAGG() {
        return altrotipoammagg;
    }

    /**
     * Sets the value of the altrotipoammagg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setALTROTIPOAMMAGG(String value) {
        this.altrotipoammagg = value;
    }

    /**
     * Gets the value of the settoreprincipale property.
     * 
     * @return
     *     possible object is
     *     {@link SettorePrincipaleType }
     *     
     */
    public SettorePrincipaleType getSETTOREPRINCIPALE() {
        return settoreprincipale;
    }

    /**
     * Sets the value of the settoreprincipale property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettorePrincipaleType }
     *     
     */
    public void setSETTOREPRINCIPALE(SettorePrincipaleType value) {
        this.settoreprincipale = value;
    }

    /**
     * Gets the value of the altrosettoreprincipale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getALTROSETTOREPRINCIPALE() {
        return altrosettoreprincipale;
    }

    /**
     * Sets the value of the altrosettoreprincipale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setALTROSETTOREPRINCIPALE(String value) {
        this.altrosettoreprincipale = value;
    }

}
