//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.21 at 11:33:05 AM CEST 
//


package it.avlp.simog.ws.massload.xmlbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DescrizioneAppaltoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescrizioneAppaltoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CRITERIO_QUALITA" type="{xmlbeans.massload.simog.avlp.it}QualityCostCriteriaType" maxOccurs="20" minOccurs="0"/>
 *         &lt;element name="CRITERIO_COSTO" type="{xmlbeans.massload.simog.avlp.it}QualityCostCriteriaType" maxOccurs="20" minOccurs="0"/>
 *         &lt;element name="CRITERIO_PREZZO" type="{xmlbeans.massload.simog.avlp.it}PriceCriteriaType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TITOLO_APPALTO">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="400"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="LUOGO_ESECUZIONE_PRINCIPALE" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="200"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CRITERIO_AGG_LOTTO" use="required" type="{xmlbeans.massload.simog.avlp.it}CriterioAggLottoType" />
 *       &lt;attribute name="TIPO_CRITERIO" use="required" type="{xmlbeans.massload.simog.avlp.it}CriteriaType" />
 *       &lt;attribute name="DESC_RINNOVI_CONTR">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="1000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="NUM_CANDIDATI_PREVISTI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="MIN_NUM_CANDIDATI_PREVISTI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="MAX_NUM_CANDIDATI_PREVISTI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="999"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CRITERI_MAX_NUM_CANDIDATI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="6000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ACCETTATE_VARIANTI" use="required" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *       &lt;attribute name="DESCRIZIONE_OPZIONI">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="6000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="PRES_OFFERTE_CATALOGO_ELETTRONICO" use="required" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *       &lt;attribute name="FLAG_APPALTO_PROGETTO_UE" use="required" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *       &lt;attribute name="APPALTO_PROGETTO_UE">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="400"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ULTERIORI_INFO_LOTTO">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="6000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescrizioneAppaltoType", propOrder = {
    "criterioqualita",
    "criteriocosto",
    "criterioprezzo"
})
public class DescrizioneAppaltoType {

    @XmlElement(name = "CRITERIO_QUALITA")
    protected List<QualityCostCriteriaType> criterioqualita;
    @XmlElement(name = "CRITERIO_COSTO")
    protected List<QualityCostCriteriaType> criteriocosto;
    @XmlElement(name = "CRITERIO_PREZZO")
    protected PriceCriteriaType criterioprezzo;
    @XmlAttribute(name = "TITOLO_APPALTO", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String titoloappalto;
    @XmlAttribute(name = "LUOGO_ESECUZIONE_PRINCIPALE", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected String luogoesecuzioneprincipale;
    @XmlAttribute(name = "CRITERIO_AGG_LOTTO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected CriterioAggLottoType criterioagglotto;
    @XmlAttribute(name = "TIPO_CRITERIO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected CriteriaType tipocriterio;
    @XmlAttribute(name = "DESC_RINNOVI_CONTR", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String descrinnovicontr;
    @XmlAttribute(name = "NUM_CANDIDATI_PREVISTI", namespace = "xmlbeans.massload.simog.avlp.it")
    protected Integer numcandidatiprevisti;
    @XmlAttribute(name = "MIN_NUM_CANDIDATI_PREVISTI", namespace = "xmlbeans.massload.simog.avlp.it")
    protected Integer minnumcandidatiprevisti;
    @XmlAttribute(name = "MAX_NUM_CANDIDATI_PREVISTI", namespace = "xmlbeans.massload.simog.avlp.it")
    protected Integer maxnumcandidatiprevisti;
    @XmlAttribute(name = "CRITERI_MAX_NUM_CANDIDATI", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String criterimaxnumcandidati;
    @XmlAttribute(name = "ACCETTATE_VARIANTI", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected FlagSNType accettatevarianti;
    @XmlAttribute(name = "DESCRIZIONE_OPZIONI", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String descrizioneopzioni;
    @XmlAttribute(name = "PRES_OFFERTE_CATALOGO_ELETTRONICO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected FlagSNType presoffertecatalogoelettronico;
    @XmlAttribute(name = "FLAG_APPALTO_PROGETTO_UE", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected FlagSNType flagappaltoprogettoue;
    @XmlAttribute(name = "APPALTO_PROGETTO_UE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String appaltoprogettoue;
    @XmlAttribute(name = "ULTERIORI_INFO_LOTTO", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String ulterioriinfolotto;

    /**
     * Gets the value of the criterioqualita property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the criterioqualita property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCRITERIOQUALITA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualityCostCriteriaType }
     * 
     * 
     */
    public List<QualityCostCriteriaType> getCRITERIOQUALITA() {
        if (criterioqualita == null) {
            criterioqualita = new ArrayList<QualityCostCriteriaType>();
        }
        return this.criterioqualita;
    }

    /**
     * Gets the value of the criteriocosto property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the criteriocosto property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCRITERIOCOSTO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualityCostCriteriaType }
     * 
     * 
     */
    public List<QualityCostCriteriaType> getCRITERIOCOSTO() {
        if (criteriocosto == null) {
            criteriocosto = new ArrayList<QualityCostCriteriaType>();
        }
        return this.criteriocosto;
    }

    /**
     * Gets the value of the criterioprezzo property.
     * 
     * @return
     *     possible object is
     *     {@link PriceCriteriaType }
     *     
     */
    public PriceCriteriaType getCRITERIOPREZZO() {
        return criterioprezzo;
    }

    /**
     * Sets the value of the criterioprezzo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceCriteriaType }
     *     
     */
    public void setCRITERIOPREZZO(PriceCriteriaType value) {
        this.criterioprezzo = value;
    }

    /**
     * Gets the value of the titoloappalto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTITOLOAPPALTO() {
        return titoloappalto;
    }

    /**
     * Sets the value of the titoloappalto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTITOLOAPPALTO(String value) {
        this.titoloappalto = value;
    }

    /**
     * Gets the value of the luogoesecuzioneprincipale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLUOGOESECUZIONEPRINCIPALE() {
        return luogoesecuzioneprincipale;
    }

    /**
     * Sets the value of the luogoesecuzioneprincipale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLUOGOESECUZIONEPRINCIPALE(String value) {
        this.luogoesecuzioneprincipale = value;
    }

    /**
     * Gets the value of the criterioagglotto property.
     * 
     * @return
     *     possible object is
     *     {@link CriterioAggLottoType }
     *     
     */
    public CriterioAggLottoType getCRITERIOAGGLOTTO() {
        return criterioagglotto;
    }

    /**
     * Sets the value of the criterioagglotto property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriterioAggLottoType }
     *     
     */
    public void setCRITERIOAGGLOTTO(CriterioAggLottoType value) {
        this.criterioagglotto = value;
    }

    /**
     * Gets the value of the tipocriterio property.
     * 
     * @return
     *     possible object is
     *     {@link CriteriaType }
     *     
     */
    public CriteriaType getTIPOCRITERIO() {
        return tipocriterio;
    }

    /**
     * Sets the value of the tipocriterio property.
     * 
     * @param value
     *     allowed object is
     *     {@link CriteriaType }
     *     
     */
    public void setTIPOCRITERIO(CriteriaType value) {
        this.tipocriterio = value;
    }

    /**
     * Gets the value of the descrinnovicontr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRINNOVICONTR() {
        return descrinnovicontr;
    }

    /**
     * Sets the value of the descrinnovicontr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRINNOVICONTR(String value) {
        this.descrinnovicontr = value;
    }

    /**
     * Gets the value of the numcandidatiprevisti property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNUMCANDIDATIPREVISTI() {
        return numcandidatiprevisti;
    }

    /**
     * Sets the value of the numcandidatiprevisti property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNUMCANDIDATIPREVISTI(Integer value) {
        this.numcandidatiprevisti = value;
    }

    /**
     * Gets the value of the minnumcandidatiprevisti property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMINNUMCANDIDATIPREVISTI() {
        return minnumcandidatiprevisti;
    }

    /**
     * Sets the value of the minnumcandidatiprevisti property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMINNUMCANDIDATIPREVISTI(Integer value) {
        this.minnumcandidatiprevisti = value;
    }

    /**
     * Gets the value of the maxnumcandidatiprevisti property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMAXNUMCANDIDATIPREVISTI() {
        return maxnumcandidatiprevisti;
    }

    /**
     * Sets the value of the maxnumcandidatiprevisti property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMAXNUMCANDIDATIPREVISTI(Integer value) {
        this.maxnumcandidatiprevisti = value;
    }

    /**
     * Gets the value of the criterimaxnumcandidati property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRITERIMAXNUMCANDIDATI() {
        return criterimaxnumcandidati;
    }

    /**
     * Sets the value of the criterimaxnumcandidati property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRITERIMAXNUMCANDIDATI(String value) {
        this.criterimaxnumcandidati = value;
    }

    /**
     * Gets the value of the accettatevarianti property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getACCETTATEVARIANTI() {
        return accettatevarianti;
    }

    /**
     * Sets the value of the accettatevarianti property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setACCETTATEVARIANTI(FlagSNType value) {
        this.accettatevarianti = value;
    }

    /**
     * Gets the value of the descrizioneopzioni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIZIONEOPZIONI() {
        return descrizioneopzioni;
    }

    /**
     * Sets the value of the descrizioneopzioni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIZIONEOPZIONI(String value) {
        this.descrizioneopzioni = value;
    }

    /**
     * Gets the value of the presoffertecatalogoelettronico property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getPRESOFFERTECATALOGOELETTRONICO() {
        return presoffertecatalogoelettronico;
    }

    /**
     * Sets the value of the presoffertecatalogoelettronico property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setPRESOFFERTECATALOGOELETTRONICO(FlagSNType value) {
        this.presoffertecatalogoelettronico = value;
    }

    /**
     * Gets the value of the flagappaltoprogettoue property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getFLAGAPPALTOPROGETTOUE() {
        return flagappaltoprogettoue;
    }

    /**
     * Sets the value of the flagappaltoprogettoue property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setFLAGAPPALTOPROGETTOUE(FlagSNType value) {
        this.flagappaltoprogettoue = value;
    }

    /**
     * Gets the value of the appaltoprogettoue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPALTOPROGETTOUE() {
        return appaltoprogettoue;
    }

    /**
     * Sets the value of the appaltoprogettoue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPALTOPROGETTOUE(String value) {
        this.appaltoprogettoue = value;
    }

    /**
     * Gets the value of the ulterioriinfolotto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getULTERIORIINFOLOTTO() {
        return ulterioriinfolotto;
    }

    /**
     * Sets the value of the ulterioriinfolotto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setULTERIORIINFOLOTTO(String value) {
        this.ulterioriinfolotto = value;
    }

}
