//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FinanziamentoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FinanziamentoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ID_FINANZIAMENTO" use="required" type="{xmlbeans.massload.simog.avlp.it}TipoFinanziamentoType" />
 *       &lt;attribute name="IMPORTO_FINANZIAMENTO" use="required" type="{xmlbeans.massload.simog.avlp.it}ImportoType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FinanziamentoType")
public class FinanziamentoType {

    @XmlAttribute(name = "ID_FINANZIAMENTO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected TipoFinanziamentoType idfinanziamento;
    @XmlAttribute(name = "IMPORTO_FINANZIAMENTO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected ImportoType importofinanziamento;

    /**
     * Gets the value of the idfinanziamento property.
     * 
     * @return
     *     possible object is
     *     {@link TipoFinanziamentoType }
     *     
     */
    public TipoFinanziamentoType getIDFINANZIAMENTO() {
        return idfinanziamento;
    }

    /**
     * Sets the value of the idfinanziamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoFinanziamentoType }
     *     
     */
    public void setIDFINANZIAMENTO(TipoFinanziamentoType value) {
        this.idfinanziamento = value;
    }

    /**
     * Gets the value of the importofinanziamento property.
     * 
     * @return
     *     possible object is
     *     {@link ImportoType }
     *     
     */
    public ImportoType getIMPORTOFINANZIAMENTO() {
        return importofinanziamento;
    }

    /**
     * Sets the value of the importofinanziamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportoType }
     *     
     */
    public void setIMPORTOFINANZIAMENTO(ImportoType value) {
        this.importofinanziamento = value;
    }

}
