//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IncaricatoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncaricatoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="SEZIONE" use="required" type="{xmlbeans.massload.simog.avlp.it}SezioneType" />
 *       &lt;attribute name="ID_RUOLO" use="required" type="{xmlbeans.massload.simog.avlp.it}RuoloResponsabileType" />
 *       &lt;attribute name="CIG_PROG_ESTERNA" type="{xmlbeans.massload.simog.avlp.it}CigType" />
 *       &lt;attribute name="DATA_AFF_PROG_ESTERNA" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="DATA_CONS_PROG_ESTERNA" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="CODICE_FISCALE_RESPONSABILE" use="required" type="{xmlbeans.massload.simog.avlp.it}CodFiscType" />
 *       &lt;attribute name="CODICE_STATO" type="{xmlbeans.massload.simog.avlp.it}StatoEsteroType" />
 *       &lt;attribute name="PERSONA_GIURIDICA" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *       &lt;attribute name="ID_GRUPPO_INCARICATO" type="{xmlbeans.massload.simog.avlp.it}InteroType99" />
 *       &lt;attribute name="MANDANTE" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncaricatoType")
public class IncaricatoType {

    @XmlAttribute(name = "SEZIONE", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected SezioneType sezione;
    @XmlAttribute(name = "ID_RUOLO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected RuoloResponsabileType idruolo;
    @XmlAttribute(name = "CIG_PROG_ESTERNA", namespace = "xmlbeans.massload.simog.avlp.it")
    protected CigType cigprogesterna;
    @XmlAttribute(name = "DATA_AFF_PROG_ESTERNA", namespace = "xmlbeans.massload.simog.avlp.it")
    protected DbDateType dataaffprogesterna;
    @XmlAttribute(name = "DATA_CONS_PROG_ESTERNA", namespace = "xmlbeans.massload.simog.avlp.it")
    protected DbDateType dataconsprogesterna;
    @XmlAttribute(name = "CODICE_FISCALE_RESPONSABILE", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected CodFiscType codicefiscaleresponsabile;
    @XmlAttribute(name = "CODICE_STATO", namespace = "xmlbeans.massload.simog.avlp.it")
    protected StatoEsteroType codicestato;
    @XmlAttribute(name = "PERSONA_GIURIDICA", namespace = "xmlbeans.massload.simog.avlp.it")
    protected FlagSNType personagiuridica;
    @XmlAttribute(name = "ID_GRUPPO_INCARICATO", namespace = "xmlbeans.massload.simog.avlp.it")
    protected InteroType99 idgruppoincaricato;
    @XmlAttribute(name = "MANDANTE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected FlagSNType mandante;

    /**
     * Gets the value of the sezione property.
     * 
     * @return
     *     possible object is
     *     {@link SezioneType }
     *     
     */
    public SezioneType getSEZIONE() {
        return sezione;
    }

    /**
     * Sets the value of the sezione property.
     * 
     * @param value
     *     allowed object is
     *     {@link SezioneType }
     *     
     */
    public void setSEZIONE(SezioneType value) {
        this.sezione = value;
    }

    /**
     * Gets the value of the idruolo property.
     * 
     * @return
     *     possible object is
     *     {@link RuoloResponsabileType }
     *     
     */
    public RuoloResponsabileType getIDRUOLO() {
        return idruolo;
    }

    /**
     * Sets the value of the idruolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuoloResponsabileType }
     *     
     */
    public void setIDRUOLO(RuoloResponsabileType value) {
        this.idruolo = value;
    }

    /**
     * Gets the value of the cigprogesterna property.
     * 
     * @return
     *     possible object is
     *     {@link CigType }
     *     
     */
    public CigType getCIGPROGESTERNA() {
        return cigprogesterna;
    }

    /**
     * Sets the value of the cigprogesterna property.
     * 
     * @param value
     *     allowed object is
     *     {@link CigType }
     *     
     */
    public void setCIGPROGESTERNA(CigType value) {
        this.cigprogesterna = value;
    }

    /**
     * Gets the value of the dataaffprogesterna property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATAAFFPROGESTERNA() {
        return dataaffprogesterna;
    }

    /**
     * Sets the value of the dataaffprogesterna property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATAAFFPROGESTERNA(DbDateType value) {
        this.dataaffprogesterna = value;
    }

    /**
     * Gets the value of the dataconsprogesterna property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATACONSPROGESTERNA() {
        return dataconsprogesterna;
    }

    /**
     * Sets the value of the dataconsprogesterna property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATACONSPROGESTERNA(DbDateType value) {
        this.dataconsprogesterna = value;
    }

    /**
     * Gets the value of the codicefiscaleresponsabile property.
     * 
     * @return
     *     possible object is
     *     {@link CodFiscType }
     *     
     */
    public CodFiscType getCODICEFISCALERESPONSABILE() {
        return codicefiscaleresponsabile;
    }

    /**
     * Sets the value of the codicefiscaleresponsabile property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodFiscType }
     *     
     */
    public void setCODICEFISCALERESPONSABILE(CodFiscType value) {
        this.codicefiscaleresponsabile = value;
    }

    /**
     * Gets the value of the codicestato property.
     * 
     * @return
     *     possible object is
     *     {@link StatoEsteroType }
     *     
     */
    public StatoEsteroType getCODICESTATO() {
        return codicestato;
    }

    /**
     * Sets the value of the codicestato property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatoEsteroType }
     *     
     */
    public void setCODICESTATO(StatoEsteroType value) {
        this.codicestato = value;
    }

    /**
     * Gets the value of the personagiuridica property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getPERSONAGIURIDICA() {
        return personagiuridica;
    }

    /**
     * Sets the value of the personagiuridica property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setPERSONAGIURIDICA(FlagSNType value) {
        this.personagiuridica = value;
    }

    /**
     * Gets the value of the idgruppoincaricato property.
     * 
     * @return
     *     possible object is
     *     {@link InteroType99 }
     *     
     */
    public InteroType99 getIDGRUPPOINCARICATO() {
        return idgruppoincaricato;
    }

    /**
     * Sets the value of the idgruppoincaricato property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteroType99 }
     *     
     */
    public void setIDGRUPPOINCARICATO(InteroType99 value) {
        this.idgruppoincaricato = value;
    }

    /**
     * Gets the value of the mandante property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getMANDANTE() {
        return mandante;
    }

    /**
     * Sets the value of the mandante property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setMANDANTE(FlagSNType value) {
        this.mandante = value;
    }

}
