//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.22 at 05:23:58 PM CEST 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="codIndicatore" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="descIndicatore" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="codTipologiaIndicatore" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="descTipologiaIndicatore" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "INDICATORE")
public class INDICATORE {

    @XmlAttribute(required = true)
    protected String codIndicatore;
    @XmlAttribute(required = true)
    protected String descIndicatore;
    @XmlAttribute(required = true)
    protected int codTipologiaIndicatore;
    @XmlAttribute(required = true)
    protected String descTipologiaIndicatore;

    /**
     * Gets the value of the codIndicatore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodIndicatore() {
        return codIndicatore;
    }

    /**
     * Sets the value of the codIndicatore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodIndicatore(String value) {
        this.codIndicatore = value;
    }

    /**
     * Gets the value of the descIndicatore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescIndicatore() {
        return descIndicatore;
    }

    /**
     * Sets the value of the descIndicatore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescIndicatore(String value) {
        this.descIndicatore = value;
    }

    /**
     * Gets the value of the codTipologiaIndicatore property.
     * 
     */
    public int getCodTipologiaIndicatore() {
        return codTipologiaIndicatore;
    }

    /**
     * Sets the value of the codTipologiaIndicatore property.
     * 
     */
    public void setCodTipologiaIndicatore(int value) {
        this.codTipologiaIndicatore = value;
    }

    /**
     * Gets the value of the descTipologiaIndicatore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescTipologiaIndicatore() {
        return descTipologiaIndicatore;
    }

    /**
     * Sets the value of the descTipologiaIndicatore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescTipologiaIndicatore(String value) {
        this.descTipologiaIndicatore = value;
    }

}
