//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:24:50 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for listaCentroCostoResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="listaCentroCostoResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stazioneAppaltante" type="{xmlbeans.massload.simog.avlp.it}stazioneAppaltanteType"/>
 *         &lt;element name="listaCentriCosto" type="{xmlbeans.massload.simog.avlp.it}listaCentriCostoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listaCentroCostoResponseType", propOrder = {
    "stazioneAppaltante",
    "listaCentriCosto"
})
public class ListaCentroCostoResponseType {

    @XmlElement(required = true)
    protected StazioneAppaltanteType stazioneAppaltante;
    @XmlElement(required = true)
    protected ListaCentriCostoType listaCentriCosto;

    /**
     * Gets the value of the stazioneAppaltante property.
     * 
     * @return
     *     possible object is
     *     {@link StazioneAppaltanteType }
     *     
     */
    public StazioneAppaltanteType getStazioneAppaltante() {
        return stazioneAppaltante;
    }

    /**
     * Sets the value of the stazioneAppaltante property.
     * 
     * @param value
     *     allowed object is
     *     {@link StazioneAppaltanteType }
     *     
     */
    public void setStazioneAppaltante(StazioneAppaltanteType value) {
        this.stazioneAppaltante = value;
    }

    /**
     * Gets the value of the listaCentriCosto property.
     * 
     * @return
     *     possible object is
     *     {@link ListaCentriCostoType }
     *     
     */
    public ListaCentriCostoType getListaCentriCosto() {
        return listaCentriCosto;
    }

    /**
     * Sets the value of the listaCentriCosto property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListaCentriCostoType }
     *     
     */
    public void setListaCentriCosto(ListaCentriCostoType value) {
        this.listaCentriCosto = value;
    }

}
