//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:24:50 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for loginWSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="loginWSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Utente" type="{xmlbeans.massload.simog.avlp.it}CodFiscType"/>
 *         &lt;element name="Password" type="{xmlbeans.massload.simog.avlp.it}CodFiscType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "loginWSType", propOrder = {
    "utente",
    "password"
})
public class LoginWSType {

    @XmlElement(name = "Utente", required = true)
    protected CodFiscType utente;
    @XmlElement(name = "Password", required = true)
    protected CodFiscType password;

    /**
     * Gets the value of the utente property.
     * 
     * @return
     *     possible object is
     *     {@link CodFiscType }
     *     
     */
    public CodFiscType getUtente() {
        return utente;
    }

    /**
     * Sets the value of the utente property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodFiscType }
     *     
     */
    public void setUtente(CodFiscType value) {
        this.utente = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link CodFiscType }
     *     
     */
    public CodFiscType getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodFiscType }
     *     
     */
    public void setPassword(CodFiscType value) {
        this.password = value;
    }

}
