//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.22 at 05:23:58 PM CEST 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="cup_master" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ragioni_collegamento" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "MASTER")
public class MASTER {

    @XmlAttribute(name = "cup_master")
    protected String cupMaster;
    @XmlAttribute(name = "ragioni_collegamento")
    protected String ragioniCollegamento;

    /**
     * Gets the value of the cupMaster property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCupMaster() {
        return cupMaster;
    }

    /**
     * Sets the value of the cupMaster property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCupMaster(String value) {
        this.cupMaster = value;
    }

    /**
     * Gets the value of the ragioniCollegamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRagioniCollegamento() {
        return ragioniCollegamento;
    }

    /**
     * Sets the value of the ragioniCollegamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRagioniCollegamento(String value) {
        this.ragioniCollegamento = value;
    }

}
