//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PosizioneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PosizioneType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="CODICE_FISCALE_AGGIUDICATARIO" use="required" type="{xmlbeans.massload.simog.avlp.it}CodFiscType" />
 *       &lt;attribute name="CODICE_STATO" use="required" type="{xmlbeans.massload.simog.avlp.it}StatoEsteroType" />
 *       &lt;attribute name="CODICE_INPS">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="20"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CODICE_INAIL">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="20"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CODICE_CASSA">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="20"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PosizioneType")
public class PosizioneType {

    @XmlAttribute(name = "CODICE_FISCALE_AGGIUDICATARIO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected CodFiscType codicefiscaleaggiudicatario;
    @XmlAttribute(name = "CODICE_STATO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected StatoEsteroType codicestato;
    @XmlAttribute(name = "CODICE_INPS", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String codiceinps;
    @XmlAttribute(name = "CODICE_INAIL", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String codiceinail;
    @XmlAttribute(name = "CODICE_CASSA", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String codicecassa;

    /**
     * Gets the value of the codicefiscaleaggiudicatario property.
     * 
     * @return
     *     possible object is
     *     {@link CodFiscType }
     *     
     */
    public CodFiscType getCODICEFISCALEAGGIUDICATARIO() {
        return codicefiscaleaggiudicatario;
    }

    /**
     * Sets the value of the codicefiscaleaggiudicatario property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodFiscType }
     *     
     */
    public void setCODICEFISCALEAGGIUDICATARIO(CodFiscType value) {
        this.codicefiscaleaggiudicatario = value;
    }

    /**
     * Gets the value of the codicestato property.
     * 
     * @return
     *     possible object is
     *     {@link StatoEsteroType }
     *     
     */
    public StatoEsteroType getCODICESTATO() {
        return codicestato;
    }

    /**
     * Sets the value of the codicestato property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatoEsteroType }
     *     
     */
    public void setCODICESTATO(StatoEsteroType value) {
        this.codicestato = value;
    }

    /**
     * Gets the value of the codiceinps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODICEINPS() {
        return codiceinps;
    }

    /**
     * Sets the value of the codiceinps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODICEINPS(String value) {
        this.codiceinps = value;
    }

    /**
     * Gets the value of the codiceinail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODICEINAIL() {
        return codiceinail;
    }

    /**
     * Sets the value of the codiceinail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODICEINAIL(String value) {
        this.codiceinail = value;
    }

    /**
     * Gets the value of the codicecassa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODICECASSA() {
        return codicecassa;
    }

    /**
     * Sets the value of the codicecassa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODICECASSA(String value) {
        this.codicecassa = value;
    }

}
