//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PubblicazioneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PubblicazioneType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DATA_GUCE" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="DATA_GURI" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="DATA_ALBO" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="DATA_BORE" type="{xmlbeans.massload.simog.avlp.it}DbDateType" />
 *       &lt;attribute name="QUOTIDIANI_NAZ" type="{xmlbeans.massload.simog.avlp.it}InteroType" />
 *       &lt;attribute name="QUOTIDIANI_REG" type="{xmlbeans.massload.simog.avlp.it}InteroType" />
 *       &lt;attribute name="PERIODICI" type="{xmlbeans.massload.simog.avlp.it}InteroType" />
 *       &lt;attribute name="PROFILO_COMMITTENTE" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *       &lt;attribute name="SITO_MINISTERO_INF_TRASP" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *       &lt;attribute name="SITO_OSSERVATORIO_CP" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *       &lt;attribute name="ID_SCHEDA_LOCALE" type="{xmlbeans.massload.simog.avlp.it}IdSchedaType" />
 *       &lt;attribute name="ID_SCHEDA_SIMOG" type="{xmlbeans.massload.simog.avlp.it}IdSchedaType" />
 *       &lt;attribute name="NUMERO_GUCE" type="{xmlbeans.massload.simog.avlp.it}CuiType" />
 *       &lt;attribute name="NUMERO_GURI" type="{xmlbeans.massload.simog.avlp.it}CuiType" />
 *       &lt;attribute name="NUMERO_BORE" type="{xmlbeans.massload.simog.avlp.it}CuiType" />
 *       &lt;attribute name="LINK_SITO">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="250"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="LINK_AFFIDAMENTO_DIRETTO" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="FLAG_BENICULT" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *       &lt;attribute name="FLAG_SOSPESO" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PubblicazioneType")
public class PubblicazioneType {

    @XmlAttribute(name = "DATA_GUCE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected DbDateType dataguce;
    @XmlAttribute(name = "DATA_GURI", namespace = "xmlbeans.massload.simog.avlp.it")
    protected DbDateType dataguri;
    @XmlAttribute(name = "DATA_ALBO", namespace = "xmlbeans.massload.simog.avlp.it")
    protected DbDateType dataalbo;
    @XmlAttribute(name = "DATA_BORE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected DbDateType databore;
    @XmlAttribute(name = "QUOTIDIANI_NAZ", namespace = "xmlbeans.massload.simog.avlp.it")
    protected InteroType quotidianinaz;
    @XmlAttribute(name = "QUOTIDIANI_REG", namespace = "xmlbeans.massload.simog.avlp.it")
    protected InteroType quotidianireg;
    @XmlAttribute(name = "PERIODICI", namespace = "xmlbeans.massload.simog.avlp.it")
    protected InteroType periodici;
    @XmlAttribute(name = "PROFILO_COMMITTENTE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected FlagSNType profilocommittente;
    @XmlAttribute(name = "SITO_MINISTERO_INF_TRASP", namespace = "xmlbeans.massload.simog.avlp.it")
    protected FlagSNType sitoministeroinftrasp;
    @XmlAttribute(name = "SITO_OSSERVATORIO_CP", namespace = "xmlbeans.massload.simog.avlp.it")
    protected FlagSNType sitoosservatoriocp;
    @XmlAttribute(name = "ID_SCHEDA_LOCALE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected IdSchedaType idschedalocale;
    @XmlAttribute(name = "ID_SCHEDA_SIMOG", namespace = "xmlbeans.massload.simog.avlp.it")
    protected IdSchedaType idschedasimog;
    @XmlAttribute(name = "NUMERO_GUCE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected CuiType numeroguce;
    @XmlAttribute(name = "NUMERO_GURI", namespace = "xmlbeans.massload.simog.avlp.it")
    protected CuiType numeroguri;
    @XmlAttribute(name = "NUMERO_BORE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected CuiType numerobore;
    @XmlAttribute(name = "LINK_SITO", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String linksito;
    @XmlAttribute(name = "LINK_AFFIDAMENTO_DIRETTO", namespace = "xmlbeans.massload.simog.avlp.it")
    protected String linkaffidamentodiretto;
    @XmlAttribute(name = "FLAG_BENICULT", namespace = "xmlbeans.massload.simog.avlp.it")
    protected FlagSNType flagbenicult;
    @XmlAttribute(name = "FLAG_SOSPESO", namespace = "xmlbeans.massload.simog.avlp.it")
    protected FlagSNType flagsospeso;

    /**
     * Gets the value of the dataguce property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATAGUCE() {
        return dataguce;
    }

    /**
     * Sets the value of the dataguce property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATAGUCE(DbDateType value) {
        this.dataguce = value;
    }

    /**
     * Gets the value of the dataguri property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATAGURI() {
        return dataguri;
    }

    /**
     * Sets the value of the dataguri property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATAGURI(DbDateType value) {
        this.dataguri = value;
    }

    /**
     * Gets the value of the dataalbo property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATAALBO() {
        return dataalbo;
    }

    /**
     * Sets the value of the dataalbo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATAALBO(DbDateType value) {
        this.dataalbo = value;
    }

    /**
     * Gets the value of the databore property.
     * 
     * @return
     *     possible object is
     *     {@link DbDateType }
     *     
     */
    public DbDateType getDATABORE() {
        return databore;
    }

    /**
     * Sets the value of the databore property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbDateType }
     *     
     */
    public void setDATABORE(DbDateType value) {
        this.databore = value;
    }

    /**
     * Gets the value of the quotidianinaz property.
     * 
     * @return
     *     possible object is
     *     {@link InteroType }
     *     
     */
    public InteroType getQUOTIDIANINAZ() {
        return quotidianinaz;
    }

    /**
     * Sets the value of the quotidianinaz property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteroType }
     *     
     */
    public void setQUOTIDIANINAZ(InteroType value) {
        this.quotidianinaz = value;
    }

    /**
     * Gets the value of the quotidianireg property.
     * 
     * @return
     *     possible object is
     *     {@link InteroType }
     *     
     */
    public InteroType getQUOTIDIANIREG() {
        return quotidianireg;
    }

    /**
     * Sets the value of the quotidianireg property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteroType }
     *     
     */
    public void setQUOTIDIANIREG(InteroType value) {
        this.quotidianireg = value;
    }

    /**
     * Gets the value of the periodici property.
     * 
     * @return
     *     possible object is
     *     {@link InteroType }
     *     
     */
    public InteroType getPERIODICI() {
        return periodici;
    }

    /**
     * Sets the value of the periodici property.
     * 
     * @param value
     *     allowed object is
     *     {@link InteroType }
     *     
     */
    public void setPERIODICI(InteroType value) {
        this.periodici = value;
    }

    /**
     * Gets the value of the profilocommittente property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getPROFILOCOMMITTENTE() {
        return profilocommittente;
    }

    /**
     * Sets the value of the profilocommittente property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setPROFILOCOMMITTENTE(FlagSNType value) {
        this.profilocommittente = value;
    }

    /**
     * Gets the value of the sitoministeroinftrasp property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getSITOMINISTEROINFTRASP() {
        return sitoministeroinftrasp;
    }

    /**
     * Sets the value of the sitoministeroinftrasp property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setSITOMINISTEROINFTRASP(FlagSNType value) {
        this.sitoministeroinftrasp = value;
    }

    /**
     * Gets the value of the sitoosservatoriocp property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getSITOOSSERVATORIOCP() {
        return sitoosservatoriocp;
    }

    /**
     * Sets the value of the sitoosservatoriocp property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setSITOOSSERVATORIOCP(FlagSNType value) {
        this.sitoosservatoriocp = value;
    }

    /**
     * Gets the value of the idschedalocale property.
     * 
     * @return
     *     possible object is
     *     {@link IdSchedaType }
     *     
     */
    public IdSchedaType getIDSCHEDALOCALE() {
        return idschedalocale;
    }

    /**
     * Sets the value of the idschedalocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdSchedaType }
     *     
     */
    public void setIDSCHEDALOCALE(IdSchedaType value) {
        this.idschedalocale = value;
    }

    /**
     * Gets the value of the idschedasimog property.
     * 
     * @return
     *     possible object is
     *     {@link IdSchedaType }
     *     
     */
    public IdSchedaType getIDSCHEDASIMOG() {
        return idschedasimog;
    }

    /**
     * Sets the value of the idschedasimog property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdSchedaType }
     *     
     */
    public void setIDSCHEDASIMOG(IdSchedaType value) {
        this.idschedasimog = value;
    }

    /**
     * Gets the value of the numeroguce property.
     * 
     * @return
     *     possible object is
     *     {@link CuiType }
     *     
     */
    public CuiType getNUMEROGUCE() {
        return numeroguce;
    }

    /**
     * Sets the value of the numeroguce property.
     * 
     * @param value
     *     allowed object is
     *     {@link CuiType }
     *     
     */
    public void setNUMEROGUCE(CuiType value) {
        this.numeroguce = value;
    }

    /**
     * Gets the value of the numeroguri property.
     * 
     * @return
     *     possible object is
     *     {@link CuiType }
     *     
     */
    public CuiType getNUMEROGURI() {
        return numeroguri;
    }

    /**
     * Sets the value of the numeroguri property.
     * 
     * @param value
     *     allowed object is
     *     {@link CuiType }
     *     
     */
    public void setNUMEROGURI(CuiType value) {
        this.numeroguri = value;
    }

    /**
     * Gets the value of the numerobore property.
     * 
     * @return
     *     possible object is
     *     {@link CuiType }
     *     
     */
    public CuiType getNUMEROBORE() {
        return numerobore;
    }

    /**
     * Sets the value of the numerobore property.
     * 
     * @param value
     *     allowed object is
     *     {@link CuiType }
     *     
     */
    public void setNUMEROBORE(CuiType value) {
        this.numerobore = value;
    }

    /**
     * Gets the value of the linksito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLINKSITO() {
        return linksito;
    }

    /**
     * Sets the value of the linksito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLINKSITO(String value) {
        this.linksito = value;
    }

    /**
     * Gets the value of the linkaffidamentodiretto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLINKAFFIDAMENTODIRETTO() {
        return linkaffidamentodiretto;
    }

    /**
     * Sets the value of the linkaffidamentodiretto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLINKAFFIDAMENTODIRETTO(String value) {
        this.linkaffidamentodiretto = value;
    }

    /**
     * Gets the value of the flagbenicult property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getFLAGBENICULT() {
        return flagbenicult;
    }

    /**
     * Sets the value of the flagbenicult property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setFLAGBENICULT(FlagSNType value) {
        this.flagbenicult = value;
    }

    /**
     * Gets the value of the flagsospeso property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getFLAGSOSPESO() {
        return flagsospeso;
    }

    /**
     * Sets the value of the flagsospeso property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setFLAGSOSPESO(FlagSNType value) {
        this.flagsospeso = value;
    }

}
