//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.03 at 10:48:06 PM CEST 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QualityCostCriteriaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QualityCostCriteriaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="QPC_CRITERIA_NAME" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="1000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="QPC_CRITERIA_WEIGHTING" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="30"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QualityCostCriteriaType")
public class QualityCostCriteriaType {

    @XmlAttribute(name = "QPC_CRITERIA_NAME", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected String qpccriterianame;
    @XmlAttribute(name = "QPC_CRITERIA_WEIGHTING", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected String qpccriteriaweighting;

    /**
     * Gets the value of the qpccriterianame property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQPCCRITERIANAME() {
        return qpccriterianame;
    }

    /**
     * Sets the value of the qpccriterianame property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQPCCRITERIANAME(String value) {
        this.qpccriterianame = value;
    }

    /**
     * Gets the value of the qpccriteriaweighting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQPCCRITERIAWEIGHTING() {
        return qpccriteriaweighting;
    }

    /**
     * Sets the value of the qpccriteriaweighting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQPCCRITERIAWEIGHTING(String value) {
        this.qpccriteriaweighting = value;
    }

}
