//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecIdSchedaElimType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecIdSchedaElimType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="CIG" use="required" type="{xmlbeans.massload.simog.avlp.it}CigType" />
 *       &lt;attribute name="CUI" use="required" type="{xmlbeans.massload.simog.avlp.it}CuiType" />
 *       &lt;attribute name="SCHEDA" type="{xmlbeans.massload.simog.avlp.it}TipiSchedeType" />
 *       &lt;attribute name="ID_SCHEDA_SIMOG" type="{xmlbeans.massload.simog.avlp.it}IdSchedaType" />
 *       &lt;attribute name="ID_SCHEDA_LOCALE" type="{xmlbeans.massload.simog.avlp.it}IdSchedaType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecIdSchedaElimType")
public class RecIdSchedaElimType {

    @XmlAttribute(name = "CIG", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected CigType cig;
    @XmlAttribute(name = "CUI", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected CuiType cui;
    @XmlAttribute(name = "SCHEDA", namespace = "xmlbeans.massload.simog.avlp.it")
    protected TipiSchedeType scheda;
    @XmlAttribute(name = "ID_SCHEDA_SIMOG", namespace = "xmlbeans.massload.simog.avlp.it")
    protected IdSchedaType idschedasimog;
    @XmlAttribute(name = "ID_SCHEDA_LOCALE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected IdSchedaType idschedalocale;

    /**
     * Gets the value of the cig property.
     * 
     * @return
     *     possible object is
     *     {@link CigType }
     *     
     */
    public CigType getCIG() {
        return cig;
    }

    /**
     * Sets the value of the cig property.
     * 
     * @param value
     *     allowed object is
     *     {@link CigType }
     *     
     */
    public void setCIG(CigType value) {
        this.cig = value;
    }

    /**
     * Gets the value of the cui property.
     * 
     * @return
     *     possible object is
     *     {@link CuiType }
     *     
     */
    public CuiType getCUI() {
        return cui;
    }

    /**
     * Sets the value of the cui property.
     * 
     * @param value
     *     allowed object is
     *     {@link CuiType }
     *     
     */
    public void setCUI(CuiType value) {
        this.cui = value;
    }

    /**
     * Gets the value of the scheda property.
     * 
     * @return
     *     possible object is
     *     {@link TipiSchedeType }
     *     
     */
    public TipiSchedeType getSCHEDA() {
        return scheda;
    }

    /**
     * Sets the value of the scheda property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipiSchedeType }
     *     
     */
    public void setSCHEDA(TipiSchedeType value) {
        this.scheda = value;
    }

    /**
     * Gets the value of the idschedasimog property.
     * 
     * @return
     *     possible object is
     *     {@link IdSchedaType }
     *     
     */
    public IdSchedaType getIDSCHEDASIMOG() {
        return idschedasimog;
    }

    /**
     * Sets the value of the idschedasimog property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdSchedaType }
     *     
     */
    public void setIDSCHEDASIMOG(IdSchedaType value) {
        this.idschedasimog = value;
    }

    /**
     * Gets the value of the idschedalocale property.
     * 
     * @return
     *     possible object is
     *     {@link IdSchedaType }
     *     
     */
    public IdSchedaType getIDSCHEDALOCALE() {
        return idschedalocale;
    }

    /**
     * Sets the value of the idschedalocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdSchedaType }
     *     
     */
    public void setIDSCHEDALOCALE(IdSchedaType value) {
        this.idschedalocale = value;
    }

}
