//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecMotivoVarType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecMotivoVarType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ID_MOTIVO_VAR" use="required" type="{xmlbeans.massload.simog.avlp.it}MotivoVarianteType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecMotivoVarType")
public class RecMotivoVarType {

    @XmlAttribute(name = "ID_MOTIVO_VAR", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected MotivoVarianteType idmotivovar;

    /**
     * Gets the value of the idmotivovar property.
     * 
     * @return
     *     possible object is
     *     {@link MotivoVarianteType }
     *     
     */
    public MotivoVarianteType getIDMOTIVOVAR() {
        return idmotivovar;
    }

    /**
     * Sets the value of the idmotivovar property.
     * 
     * @param value
     *     allowed object is
     *     {@link MotivoVarianteType }
     *     
     */
    public void setIDMOTIVOVAR(MotivoVarianteType value) {
        this.idmotivovar = value;
    }

}
