//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecVarAnagType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecVarAnagType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MOTIVO" type="{xmlbeans.massload.simog.avlp.it}MotiviVariazioneCOType"/>
 *         &lt;element name="Riferimento" type="{xmlbeans.massload.simog.avlp.it}RecIdSchedaElimType"/>
 *         &lt;element name="Responsabili" type="{xmlbeans.massload.simog.avlp.it}IncaricatoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Aggiudicatari" type="{xmlbeans.massload.simog.avlp.it}SoggAggiudicatarioType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DitteAusiliarie" type="{xmlbeans.massload.simog.avlp.it}DittaAusiliariaType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Posizioni" type="{xmlbeans.massload.simog.avlp.it}PosizioneType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecVarAnagType", propOrder = {
    "motivo",
    "riferimento",
    "responsabili",
    "aggiudicatari",
    "ditteAusiliarie",
    "posizioni"
})
public class RecVarAnagType {

    @XmlElement(name = "MOTIVO", required = true)
    protected MotiviVariazioneCOType motivo;
    @XmlElement(name = "Riferimento", required = true)
    protected RecIdSchedaElimType riferimento;
    @XmlElement(name = "Responsabili")
    protected List<IncaricatoType> responsabili;
    @XmlElement(name = "Aggiudicatari")
    protected List<SoggAggiudicatarioType> aggiudicatari;
    @XmlElement(name = "DitteAusiliarie")
    protected List<DittaAusiliariaType> ditteAusiliarie;
    @XmlElement(name = "Posizioni")
    protected List<PosizioneType> posizioni;

    /**
     * Gets the value of the motivo property.
     * 
     * @return
     *     possible object is
     *     {@link MotiviVariazioneCOType }
     *     
     */
    public MotiviVariazioneCOType getMOTIVO() {
        return motivo;
    }

    /**
     * Sets the value of the motivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MotiviVariazioneCOType }
     *     
     */
    public void setMOTIVO(MotiviVariazioneCOType value) {
        this.motivo = value;
    }

    /**
     * Gets the value of the riferimento property.
     * 
     * @return
     *     possible object is
     *     {@link RecIdSchedaElimType }
     *     
     */
    public RecIdSchedaElimType getRiferimento() {
        return riferimento;
    }

    /**
     * Sets the value of the riferimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecIdSchedaElimType }
     *     
     */
    public void setRiferimento(RecIdSchedaElimType value) {
        this.riferimento = value;
    }

    /**
     * Gets the value of the responsabili property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the responsabili property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponsabili().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncaricatoType }
     * 
     * 
     */
    public List<IncaricatoType> getResponsabili() {
        if (responsabili == null) {
            responsabili = new ArrayList<IncaricatoType>();
        }
        return this.responsabili;
    }

    /**
     * Gets the value of the aggiudicatari property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aggiudicatari property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAggiudicatari().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SoggAggiudicatarioType }
     * 
     * 
     */
    public List<SoggAggiudicatarioType> getAggiudicatari() {
        if (aggiudicatari == null) {
            aggiudicatari = new ArrayList<SoggAggiudicatarioType>();
        }
        return this.aggiudicatari;
    }

    /**
     * Gets the value of the ditteAusiliarie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ditteAusiliarie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDitteAusiliarie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DittaAusiliariaType }
     * 
     * 
     */
    public List<DittaAusiliariaType> getDitteAusiliarie() {
        if (ditteAusiliarie == null) {
            ditteAusiliarie = new ArrayList<DittaAusiliariaType>();
        }
        return this.ditteAusiliarie;
    }

    /**
     * Gets the value of the posizioni property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the posizioni property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPosizioni().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PosizioneType }
     * 
     * 
     */
    public List<PosizioneType> getPosizioni() {
        if (posizioni == null) {
            posizioni = new ArrayList<PosizioneType>();
        }
        return this.posizioni;
    }

}
