//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecVariazioneSAType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecVariazioneSAType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ID_GARA" use="required" type="{xmlbeans.massload.simog.avlp.it}LongType" />
 *       &lt;attribute name="MOTIVO" use="required" type="{xmlbeans.massload.simog.avlp.it}MotiviVariazioneSAType" />
 *       &lt;attribute name="CF_AMMINISTRAZIONE" use="required" type="{xmlbeans.massload.simog.avlp.it}CodFiscType" />
 *       &lt;attribute name="ID_CENTRO_COSTO" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="40"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecVariazioneSAType")
public class RecVariazioneSAType {

    @XmlAttribute(name = "ID_GARA", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected LongType idgara;
    @XmlAttribute(name = "MOTIVO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected MotiviVariazioneSAType motivo;
    @XmlAttribute(name = "CF_AMMINISTRAZIONE", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected CodFiscType cfamministrazione;
    @XmlAttribute(name = "ID_CENTRO_COSTO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected String idcentrocosto;

    /**
     * Gets the value of the idgara property.
     * 
     * @return
     *     possible object is
     *     {@link LongType }
     *     
     */
    public LongType getIDGARA() {
        return idgara;
    }

    /**
     * Sets the value of the idgara property.
     * 
     * @param value
     *     allowed object is
     *     {@link LongType }
     *     
     */
    public void setIDGARA(LongType value) {
        this.idgara = value;
    }

    /**
     * Gets the value of the motivo property.
     * 
     * @return
     *     possible object is
     *     {@link MotiviVariazioneSAType }
     *     
     */
    public MotiviVariazioneSAType getMOTIVO() {
        return motivo;
    }

    /**
     * Sets the value of the motivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MotiviVariazioneSAType }
     *     
     */
    public void setMOTIVO(MotiviVariazioneSAType value) {
        this.motivo = value;
    }

    /**
     * Gets the value of the cfamministrazione property.
     * 
     * @return
     *     possible object is
     *     {@link CodFiscType }
     *     
     */
    public CodFiscType getCFAMMINISTRAZIONE() {
        return cfamministrazione;
    }

    /**
     * Sets the value of the cfamministrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodFiscType }
     *     
     */
    public void setCFAMMINISTRAZIONE(CodFiscType value) {
        this.cfamministrazione = value;
    }

    /**
     * Gets the value of the idcentrocosto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDCENTROCOSTO() {
        return idcentrocosto;
    }

    /**
     * Sets the value of the idcentrocosto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDCENTROCOSTO(String value) {
        this.idcentrocosto = value;
    }

}
