//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequisitoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequisitoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ID_CATEGORIA" use="required" type="{xmlbeans.massload.simog.avlp.it}CategoriaType" />
 *       &lt;attribute name="CLASSE_IMPORTO" use="required" type="{xmlbeans.massload.simog.avlp.it}ClasseImportoType" />
 *       &lt;attribute name="PREVALENTE" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *       &lt;attribute name="SCORPORABILE" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *       &lt;attribute name="SUBAPPALTABILE" type="{xmlbeans.massload.simog.avlp.it}FlagSNType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequisitoType")
public class RequisitoType {

    @XmlAttribute(name = "ID_CATEGORIA", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected CategoriaType idcategoria;
    @XmlAttribute(name = "CLASSE_IMPORTO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected ClasseImportoType classeimporto;
    @XmlAttribute(name = "PREVALENTE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected FlagSNType prevalente;
    @XmlAttribute(name = "SCORPORABILE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected FlagSNType scorporabile;
    @XmlAttribute(name = "SUBAPPALTABILE", namespace = "xmlbeans.massload.simog.avlp.it")
    protected FlagSNType subappaltabile;

    /**
     * Gets the value of the idcategoria property.
     * 
     * @return
     *     possible object is
     *     {@link CategoriaType }
     *     
     */
    public CategoriaType getIDCATEGORIA() {
        return idcategoria;
    }

    /**
     * Sets the value of the idcategoria property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoriaType }
     *     
     */
    public void setIDCATEGORIA(CategoriaType value) {
        this.idcategoria = value;
    }

    /**
     * Gets the value of the classeimporto property.
     * 
     * @return
     *     possible object is
     *     {@link ClasseImportoType }
     *     
     */
    public ClasseImportoType getCLASSEIMPORTO() {
        return classeimporto;
    }

    /**
     * Sets the value of the classeimporto property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClasseImportoType }
     *     
     */
    public void setCLASSEIMPORTO(ClasseImportoType value) {
        this.classeimporto = value;
    }

    /**
     * Gets the value of the prevalente property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getPREVALENTE() {
        return prevalente;
    }

    /**
     * Sets the value of the prevalente property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setPREVALENTE(FlagSNType value) {
        this.prevalente = value;
    }

    /**
     * Gets the value of the scorporabile property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getSCORPORABILE() {
        return scorporabile;
    }

    /**
     * Sets the value of the scorporabile property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setSCORPORABILE(FlagSNType value) {
        this.scorporabile = value;
    }

    /**
     * Gets the value of the subappaltabile property.
     * 
     * @return
     *     possible object is
     *     {@link FlagSNType }
     *     
     */
    public FlagSNType getSUBAPPALTABILE() {
        return subappaltabile;
    }

    /**
     * Sets the value of the subappaltabile property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagSNType }
     *     
     */
    public void setSUBAPPALTABILE(FlagSNType value) {
        this.subappaltabile = value;
    }

}
