//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SchedaCompletaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SchedaCompletaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CUI" type="{xmlbeans.massload.simog.avlp.it}CuiType"/>
 *         &lt;element name="Aggiudicazione" type="{xmlbeans.massload.simog.avlp.it}AggiudicazioneType" minOccurs="0"/>
 *         &lt;element name="Sottosoglia" type="{xmlbeans.massload.simog.avlp.it}SchedaSottosogliaType" minOccurs="0"/>
 *         &lt;element name="Escluso" type="{xmlbeans.massload.simog.avlp.it}SchedaEsclusoType" minOccurs="0"/>
 *         &lt;element name="Adesione" type="{xmlbeans.massload.simog.avlp.it}AdesioneType" minOccurs="0"/>
 *         &lt;element name="DatiInizio" type="{xmlbeans.massload.simog.avlp.it}DatiInizioType" minOccurs="0"/>
 *         &lt;element name="DatiStipula" type="{xmlbeans.massload.simog.avlp.it}DatiStipulaType" minOccurs="0"/>
 *         &lt;element name="DatiAvanzamenti" type="{xmlbeans.massload.simog.avlp.it}AvanzamentiType" minOccurs="0"/>
 *         &lt;element name="DatiConclusione" type="{xmlbeans.massload.simog.avlp.it}ConclusioneType" minOccurs="0"/>
 *         &lt;element name="DatiCollaudo" type="{xmlbeans.massload.simog.avlp.it}DatiCollaudoType" minOccurs="0"/>
 *         &lt;element name="DatiRitardi" type="{xmlbeans.massload.simog.avlp.it}RitardiType" minOccurs="0"/>
 *         &lt;element name="DatiAccordi" type="{xmlbeans.massload.simog.avlp.it}AccordiBonariType" minOccurs="0"/>
 *         &lt;element name="DatiSospensioni" type="{xmlbeans.massload.simog.avlp.it}SospensioniType" minOccurs="0"/>
 *         &lt;element name="DatiVarianti" type="{xmlbeans.massload.simog.avlp.it}VariantiType" minOccurs="0"/>
 *         &lt;element name="DatiSubappalti" type="{xmlbeans.massload.simog.avlp.it}SubappaltiType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SchedaCompletaType", propOrder = {
    "cui",
    "aggiudicazione",
    "sottosoglia",
    "escluso",
    "adesione",
    "datiInizio",
    "datiStipula",
    "datiAvanzamenti",
    "datiConclusione",
    "datiCollaudo",
    "datiRitardi",
    "datiAccordi",
    "datiSospensioni",
    "datiVarianti",
    "datiSubappalti"
})
public class SchedaCompletaType {

    @XmlElement(name = "CUI", required = true)
    protected CuiType cui;
    @XmlElement(name = "Aggiudicazione")
    protected AggiudicazioneType aggiudicazione;
    @XmlElement(name = "Sottosoglia")
    protected SchedaSottosogliaType sottosoglia;
    @XmlElement(name = "Escluso")
    protected SchedaEsclusoType escluso;
    @XmlElement(name = "Adesione")
    protected AdesioneType adesione;
    @XmlElement(name = "DatiInizio")
    protected DatiInizioType datiInizio;
    @XmlElement(name = "DatiStipula")
    protected DatiStipulaType datiStipula;
    @XmlElement(name = "DatiAvanzamenti")
    protected AvanzamentiType datiAvanzamenti;
    @XmlElement(name = "DatiConclusione")
    protected ConclusioneType datiConclusione;
    @XmlElement(name = "DatiCollaudo")
    protected DatiCollaudoType datiCollaudo;
    @XmlElement(name = "DatiRitardi")
    protected RitardiType datiRitardi;
    @XmlElement(name = "DatiAccordi")
    protected AccordiBonariType datiAccordi;
    @XmlElement(name = "DatiSospensioni")
    protected SospensioniType datiSospensioni;
    @XmlElement(name = "DatiVarianti")
    protected VariantiType datiVarianti;
    @XmlElement(name = "DatiSubappalti")
    protected SubappaltiType datiSubappalti;

    /**
     * Gets the value of the cui property.
     * 
     * @return
     *     possible object is
     *     {@link CuiType }
     *     
     */
    public CuiType getCUI() {
        return cui;
    }

    /**
     * Sets the value of the cui property.
     * 
     * @param value
     *     allowed object is
     *     {@link CuiType }
     *     
     */
    public void setCUI(CuiType value) {
        this.cui = value;
    }

    /**
     * Gets the value of the aggiudicazione property.
     * 
     * @return
     *     possible object is
     *     {@link AggiudicazioneType }
     *     
     */
    public AggiudicazioneType getAggiudicazione() {
        return aggiudicazione;
    }

    /**
     * Sets the value of the aggiudicazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggiudicazioneType }
     *     
     */
    public void setAggiudicazione(AggiudicazioneType value) {
        this.aggiudicazione = value;
    }

    /**
     * Gets the value of the sottosoglia property.
     * 
     * @return
     *     possible object is
     *     {@link SchedaSottosogliaType }
     *     
     */
    public SchedaSottosogliaType getSottosoglia() {
        return sottosoglia;
    }

    /**
     * Sets the value of the sottosoglia property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchedaSottosogliaType }
     *     
     */
    public void setSottosoglia(SchedaSottosogliaType value) {
        this.sottosoglia = value;
    }

    /**
     * Gets the value of the escluso property.
     * 
     * @return
     *     possible object is
     *     {@link SchedaEsclusoType }
     *     
     */
    public SchedaEsclusoType getEscluso() {
        return escluso;
    }

    /**
     * Sets the value of the escluso property.
     * 
     * @param value
     *     allowed object is
     *     {@link SchedaEsclusoType }
     *     
     */
    public void setEscluso(SchedaEsclusoType value) {
        this.escluso = value;
    }

    /**
     * Gets the value of the adesione property.
     * 
     * @return
     *     possible object is
     *     {@link AdesioneType }
     *     
     */
    public AdesioneType getAdesione() {
        return adesione;
    }

    /**
     * Sets the value of the adesione property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdesioneType }
     *     
     */
    public void setAdesione(AdesioneType value) {
        this.adesione = value;
    }

    /**
     * Gets the value of the datiInizio property.
     * 
     * @return
     *     possible object is
     *     {@link DatiInizioType }
     *     
     */
    public DatiInizioType getDatiInizio() {
        return datiInizio;
    }

    /**
     * Sets the value of the datiInizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiInizioType }
     *     
     */
    public void setDatiInizio(DatiInizioType value) {
        this.datiInizio = value;
    }

    /**
     * Gets the value of the datiStipula property.
     * 
     * @return
     *     possible object is
     *     {@link DatiStipulaType }
     *     
     */
    public DatiStipulaType getDatiStipula() {
        return datiStipula;
    }

    /**
     * Sets the value of the datiStipula property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiStipulaType }
     *     
     */
    public void setDatiStipula(DatiStipulaType value) {
        this.datiStipula = value;
    }

    /**
     * Gets the value of the datiAvanzamenti property.
     * 
     * @return
     *     possible object is
     *     {@link AvanzamentiType }
     *     
     */
    public AvanzamentiType getDatiAvanzamenti() {
        return datiAvanzamenti;
    }

    /**
     * Sets the value of the datiAvanzamenti property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvanzamentiType }
     *     
     */
    public void setDatiAvanzamenti(AvanzamentiType value) {
        this.datiAvanzamenti = value;
    }

    /**
     * Gets the value of the datiConclusione property.
     * 
     * @return
     *     possible object is
     *     {@link ConclusioneType }
     *     
     */
    public ConclusioneType getDatiConclusione() {
        return datiConclusione;
    }

    /**
     * Sets the value of the datiConclusione property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConclusioneType }
     *     
     */
    public void setDatiConclusione(ConclusioneType value) {
        this.datiConclusione = value;
    }

    /**
     * Gets the value of the datiCollaudo property.
     * 
     * @return
     *     possible object is
     *     {@link DatiCollaudoType }
     *     
     */
    public DatiCollaudoType getDatiCollaudo() {
        return datiCollaudo;
    }

    /**
     * Sets the value of the datiCollaudo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiCollaudoType }
     *     
     */
    public void setDatiCollaudo(DatiCollaudoType value) {
        this.datiCollaudo = value;
    }

    /**
     * Gets the value of the datiRitardi property.
     * 
     * @return
     *     possible object is
     *     {@link RitardiType }
     *     
     */
    public RitardiType getDatiRitardi() {
        return datiRitardi;
    }

    /**
     * Sets the value of the datiRitardi property.
     * 
     * @param value
     *     allowed object is
     *     {@link RitardiType }
     *     
     */
    public void setDatiRitardi(RitardiType value) {
        this.datiRitardi = value;
    }

    /**
     * Gets the value of the datiAccordi property.
     * 
     * @return
     *     possible object is
     *     {@link AccordiBonariType }
     *     
     */
    public AccordiBonariType getDatiAccordi() {
        return datiAccordi;
    }

    /**
     * Sets the value of the datiAccordi property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccordiBonariType }
     *     
     */
    public void setDatiAccordi(AccordiBonariType value) {
        this.datiAccordi = value;
    }

    /**
     * Gets the value of the datiSospensioni property.
     * 
     * @return
     *     possible object is
     *     {@link SospensioniType }
     *     
     */
    public SospensioniType getDatiSospensioni() {
        return datiSospensioni;
    }

    /**
     * Sets the value of the datiSospensioni property.
     * 
     * @param value
     *     allowed object is
     *     {@link SospensioniType }
     *     
     */
    public void setDatiSospensioni(SospensioniType value) {
        this.datiSospensioni = value;
    }

    /**
     * Gets the value of the datiVarianti property.
     * 
     * @return
     *     possible object is
     *     {@link VariantiType }
     *     
     */
    public VariantiType getDatiVarianti() {
        return datiVarianti;
    }

    /**
     * Sets the value of the datiVarianti property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariantiType }
     *     
     */
    public void setDatiVarianti(VariantiType value) {
        this.datiVarianti = value;
    }

    /**
     * Gets the value of the datiSubappalti property.
     * 
     * @return
     *     possible object is
     *     {@link SubappaltiType }
     *     
     */
    public SubappaltiType getDatiSubappalti() {
        return datiSubappalti;
    }

    /**
     * Sets the value of the datiSubappalti property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubappaltiType }
     *     
     */
    public void setDatiSubappalti(SubappaltiType value) {
        this.datiSubappalti = value;
    }

}
