//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SchedaSottosogliaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SchedaSottosogliaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Appalto" type="{xmlbeans.massload.simog.avlp.it}SottoEsclusoType"/>
 *         &lt;element name="Condizioni" type="{xmlbeans.massload.simog.avlp.it}CondizioneType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Aggiudicatari" type="{xmlbeans.massload.simog.avlp.it}SoggAggiudicatarioType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Incaricati" type="{xmlbeans.massload.simog.avlp.it}IncaricatoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CUPLOTTO" type="{xmlbeans.massload.simog.avlp.it}CUPLOTTOType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SchedaSottosogliaType", propOrder = {
    "appalto",
    "condizioni",
    "aggiudicatari",
    "incaricati",
    "cuplotto"
})
public class SchedaSottosogliaType {

    @XmlElement(name = "Appalto", required = true)
    protected SottoEsclusoType appalto;
    @XmlElement(name = "Condizioni")
    protected List<CondizioneType> condizioni;
    @XmlElement(name = "Aggiudicatari")
    protected List<SoggAggiudicatarioType> aggiudicatari;
    @XmlElement(name = "Incaricati")
    protected List<IncaricatoType> incaricati;
    @XmlElement(name = "CUPLOTTO")
    protected CUPLOTTOType cuplotto;

    /**
     * Gets the value of the appalto property.
     * 
     * @return
     *     possible object is
     *     {@link SottoEsclusoType }
     *     
     */
    public SottoEsclusoType getAppalto() {
        return appalto;
    }

    /**
     * Sets the value of the appalto property.
     * 
     * @param value
     *     allowed object is
     *     {@link SottoEsclusoType }
     *     
     */
    public void setAppalto(SottoEsclusoType value) {
        this.appalto = value;
    }

    /**
     * Gets the value of the condizioni property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the condizioni property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCondizioni().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CondizioneType }
     * 
     * 
     */
    public List<CondizioneType> getCondizioni() {
        if (condizioni == null) {
            condizioni = new ArrayList<CondizioneType>();
        }
        return this.condizioni;
    }

    /**
     * Gets the value of the aggiudicatari property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aggiudicatari property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAggiudicatari().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SoggAggiudicatarioType }
     * 
     * 
     */
    public List<SoggAggiudicatarioType> getAggiudicatari() {
        if (aggiudicatari == null) {
            aggiudicatari = new ArrayList<SoggAggiudicatarioType>();
        }
        return this.aggiudicatari;
    }

    /**
     * Gets the value of the incaricati property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incaricati property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncaricati().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncaricatoType }
     * 
     * 
     */
    public List<IncaricatoType> getIncaricati() {
        if (incaricati == null) {
            incaricati = new ArrayList<IncaricatoType>();
        }
        return this.incaricati;
    }

    /**
     * Gets the value of the cuplotto property.
     * 
     * @return
     *     possible object is
     *     {@link CUPLOTTOType }
     *     
     */
    public CUPLOTTOType getCUPLOTTO() {
        return cuplotto;
    }

    /**
     * Sets the value of the cuplotto property.
     * 
     * @param value
     *     allowed object is
     *     {@link CUPLOTTOType }
     *     
     */
    public void setCUPLOTTO(CUPLOTTOType value) {
        this.cuplotto = value;
    }

}
