//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.16 at 04:20:40 PM CEST 
//


package it.avlp.simog.ws.massload.xmlbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SchedaGaraCig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SchedaGaraCig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Gara" type="{xmlbeans.massload.simog.avlp.it}GaraType"/>
 *         &lt;element name="CIG" type="{xmlbeans.massload.simog.avlp.it}CigType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SchedaGaraCig", propOrder = {
    "gara",
    "cig"
})

@XmlRootElement(name="SchedaGaraCig")
public class SchedaGaraCig {

    @XmlElement(name = "Gara", required = true)
    protected GaraType gara;
    @XmlElement(name = "CIG")
    protected List<CigType> cig;

    /**
     * Gets the value of the gara property.
     * 
     * @return
     *     possible object is
     *     {@link GaraType }
     *     
     */
    public GaraType getGara() {
        return gara;
    }

    /**
     * Sets the value of the gara property.
     * 
     * @param value
     *     allowed object is
     *     {@link GaraType }
     *     
     */
    public void setGara(GaraType value) {
        this.gara = value;
    }

    /**
     * Gets the value of the cig property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cig property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCIG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CigType }
     * 
     * 
     */
    public List<CigType> getCIG() {
        if (cig == null) {
            cig = new ArrayList<CigType>();
        }
        return this.cig;
    }

}
