//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.16 at 04:20:40 PM CEST 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SchedaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SchedaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatiGara" type="{xmlbeans.massload.simog.avlp.it}DatiGaraType"/>
 *         &lt;element name="DatiScheda" type="{xmlbeans.massload.simog.avlp.it}DatiAggiudicazioneType" minOccurs="0"/>
 *         &lt;element name="Responsabili" type="{xmlbeans.massload.simog.avlp.it}ResponsabiliType" minOccurs="0"/>
 *         &lt;element name="Aggiudicatari" type="{xmlbeans.massload.simog.avlp.it}AggiudicatariType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SchedaType", propOrder = {
    "datiGara",
    "datiScheda",
    "responsabili",
    "aggiudicatari"
})

@XmlRootElement(name="Scheda")
public class SchedaType {

    @XmlElement(name = "DatiGara", required = true)
    protected DatiGaraType datiGara;
    @XmlElement(name = "DatiScheda")
    protected DatiAggiudicazioneType datiScheda;
    @XmlElement(name = "Responsabili")
    protected ResponsabiliType responsabili;
    @XmlElement(name = "Aggiudicatari")
    protected AggiudicatariType aggiudicatari;

    /**
     * Gets the value of the datiGara property.
     * 
     * @return
     *     possible object is
     *     {@link DatiGaraType }
     *     
     */
    public DatiGaraType getDatiGara() {
        return datiGara;
    }

    /**
     * Sets the value of the datiGara property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiGaraType }
     *     
     */
    public void setDatiGara(DatiGaraType value) {
        this.datiGara = value;
    }

    /**
     * Gets the value of the datiScheda property.
     * 
     * @return
     *     possible object is
     *     {@link DatiAggiudicazioneType }
     *     
     */
    public DatiAggiudicazioneType getDatiScheda() {
        return datiScheda;
    }

    /**
     * Sets the value of the datiScheda property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiAggiudicazioneType }
     *     
     */
    public void setDatiScheda(DatiAggiudicazioneType value) {
        this.datiScheda = value;
    }

    /**
     * Gets the value of the responsabili property.
     * 
     * @return
     *     possible object is
     *     {@link ResponsabiliType }
     *     
     */
    public ResponsabiliType getResponsabili() {
        return responsabili;
    }

    /**
     * Sets the value of the responsabili property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponsabiliType }
     *     
     */
    public void setResponsabili(ResponsabiliType value) {
        this.responsabili = value;
    }

    /**
     * Gets the value of the aggiudicatari property.
     * 
     * @return
     *     possible object is
     *     {@link AggiudicatariType }
     *     
     */
    public AggiudicatariType getAggiudicatari() {
        return aggiudicatari;
    }

    /**
     * Sets the value of the aggiudicatari property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggiudicatariType }
     *     
     */
    public void setAggiudicatari(AggiudicatariType value) {
        this.aggiudicatari = value;
    }

}
