//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TipiAppaltoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TipiAppaltoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ID_APPALTO" use="required" type="{xmlbeans.massload.simog.avlp.it}TipoAppaltoType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TipiAppaltoType")
public class TipiAppaltoType {

    @XmlAttribute(name = "ID_APPALTO", namespace = "xmlbeans.massload.simog.avlp.it", required = true)
    protected TipoAppaltoType idappalto;

    /**
     * Gets the value of the idappalto property.
     * 
     * @return
     *     possible object is
     *     {@link TipoAppaltoType }
     *     
     */
    public TipoAppaltoType getIDAPPALTO() {
        return idappalto;
    }

    /**
     * Sets the value of the idappalto property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipoAppaltoType }
     *     
     */
    public void setIDAPPALTO(TipoAppaltoType value) {
        this.idappalto = value;
    }

}
