//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.09 at 04:35:21 PM CET 
//


package it.avlp.simog.ws.massload.xmlbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InfoTrasferimento" type="{xmlbeans.massload.simog.avlp.it}TrasferimentoType"/>
 *         &lt;element name="Schede" type="{xmlbeans.massload.simog.avlp.it}DatiAggiudicazioneType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SchedeEliminate" type="{xmlbeans.massload.simog.avlp.it}RecIdSchedaElimType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="VariazioniAnag" type="{xmlbeans.massload.simog.avlp.it}VarAnagType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Responsabili" type="{xmlbeans.massload.simog.avlp.it}ResponsabiliType" minOccurs="0"/>
 *         &lt;element name="Aggiudicatari" type="{xmlbeans.massload.simog.avlp.it}AggiudicatariType" minOccurs="0"/>
 *         &lt;element name="VariazioniSA" type="{xmlbeans.massload.simog.avlp.it}VariazioneSAType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "infoTrasferimento",
    "schede",
    "schedeEliminate",
    "variazioniAnag",
    "responsabili",
    "aggiudicatari",
    "variazioniSA"
})
@XmlRootElement(name = "TrasferimentoDati")
public class TrasferimentoDati {

    @XmlElement(name = "InfoTrasferimento", required = true)
    protected TrasferimentoType infoTrasferimento;
    @XmlElement(name = "Schede")
    protected List<DatiAggiudicazioneType> schede;
    @XmlElement(name = "SchedeEliminate")
    protected List<RecIdSchedaElimType> schedeEliminate;
    @XmlElement(name = "VariazioniAnag")
    protected List<VarAnagType> variazioniAnag;
    @XmlElement(name = "Responsabili")
    protected ResponsabiliType responsabili;
    @XmlElement(name = "Aggiudicatari")
    protected AggiudicatariType aggiudicatari;
    @XmlElement(name = "VariazioniSA")
    protected VariazioneSAType variazioniSA;

    /**
     * Gets the value of the infoTrasferimento property.
     * 
     * @return
     *     possible object is
     *     {@link TrasferimentoType }
     *     
     */
    public TrasferimentoType getInfoTrasferimento() {
        return infoTrasferimento;
    }

    /**
     * Sets the value of the infoTrasferimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrasferimentoType }
     *     
     */
    public void setInfoTrasferimento(TrasferimentoType value) {
        this.infoTrasferimento = value;
    }

    /**
     * Gets the value of the schede property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the schede property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSchede().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatiAggiudicazioneType }
     * 
     * 
     */
    public List<DatiAggiudicazioneType> getSchede() {
        if (schede == null) {
            schede = new ArrayList<DatiAggiudicazioneType>();
        }
        return this.schede;
    }

    /**
     * Gets the value of the schedeEliminate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the schedeEliminate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSchedeEliminate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RecIdSchedaElimType }
     * 
     * 
     */
    public List<RecIdSchedaElimType> getSchedeEliminate() {
        if (schedeEliminate == null) {
            schedeEliminate = new ArrayList<RecIdSchedaElimType>();
        }
        return this.schedeEliminate;
    }

    /**
     * Gets the value of the variazioniAnag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the variazioniAnag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVariazioniAnag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VarAnagType }
     * 
     * 
     */
    public List<VarAnagType> getVariazioniAnag() {
        if (variazioniAnag == null) {
            variazioniAnag = new ArrayList<VarAnagType>();
        }
        return this.variazioniAnag;
    }

    /**
     * Gets the value of the responsabili property.
     * 
     * @return
     *     possible object is
     *     {@link ResponsabiliType }
     *     
     */
    public ResponsabiliType getResponsabili() {
        return responsabili;
    }

    /**
     * Sets the value of the responsabili property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponsabiliType }
     *     
     */
    public void setResponsabili(ResponsabiliType value) {
        this.responsabili = value;
    }

    /**
     * Gets the value of the aggiudicatari property.
     * 
     * @return
     *     possible object is
     *     {@link AggiudicatariType }
     *     
     */
    public AggiudicatariType getAggiudicatari() {
        return aggiudicatari;
    }

    /**
     * Sets the value of the aggiudicatari property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggiudicatariType }
     *     
     */
    public void setAggiudicatari(AggiudicatariType value) {
        this.aggiudicatari = value;
    }

    /**
     * Gets the value of the variazioniSA property.
     * 
     * @return
     *     possible object is
     *     {@link VariazioneSAType }
     *     
     */
    public VariazioneSAType getVariazioniSA() {
        return variazioniSA;
    }

    /**
     * Sets the value of the variazioniSA property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariazioneSAType }
     *     
     */
    public void setVariazioniSA(VariazioneSAType value) {
        this.variazioniSA = value;
    }

}
