server.port=8081

#MONGODB CONNECTION
#spring.data.mongodb.uri=mongodb://f.trinca:PreMongo_Kj8GtQ@premongo1.premaster.local:27017/APPALTI?authSource=admin
spring.data.mongodb.uri=mongodb://10.119.26.72:27017/APPALTI?authSource=admin