<%@ taglib prefix="utils" uri="http://simog.avlp.it/tags-util"  %>
<div id="footer">
	<div class="numeroVerde"><utils:message key="footer.contactCenter" /> <font title="Build @BUILD@ del @DATE@">SIMOG</font> - AVCP - 800 896 936</div>
	
	<utils:message key="footer.supportoSimog" /> - <a href="mailto:assistenza.simog@avcp.it?subject=Richiesta Supporto SIMOG"><utils:message key="footer.assistenzaSimog" /></a>
	<br/> (<utils:message key="footer.includereRiferimenti" />) 
	<br><br> <utils:message key="footer.sitoOttimizzato" /> 
	
</div>