<div id="navigation">
	<ul>
		<li id="activelink"><a href="loadBloccoDati?pagina=include/aggiudicazioni.inc">Aggiudicazione</a></li>
		<li><a href="loadBloccoDati?pagina=include/pubblicazioneEsito.inc">Pubblicazione Esito</a></li>
		<li><a href="loadBloccoDati?pagina=include/responsabileProcedimento.inc">Responsabile del procedimento</a></li>					    
   		<li><a href="loadBloccoDati?pagina=include/massimoRibasso.inc">Massimo Ribasso</a></li>
		<li><a href="loadBloccoDati?pagina=include/contenzioso.inc">Contenzioso</a></li>
		<li><a href="loadBloccoDati?pagina=include/affidatario.inc">Aggiudicatario</a></li>
		<li><a href="loadBloccoDati?pagina=include/contratti.inc">Contratto</a></li>
		<li><a href="loadBloccoDati?pagina=include/finanziamenti.inc">Finanziamenti</a></li>
	</ul>
</div>
<fieldset>
					
</fieldset> 