</div>
	<!-- FOOTER -->
	<div id="footer">
		<div class="PORTLET-FRAGMENT"  style="width: null;height: null;">
		<!--############################ FOOTER ######################################--> 
				<div title="Versione 3.04.6.1 (849) del 08-07-2021 12:00:21" id="testo_footer">
				<p>&copy; Autorit&agrave; Nazionale Anticorruzione - Tutti i diritti riservati</p> 
				<p>via M. Minghetti, 10 - 00187 Roma - c.f. 97584460584</p> 
				<p>Contact Center: 800896936</p>
			</div>
		</div> 
	</div>
	<!-- /FOOTER -->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-9618615-5']);
  _gaq.push(['_setDomainName', 'anticorruzione.it']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>