				<h5>Stazione Appaltante</h5>
				<div class="elenco">
				<div class="gara">
					<table>
						<tr>
							<th class="garaTh" width="40%"><label for="sa_riferimento">SA Riferimento</label></th>
							<TD class="garaTd" colspan="3"><%= saRiferimentoInclude %></TD>
						</tr>
						<tr>
							<th class="garaTh" width="40%"><label for="cf_sa">Codice Fiscale Stazione Appaltante</label></th>
							<TD class="garaTd" colspan="3"><%= CFSAInclude %></TD>
						</tr>
						<tr>
							<th class="garaTh" width="40%"><label for="cf_sa">RSSA che ha creato la Gara</label></th>
							<TD class="garaTd" colspan="3"><%= RSSACreatoreInclude %></TD>
						</tr>
					</table>
				</div>