package it.avlp.simog.error;

//import it.avlp.simog.ws.commons.LoggerManager;

import java.util.TreeMap;

//import org.apache.log4j.Logger;

	/**
	 * Classe per la gestione degli errori
	 * dato un codice in ingresso restituisce il
	 * messaggio associato (su richiesta) altrimenti
	 * rimane memorizzato in locale
	 * 
	 * **/

public class ErrorManager {
	
	// definizione delle costanti relative ai messaggi WS
	public final static String SIMOGWS_CIGMANAGER_NULL_01 = "SIMOGWS_CIGMANAGER_NULL_01"; 
	public final static String SIMOGWS_CIGMANAGER_NULL_02 = "SIMOGWS_CIGMANAGER_NULL_02"; 
	public final static String SIMOGWS_CIGMANAGER_SIMOGCOMMON_03 = "SIMOGWS_CIGMANAGER_SIMOGCOMMON_03"; 
	
	public final static String SIMOGWS_COLLABORAZIONIMANAGER_NULL_01 = "SIMOGWS_COLLABORAZIONIMANAGER_NULL_01"; 
	
	public final static String SIMOGWS_EXTERNALMANAGER_NULL_01 = "SIMOGWS_EXTERNALMANAGER_NULL_01"; 
	public final static String SIMOGWS_EXTERNALMANAGER_NULL_02 = "SIMOGWS_EXTERNALMANAGER_NULL_02"; 
	public final static String SIMOGWS_EXTERNALMANAGER_IO_03 = "SIMOGWS_EXTERNALMANAGER_IO_03"; 
	public final static String SIMOGWS_EXTERNALMANAGER_REMOTE_04 = "SIMOGWS_EXTERNALMANAGER_REMOTE_04"; 
	public final static String SIMOGWS_EXTERNALMANAGER_NULL_05 = "SIMOGWS_EXTERNALMANAGER_NULL_05"; 
	
	public final static String SIMOGWS_XMLMANAGER_XML_01 = "SIMOGWS_XMLMANAGER_XML_01"; 
	public final static String SIMOGWS_XMLMANAGER_XML_02 = "SIMOGWS_XMLMANAGER_XML_02"; 
	public final static String SIMOGWS_XMLMANAGER_NULL_03 = "SIMOGWS_XMLMANAGER_NULL_03"; 
	public final static String SIMOGWS_XMLMANAGER_XML_04 = "SIMOGWS_XMLMANAGER_XML_04"; 
	public final static String SIMOGWS_XMLMANAGER_STRING_05 = "SIMOGWS_XMLMANAGER_STRING_05"; 
	
	public final static String SIMOGWS_CONNECTIONWSMANAGER_NULL_01 = "SIMOGWS_CONNECTIONWSMANAGER_NULL_01"; 
	public final static String SIMOGWS_CONNECTIONWSMANAGER_SQL_02 = "SIMOGWS_CONNECTIONWSMANAGER_SQL_02"; 
	public final static String SIMOGWS_CONNECTIONWSMANAGER_SQL_03 = "SIMOGWS_CONNECTIONWSMANAGER_SQL_03"; 
	public final static String SIMOGWS_CONNECTIONWSMANAGER_SQL_04 = "SIMOGWS_CONNECTIONWSMANAGER_SQL_04"; 
	public final static String SIMOGWS_CONNECTIONWSMANAGER_CLASSNOTFOUND_05 = "SIMOGWS_CONNECTIONWSMANAGER_CLASSNOTFOUND_05"; 
	public final static String SIMOGWS_CONNECTIONWSMANAGER_SQL_06 = "SIMOGWS_CONNECTIONWSMANAGER_SQL_06"; 
	public final static String SIMOGWS_CONNECTIONWSMANAGER_SQL_07 = "SIMOGWS_CONNECTIONWSMANAGER_SQL_07"; 
	
	public final static String SIMOGWS_WSSMANAGER_SQL_01 = "SIMOGWS_WSSMANAGER_SQL_01"; 
	public final static String SIMOGWS_WSSMANAGER_SQL_02 = "SIMOGWS_WSSMANAGER_SQL_02"; 
	public final static String SIMOGWS_WSSMANAGER_NULL_03 = "SIMOGWS_WSSMANAGER_NULL_03"; 
	public final static String SIMOGWS_WSSMANAGER_SQL_04 = "SIMOGWS_WSSMANAGER_SQL_04"; 
	public final static String SIMOGWS_WSSMANAGER_SQL_05 = "SIMOGWS_WSSMANAGER_SQL_05"; 
	public final static String SIMOGWS_WSSMANAGER_SQL_06 = "SIMOGWS_WSSMANAGER_SQL_06"; 
	public final static String SIMOGWS_WSSMANAGER_NULL_07 = "SIMOGWS_WSSMANAGER_NULL_07"; 
	public final static String SIMOGWS_WSSMANAGER_SQL_08 = "SIMOGWS_WSSMANAGER_SQL_08"; 
	public final static String SIMOGWS_WSSMANAGER_NULL_09 = "SIMOGWS_WSSMANAGER_NULL_09"; 
	public final static String SIMOGWS_WSSMANAGER_SQL_10 = "SIMOGWS_WSSMANAGER_SQL_10"; 
	public final static String SIMOGWS_WSSMANAGER_NULL_11 = "SIMOGWS_WSSMANAGER_NULL_11"; 
	public final static String SIMOGWS_WSSMANAGER_SQL_12 = "SIMOGWS_WSSMANAGER_SQL_12"; 
	public final static String SIMOGWS_WSSMANAGER_NULL_13 = "SIMOGWS_WSSMANAGER_NULL_13"; 
	public final static String SIMOGWS_WSSMANAGER_SQL_14 = "SIMOGWS_WSSMANAGER_SQL_14"; 
	public final static String SIMOGWS_WSSMANAGER_NULL_15 = "SIMOGWS_WSSMANAGER_NULL_15"; 
	public final static String SIMOGWS_WSSMANAGER_NULL_16 = "SIMOGWS_WSSMANAGER_NULL_16"; 
	public final static String SIMOGWS_WSSMANAGER_SQL_17 = "SIMOGWS_WSSMANAGER_SQL_17"; 
	public final static String SIMOGWS_WSSMANAGER_APP_18 = "SIMOGWS_WSSMANAGER_APP_18"; 
	public final static String SIMOGWS_WSSMANAGER_APP_19 = "SIMOGWS_WSSMANAGER_APP_19";
	
	public final static String SIMOGWS_GARAXMLMANAGER_NULL_01 = "SIMOGWS_GARAXMLMANAGER_NULL_01" ;
	public final static String SIMOGWS_GARAXMLMANAGER_NULL_02 = "SIMOGWS_GARAXMLMANAGER_NULL_02" ;
	public final static String SIMOGWS_GARAXMLMANAGER_APP_03 = "SIMOGWS_GARAXMLMANAGER_APP_03" ;
	
	public final static String SIMOGWS_TICKETMANAGER_SHA_01 = "SIMOGWS_TICKETMANAGER_SHA_01" ;
	public final static String SIMOGWS_TICKETMANAGER_APP_02 = "SIMOGWS_TICKETMANAGER_APP_02" ;
	public final static String SIMOGWS_TICKETMANAGER_NULL_03 = "SIMOGWS_TICKETMANAGER_NULL_03" ;
	public final static String SIMOGWS_TICKETMANAGER_NULL_04 = "SIMOGWS_TICKETMANAGER_NULL_04" ;
	
	public final static String SIMOGWS_XMLBEANMANAGER_APP_01 = "SIMOGWS_XMLBEANMANAGER_APP_01" ;
	public final static String SIMOGWS_XMLBEANMANAGER_APP_02 = "SIMOGWS_XMLBEANMANAGER_APP_02" ;

	public final static String SIMOGWS_XMLBEANMANAGER_APP_03 = "SIMOGWS_XMLBEANMANAGER_APP_03" ;
	public final static String SIMOGWS_XMLBEANMANAGER_APP_04 = "SIMOGWS_XMLBEANMANAGER_APP_04" ;
	public final static String SIMOGWS_XMLBEANMANAGER_APP_05 = "SIMOGWS_XMLBEANMANAGER_APP_05" ;
	public final static String SIMOGWS_XMLBEANMANAGER_APP_06 = "SIMOGWS_XMLBEANMANAGER_APP_06" ;
	public final static String SIMOGWS_XMLBEANMANAGER_APP_07 = "SIMOGWS_XMLBEANMANAGER_APP_07" ;
	public final static String SIMOGWS_XMLBEANMANAGER_APP_08 = "SIMOGWS_XMLBEANMANAGER_APP_08" ;
	public final static String SIMOGWS_XMLBEANMANAGER_APP_09 = "SIMOGWS_XMLBEANMANAGER_APP_09" ;
	public final static String SIMOGWS_XMLBEANMANAGER_APP_10 = "SIMOGWS_XMLBEANMANAGER_APP_10" ;
	public final static String SIMOGWS_XMLBEANMANAGER_APP_11 = "SIMOGWS_XMLBEANMANAGER_APP_11" ;

	public final static String SIMOGWS_CONFIGURATIONMANAGER_APP_01 = "SIMOGWS_CONFIGURATIONMANAGER_APP_01" ;
	public final static String SIMOGWS_CONFIGURATIONMANAGER_APP_02 = "SIMOGWS_CONFIGURATIONMANAGER_APP_02" ;

	public final static String SIMOGWS_ACTIONS_APP_01 = "SIMOGWS_ACTIONS_APP_01" ;
	public final static String SIMOGWS_ACTIONS_APP_02 = "SIMOGWS_ACTIONS_APP_02" ;
	//TICKET ALM - 3.04.3
	public final static String SIMOGWS_ACTIONS_APP_03 = "SIMOGWS_ACTIONS_APP_03" ;
	public final static String SIMOGWS_ACTIONS_APP_04 = "SIMOGWS_ACTIONS_APP_04" ;
	public final static String SIMOGWS_ACTIONS_APP_05 = "SIMOGWS_ACTIONS_APP_05" ;
	public final static String SIMOGWS_ACTIONS_APP_06 = "SIMOGWS_ACTIONS_APP_06" ;
	
	public final static String SIMOGWS_UNDEFINEND_ERR_01 = "SIMOGWS_UNDEFINEND_ERR_01" ;
	
	public final static String SIMOGWS_SQLTOOLS_ERR_01 = "SIMOGWS_SQLTOOLS_ERR_01" ;
	public final static String SIMOGWS_SQLTOOLS_ERR_02 = "SIMOGWS_SQLTOOLS_ERR_02" ;

	public final static String SIMOGWS_GARALOTTOMANAGER_SQL_01 = "SIMOGWS_GARALOTTOMANAGER_SQL_01" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_02 = "SIMOGWS_GARALOTTOMANAGER_APP_02" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_03 = "SIMOGWS_GARALOTTOMANAGER_APP_03" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_04 = "SIMOGWS_GARALOTTOMANAGER_APP_04" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_05 = "SIMOGWS_GARALOTTOMANAGER_APP_05" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_06 = "SIMOGWS_GARALOTTOMANAGER_APP_06" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_07 = "SIMOGWS_GARALOTTOMANAGER_APP_07" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_08 = "SIMOGWS_GARALOTTOMANAGER_APP_08" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_09 = "SIMOGWS_GARALOTTOMANAGER_APP_09" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_10 = "SIMOGWS_GARALOTTOMANAGER_APP_10" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_11 = "SIMOGWS_GARALOTTOMANAGER_APP_11" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_12 = "SIMOGWS_GARALOTTOMANAGER_APP_12" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_13 = "SIMOGWS_GARALOTTOMANAGER_APP_13" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_14 = "SIMOGWS_GARALOTTOMANAGER_APP_14" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_15 = "SIMOGWS_GARALOTTOMANAGER_APP_15" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_16 = "SIMOGWS_GARALOTTOMANAGER_APP_16" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_17 = "SIMOGWS_GARALOTTOMANAGER_APP_17" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_18 = "SIMOGWS_GARALOTTOMANAGER_APP_18" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_19 = "SIMOGWS_GARALOTTOMANAGER_APP_19" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_20 = "SIMOGWS_GARALOTTOMANAGER_APP_20" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_21 = "SIMOGWS_GARALOTTOMANAGER_APP_21" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_22 = "SIMOGWS_GARALOTTOMANAGER_APP_22" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_23 = "SIMOGWS_GARALOTTOMANAGER_APP_23" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_SQL_24 = "SIMOGWS_GARALOTTOMANAGER_SQL_24" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_25 = "SIMOGWS_GARALOTTOMANAGER_APP_25" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_26 = "SIMOGWS_GARALOTTOMANAGER_APP_26" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_27 = "SIMOGWS_GARALOTTOMANAGER_APP_27" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_28 = "SIMOGWS_GARALOTTOMANAGER_APP_28" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_29 = "SIMOGWS_GARALOTTOMANAGER_APP_29" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_30 = "SIMOGWS_GARALOTTOMANAGER_APP_30" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_31 = "SIMOGWS_GARALOTTOMANAGER_APP_31" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_32 = "SIMOGWS_GARALOTTOMANAGER_APP_32" ;

	public final static String SIMOGWS_GARALOTTOMANAGER_APP_33 = "SIMOGWS_GARALOTTOMANAGER_APP_33" ;
	public final static String SIMOGWS_GARALOTTOMANAGER_APP_34 = "SIMOGWS_GARALOTTOMANAGER_APP_34" ;

	public final static String SIMOGWS_PUBBLICAZIONE_APP_35 = "SIMOGWS_PUBBLICAZIONE_APP_35" ;
	public final static String SIMOGWS_PUBBLICAZIONE_APP_36 = "SIMOGWS_PUBBLICAZIONE_APP_36" ;

	public final static String SIMOGWS_GARALOTTOMANAGER_APP_37 = "SIMOGWS_GARALOTTOMANAGER_APP_37" ;
   public final static String SIMOGWS_GARALOTTOMANAGER_APP_38 = "SIMOGWS_GARALOTTOMANAGER_APP_38" ;
   
   // INT87
   public final static String SIMOGWS_GARALOTTOMANAGER_APP_39 = "SIMOGWS_GARALOTTOMANAGER_APP_39" ;
   
   //MAC #3525 (3.04.2)
   public final static String SIMOGWS_GARALOTTOMANAGER_APP_40 = "SIMOGWS_GARALOTTOMANAGER_APP_40";
   
   // MAC #10525 (3.04.3.1)
   public final static String SIMOGWS_GARALOTTOMANAGER_APP_41 = "SIMOGWS_GARALOTTOMANAGER_APP_41";
   
	private TreeMap<String,String> ErrorList = null;
	private String errore = null;
	//private Logger logger = null;
	
	/**
	 * Costruttore
	 * @param codiceErrore String 
	 */
	public ErrorManager(String codiceErrore){
		//this.logger = logger;
		ErrorList = new TreeMap<String,String>();
		this.populateErrors();
		this.errore = this.translateError(codiceErrore);
	}
	
	/**
	 * Restituisce la stringa associata ad un determinato codice errore
	 * 
	 * @param codiceErrore String
	 * @return String
	 */
	private String translateError(String codiceErrore){
		//logger.debug("eseguendo: String translateError("+codiceErrore+")");
		try {
         return (String)ErrorList.get(codiceErrore);
      } catch (Exception e) {
         return (codiceErrore);
      }
	}
	
	/**
	 * Restituisce la stringa di errore
	 * @return String 
	 */
	public String getError(){
		//logger.debug("eseguendo: String getError()");
		return this.errore ;
	}
	
	/**
	 * Il metodo si occupa di popolare la lista degli errori
	 */
	private void populateErrors(){
		//---------CIG MANAGER------------
		ErrorList.put(SIMOGWS_CIGMANAGER_NULL_01,SIMOGWS_CIGMANAGER_NULL_01 + " - CIG RITORNATO DA SIMOG COMMON NULLO");
		ErrorList.put(SIMOGWS_CIGMANAGER_NULL_02,SIMOGWS_CIGMANAGER_NULL_02 + " - CONNESSIONE PASSATA A CIG MANAGER NULLA");
		ErrorList.put(SIMOGWS_CIGMANAGER_SIMOGCOMMON_03,SIMOGWS_CIGMANAGER_SIMOGCOMMON_03 + " - PROBLEMA SOLLEVATO DA SIMOG COMMON");
		//-----------COLLABORAZIONI MANAGER--------------
		ErrorList.put(SIMOGWS_COLLABORAZIONIMANAGER_NULL_01 ,SIMOGWS_COLLABORAZIONIMANAGER_NULL_01 + " - OGGETTO PASSATO A COLLABORAZIONIMANAGER NULLO");
		//----------EXTERNALMANAGER-----
		ErrorList.put(SIMOGWS_EXTERNALMANAGER_NULL_01,SIMOGWS_EXTERNALMANAGER_NULL_01 + "- LA STRINGA XML RISULTA NULLA O VUOTA");	
		ErrorList.put(SIMOGWS_EXTERNALMANAGER_NULL_02,SIMOGWS_EXTERNALMANAGER_NULL_02 + " - XMLBEAN RISULTA NULLO");	
		ErrorList.put(SIMOGWS_EXTERNALMANAGER_IO_03,SIMOGWS_EXTERNALMANAGER_IO_03 + " - ERRORE TEST CON LETTURA XML LOCALE");
		ErrorList.put(SIMOGWS_EXTERNALMANAGER_REMOTE_04,SIMOGWS_EXTERNALMANAGER_REMOTE_04 + " - PROBLEMA CON IL WEB SERVICE REMOTO AVCP");
		ErrorList.put(SIMOGWS_EXTERNALMANAGER_NULL_05,SIMOGWS_EXTERNALMANAGER_NULL_05 +" - L'XML RESTITUITO DAL WS REMOTO RISULTA NULLO O VUOTO");
		//----------XMLMANAGER----------------
		ErrorList.put(SIMOGWS_XMLMANAGER_XML_01,SIMOGWS_XMLMANAGER_XML_01 + " - ERRORE/I NELLA VALIDAZIONE DELL'XML");
		ErrorList.put(SIMOGWS_XMLMANAGER_XML_02,SIMOGWS_XMLMANAGER_XML_02 + " - ECCEZIONE NELLA VALIDAZIONE DELL'XML");
		ErrorList.put(SIMOGWS_XMLMANAGER_NULL_03,SIMOGWS_XMLMANAGER_NULL_03 + " - STRINGA XML PASSATA RISULTA NULLA");
		ErrorList.put(SIMOGWS_XMLMANAGER_XML_04,SIMOGWS_XMLMANAGER_XML_04 + " - XMLBEAN RISULTA NULLO");
		ErrorList.put(SIMOGWS_XMLMANAGER_STRING_05,SIMOGWS_XMLMANAGER_STRING_05 + " - ECCEZIONE FORMATTANDO LA STRINGA CHE RAPPRESENTA IL FILE XML");
		//----------CONNECTIONWSMANAGER--------
		ErrorList.put(SIMOGWS_CONNECTIONWSMANAGER_NULL_01,SIMOGWS_CONNECTIONWSMANAGER_NULL_01 + " - CONNESSIONE CHE SI CERCA DI RECUPERARE NULLA");
		ErrorList.put(SIMOGWS_CONNECTIONWSMANAGER_SQL_02,SIMOGWS_CONNECTIONWSMANAGER_SQL_02 + " - PROBLEMA SETTANDO IL LIVELLO DI ISOLAMENTO DELLA CONNESSIONE");
		ErrorList.put(SIMOGWS_CONNECTIONWSMANAGER_SQL_03,SIMOGWS_CONNECTIONWSMANAGER_SQL_03 + " - PROBLEMA CREANDO UNA NUOVA CONNESSIONE");
		ErrorList.put(SIMOGWS_CONNECTIONWSMANAGER_SQL_04, SIMOGWS_CONNECTIONWSMANAGER_SQL_04 + " - PROBLEMA NEL RECUPERARE IL DATASOURCE");
		ErrorList.put(SIMOGWS_CONNECTIONWSMANAGER_CLASSNOTFOUND_05,SIMOGWS_CONNECTIONWSMANAGER_CLASSNOTFOUND_05 + " - PROBLEMA NEL TROVARE IL DRIVER");
		ErrorList.put(SIMOGWS_CONNECTIONWSMANAGER_SQL_06,SIMOGWS_CONNECTIONWSMANAGER_SQL_06 + " - PROBLEMA NEL RECUPERARE IL LIVELLO DI ISOLAMENTO DELLA CONNESSIONE");
		ErrorList.put(SIMOGWS_CONNECTIONWSMANAGER_SQL_07,SIMOGWS_CONNECTIONWSMANAGER_SQL_07 + " - IL DB NON RISULTA DISPONIBILE");
		//-----------WSSMANAGER--------------
		ErrorList.put(SIMOGWS_WSSMANAGER_SQL_01,SIMOGWS_WSSMANAGER_SQL_01 + " - PROBLEMA NEL RECUPERARE I DATI DI UNA SESSIONE");
		ErrorList.put(SIMOGWS_WSSMANAGER_SQL_02,SIMOGWS_WSSMANAGER_SQL_02 + " - PROBLEMA NEL CAMBIARE LO STATO DI UNA SESSIONE SCADUTA O NON VALIDA A \"ENDED\"");
		ErrorList.put(SIMOGWS_WSSMANAGER_NULL_03,SIMOGWS_WSSMANAGER_NULL_03 + " - LA CONNESSIONE RISULTA NULLA");
		ErrorList.put(SIMOGWS_WSSMANAGER_SQL_04,SIMOGWS_WSSMANAGER_SQL_04 + " - PROBELMA NELL'INSERMENTO DI UNA NUOVA SESSIONE");
		ErrorList.put(SIMOGWS_WSSMANAGER_SQL_05,SIMOGWS_WSSMANAGER_SQL_05 + " - PROBLEMA NELL'AGGIORNARE LO STATO DI UNA SESSIONE VALIDA DI LOGIN A \"IDLE\"");
		ErrorList.put(SIMOGWS_WSSMANAGER_SQL_06,SIMOGWS_WSSMANAGER_SQL_06 + " - PROBLEMA NELL'AGGIORNARE LO STATO DI UNA SESSIONE NON VALIDA DI LOGIN A \"IDLE\" CON ERRORE");
		ErrorList.put(SIMOGWS_WSSMANAGER_NULL_07,SIMOGWS_WSSMANAGER_NULL_07 + " - LA CONNESSIONE RISULTA NULLA");
		ErrorList.put(SIMOGWS_WSSMANAGER_SQL_08,SIMOGWS_WSSMANAGER_SQL_08 + " - PROBLEMA NELL'AGGIORNAMENTO DELLA SESSIONE A STATO \"PROCESSING\"");
		ErrorList.put(SIMOGWS_WSSMANAGER_NULL_09,SIMOGWS_WSSMANAGER_NULL_09 + " - LA CONNESSIONE RISULTA NULLA");
		ErrorList.put(SIMOGWS_WSSMANAGER_SQL_10,SIMOGWS_WSSMANAGER_SQL_10 + " - PROBLEMA DI AGGIORNAMENTO DELLA SESSIONE UNA VOLTA EFFETTUATA L'OPERAZIONE");
		ErrorList.put(SIMOGWS_WSSMANAGER_NULL_11,SIMOGWS_WSSMANAGER_NULL_11 + " - LA CONNESSIONE RISULTA NULLA");
		ErrorList.put(SIMOGWS_WSSMANAGER_SQL_12,SIMOGWS_WSSMANAGER_SQL_12 + " - PROBLEMA CHIUDENDO LA SESSIONE");
		ErrorList.put(SIMOGWS_WSSMANAGER_NULL_13,SIMOGWS_WSSMANAGER_NULL_13 + " - LA CONNESSIONE RISULTA NULLA");
		ErrorList.put(SIMOGWS_WSSMANAGER_SQL_14,SIMOGWS_WSSMANAGER_SQL_14 + " - PROBLEMA NEL RECUPERARE UNA SESSIONE VALIDA ASSOCIATA AI DATI IMMESSI");
		ErrorList.put(SIMOGWS_WSSMANAGER_NULL_15,SIMOGWS_WSSMANAGER_NULL_15 + " - NON E' STATA TROVATA ALCUNA SESSIONE VALIDA");
		ErrorList.put(SIMOGWS_WSSMANAGER_NULL_16,SIMOGWS_WSSMANAGER_NULL_16 + " - LA CONNESSIONE RISULTA NULLA");
		ErrorList.put(SIMOGWS_WSSMANAGER_SQL_17,SIMOGWS_WSSMANAGER_SQL_17 + " - PROBLEMA DURANTE LA RESTITUZIONE DEL CONNECTIONMANAGER, LA CONNESSIONE ASSOCIATA E' NULLA");	
		ErrorList.put(SIMOGWS_WSSMANAGER_APP_18,SIMOGWS_WSSMANAGER_APP_18 + " - ESISTE GIA' UNA SESSIONE ATTIVA");
		ErrorList.put(SIMOGWS_WSSMANAGER_APP_19,SIMOGWS_WSSMANAGER_APP_19 + " - IL LOTTO NON SI TROVA IN UNO STATO CHE NE CONSENTA LA MODIFICA");
		//-----------GARAXMLMANAGER-------------------------
		ErrorList.put(SIMOGWS_GARAXMLMANAGER_NULL_01,SIMOGWS_GARAXMLMANAGER_NULL_01 + " - LA STRINGA PASSATA CHE RAPPRESENTA LE SCHEDE RICHIESTE RISULTA NULLA O VUOTA");
		ErrorList.put(SIMOGWS_GARAXMLMANAGER_NULL_02,SIMOGWS_GARAXMLMANAGER_NULL_02 + " - IL CIG PASSATO E' NULLO");
		ErrorList.put(SIMOGWS_GARAXMLMANAGER_APP_03,SIMOGWS_GARAXMLMANAGER_APP_03 + " - NON E' STATA TROVATA CORRISPONDENZA TRA LA GARA E L'UTENTE");
		//-----------TICKETMANAGER-------------------------
		ErrorList.put(SIMOGWS_TICKETMANAGER_SHA_01,SIMOGWS_TICKETMANAGER_SHA_01 + " - ERRORE NELLA CREAZIONE DEL TICKET");
		ErrorList.put(SIMOGWS_TICKETMANAGER_APP_02,SIMOGWS_TICKETMANAGER_APP_02+ " - "+
						"LA COLLABORAZIONE RISULTA NULLA O PERCHE' L'INDICE PASSATO NON ESISTE(GENERACIG),"+
						" OPPURE PERCHE' NON ESISTE UNA COLLABORAZIONE ASSOCIABILE ALLA GARA(CONSULTAGARA)" +
						" OPPURE IL PROFILO NON E' ABILITATO ALL'AZIONE RICHIESTA");
		ErrorList.put(SIMOGWS_TICKETMANAGER_NULL_03,SIMOGWS_TICKETMANAGER_NULL_03 + " - SI E' TENTATO DI RECUPERARE GLI OGGETTI COLLABORAZIONI CHE RISULTAVANO NULLI");
		ErrorList.put(SIMOGWS_TICKETMANAGER_NULL_04,SIMOGWS_TICKETMANAGER_NULL_04 + " - SI E' TENTATO DI RECUPERARE L'OGGETTO COLLABORAZIONE CHE RISULTAVA NULLO");
		//------------XMLBEANMANAGER-----------------------
		ErrorList.put(SIMOGWS_XMLBEANMANAGER_APP_01,SIMOGWS_XMLBEANMANAGER_APP_01 + " - CIG PASSATO NON VALIDO");
		ErrorList.put(SIMOGWS_XMLBEANMANAGER_APP_02,SIMOGWS_XMLBEANMANAGER_APP_02 + " - ERRORE DURANTE IL CARICAMENTO DEI \"DATI GARA\"");
			// -- VL - adds and modif 03032008 -- //
	    ErrorList.put(SIMOGWS_XMLBEANMANAGER_APP_03,SIMOGWS_XMLBEANMANAGER_APP_03 + " - ERRORE DURANTE IL CARICAMENTO DELLE \"AGGIUDICAZIONI\"");
		ErrorList.put(SIMOGWS_XMLBEANMANAGER_APP_04,SIMOGWS_XMLBEANMANAGER_APP_04 + " - ERRORE DURANTE IL CARICAMENTO DI \"CONCLUSIONE\"");
		ErrorList.put(SIMOGWS_XMLBEANMANAGER_APP_05,SIMOGWS_XMLBEANMANAGER_APP_05 + " - ERRORE DURANTE IL CARICAMENTO DI \"COLLAUDO\"");
		ErrorList.put(SIMOGWS_XMLBEANMANAGER_APP_06,SIMOGWS_XMLBEANMANAGER_APP_06 + " - ERRORE DURANTE IL CARICAMENTO DEGLI \"ACCORDI BONARI\"");
		ErrorList.put(SIMOGWS_XMLBEANMANAGER_APP_07,SIMOGWS_XMLBEANMANAGER_APP_07 + " - ERRORE DURANTE IL CARICAMENTO DELLE \"SOSPENSIONI\"");
		ErrorList.put(SIMOGWS_XMLBEANMANAGER_APP_08,SIMOGWS_XMLBEANMANAGER_APP_08 + " - ERRORE DURANTE IL CARICAMENTO DELLE \"VARIANTI\"");
		ErrorList.put(SIMOGWS_XMLBEANMANAGER_APP_09,SIMOGWS_XMLBEANMANAGER_APP_09 + " - ERRORE DURANTE IL CARICAMENTO DEI \"SUBAPPALTI\"");
		ErrorList.put(SIMOGWS_XMLBEANMANAGER_APP_10,SIMOGWS_XMLBEANMANAGER_APP_10 + " - ERRORE DURANTE IL CARICAMENTO DEI \"RITARDI\"");
		ErrorList.put(SIMOGWS_XMLBEANMANAGER_APP_11,SIMOGWS_XMLBEANMANAGER_APP_11 + " - ERRORE DURANTE IL CARICAMENTO DEGLI \"AVANZAMENTI\"");
		//------------CONFIGURATIONMANAGER-----------------------
		ErrorList.put(SIMOGWS_CONFIGURATIONMANAGER_APP_01,SIMOGWS_CONFIGURATIONMANAGER_APP_01 + " - ERRORE DURANTE IL CARICAMENTO DELLE PROPRIETA' DELL'APPLICAZIONE");
		ErrorList.put(SIMOGWS_CONFIGURATIONMANAGER_APP_02,SIMOGWS_CONFIGURATIONMANAGER_APP_02 + " - ERRORE DURANTE LA RICERCA DEL FILE DI CONFIGURAZIONE");
		//------------ACTIONS ERRORS
		ErrorList.put(SIMOGWS_ACTIONS_APP_01,SIMOGWS_ACTIONS_APP_01 + " - ERRORE DURANTE LA VALIDAZIONE DEI DATI IMMESSI, UNO O PIU' DATI NECESSARI SONO NULLI, E/O NON VALIDI");
		ErrorList.put(SIMOGWS_ACTIONS_APP_02,SIMOGWS_ACTIONS_APP_02 + " - ERRORE DI LOGIN NOME UTENTE O PASSWORD NON VALIDI");	
		//TICKET ALM - 3.04.3
		ErrorList.put(SIMOGWS_ACTIONS_APP_03,SIMOGWS_ACTIONS_APP_03 + " - IL RUP NON E' PRESENTE OPPURE NON HA COLLABORAZIONI");	
		ErrorList.put(SIMOGWS_ACTIONS_APP_04,SIMOGWS_ACTIONS_APP_04 + " - NESSUN PROFILO RPNT DISPONIBILE PER L'UTENTE");	
		ErrorList.put(SIMOGWS_ACTIONS_APP_05,SIMOGWS_ACTIONS_APP_05 + " - SERVIZIO ATTUALMENTE NON DISPONIBILE");	
		ErrorList.put(SIMOGWS_ACTIONS_APP_06,SIMOGWS_ACTIONS_APP_06 + " - NESSUNA INIZIATIVA DISPONIBILE");	
		//-----------ERRORE NON DEFINITO----------------------
		ErrorList.put(SIMOGWS_UNDEFINEND_ERR_01,SIMOGWS_UNDEFINEND_ERR_01 + " - ERRORE INDEFINITO");
		//----------sql tools----------------------
		ErrorList.put(SIMOGWS_SQLTOOLS_ERR_01,SIMOGWS_SQLTOOLS_ERR_01 + " - ERRORE PRENDENDO LA DATA DAL DATABASE");
		ErrorList.put(SIMOGWS_SQLTOOLS_ERR_02,SIMOGWS_SQLTOOLS_ERR_02 + " - ERRORE INCREMENTANDO LA VALIDITA' DELLA SESSIONE");
	
		//---------- GARALOTTOMANAGER 9 aprile -------------------------//
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_SQL_01,SIMOGWS_GARALOTTOMANAGER_SQL_01 + " - ERRORE INSERENDO UNA GARA SUL DB");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_02,SIMOGWS_GARALOTTOMANAGER_APP_02 + " - ERRORE UNO DEGLI OGGETTI NECESSARI ALL'OPERAZIONE RISULTA NULLO");		
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_03,SIMOGWS_GARALOTTOMANAGER_APP_03 + " - ERRORE UNO DEGLI OGGETTI NECESSARI ALL'INSERIMENTO DELLA GARA RISULTA NULLO");	
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_04,SIMOGWS_GARALOTTOMANAGER_APP_04 + " - ERRORE UNO DEGLI OGGETTI NECESSARI ALL'AGGIORNAMENTO DELLA GARA RISULTA NON VALIDO");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_05,SIMOGWS_GARALOTTOMANAGER_APP_05 + " - ERRORE LA GARA NON E' NELLO STATO \"IN DEFINIZIONE\"");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_06,SIMOGWS_GARALOTTOMANAGER_APP_06 + " - ERRORE UNA STRINGA CHE DOVREBBE ESSERE NUMERICA NON RISULTA VALIDA");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_07,SIMOGWS_GARALOTTOMANAGER_APP_07 + " - FALLITA MODIFICA DELLA GARA");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_08,SIMOGWS_GARALOTTOMANAGER_APP_08 + " - FALLITO PERFEZIONAMENTO DELLA GARA");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_09,SIMOGWS_GARALOTTOMANAGER_APP_09 + " - L'INDICE DI COLLABORAZIONE INDICATO NON RISULTA ESSERE VALIDO");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_10,SIMOGWS_GARALOTTOMANAGER_APP_10 + " - L'INDICE DI COLLABORAZIONE INDICATO NON RISULTA ASSOCIABILE ALLA AMMINISTRAZIONE DELLA GARA");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_11,SIMOGWS_GARALOTTOMANAGER_APP_11 + " - LA GARA NON SI TROVA NELLO STATO \"CONFERMATO\" CHE PERMETTE IL CARICAMENTO DI UN LOTTO");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_12,SIMOGWS_GARALOTTOMANAGER_APP_12 + " - IL LOTTO NON RISULTA ESSERE NELLO STATO \"IN DEFINIZIONE\" PERTANTO NON RISULTA MODIFICABILE");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_13,SIMOGWS_GARALOTTOMANAGER_APP_13 + " - L'UTENTE NON E' ABILITATO ALLA MODIFICA DELLA GARA");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_14,SIMOGWS_GARALOTTOMANAGER_APP_14 + " - ID GARA NON RISULTA VALIDO");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_15,SIMOGWS_GARALOTTOMANAGER_APP_15 + " - IL LOTTO NON RISULTA ESSERE NELLO STATO \"IN DEFINIZIONE\" PERTANTO NON RISULTA PERFEZIONABILE");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_16,SIMOGWS_GARALOTTOMANAGER_APP_16 + " - IL LOTTO CONTIENE DEGLI ERRORI, VERIFICARE");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_17,SIMOGWS_GARALOTTOMANAGER_APP_17 + " - LA GARA NON RISULTA ESSERE NELLO STATO ADATTO PER LA SUA CANCELLAZIONE");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_18,SIMOGWS_GARALOTTOMANAGER_APP_18 + " - L'UTENTE NON E' ABILITATO ALLA CANCELLAZIONE DELLA GARA");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_19,SIMOGWS_GARALOTTOMANAGER_APP_19 + " - ERRORE UNO DEGLI OGGETTI NECESSARI ALLA CANCELLAZIONE DEL LOTTO RISULTA NON VALIDO");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_20,SIMOGWS_GARALOTTOMANAGER_APP_20 + " - L'UTENTE NON E' ABILITATO ALLA CANCELLAZIONE DEL LOTTO");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_21,SIMOGWS_GARALOTTOMANAGER_APP_21 + " - IL LOTTO NON RISULTA ESSERE NELLO STATO ADATTO PER LA SUA CANCELLAZIONE");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_22,SIMOGWS_GARALOTTOMANAGER_APP_22 + " - FALLITA CANCELLAZIONE DELLA GARA");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_23,SIMOGWS_GARALOTTOMANAGER_APP_23 + " - FALLITA CANCELLAZIONE DEL LOTTO");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_SQL_24,SIMOGWS_GARALOTTOMANAGER_SQL_24 + " - ERRORE CANCELLANDO UNA GARA");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_25,SIMOGWS_GARALOTTOMANAGER_APP_25 + " - L'UTENTE NON E' ABILITATO ALL'INSERIMENTO DELLA GARA");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_26,SIMOGWS_GARALOTTOMANAGER_APP_26 + " - ERRORE DURANTE INSERIMENTO DEL LOTTO");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_27,SIMOGWS_GARALOTTOMANAGER_APP_27 + " - ERRORE VERIFICANDO ESISTENZA GARE PER OSSR");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_28,SIMOGWS_GARALOTTOMANAGER_APP_28 + " - ERRORE NEL RECUPERO DEL LOTTO");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_29,SIMOGWS_GARALOTTOMANAGER_APP_29 + " - ERRORE INSERIRE CORRETTAMENTE IL PARAMETRO CIG");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_30,SIMOGWS_GARALOTTOMANAGER_APP_30 + " - ERRORE LA GARA NON E' STATA TROVATA");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_31,SIMOGWS_GARALOTTOMANAGER_APP_31 + " - ERRORE LA GARA RISULTA GIA' PUBBLICATA/PERFEZIONATA");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_32,SIMOGWS_GARALOTTOMANAGER_APP_32 + " - ERRORE LA GARA NON RISULTA NELLO STATO CONFERMATO");

		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_33,SIMOGWS_GARALOTTOMANAGER_APP_33 + " - ID MOTIVAZIONE CANCELLAZIONE NON VALIDO");
		ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_34,SIMOGWS_GARALOTTOMANAGER_APP_34 + " - MOTIVAZIONE CANCELLAZIONE OBBLIGATORIA");

		ErrorList.put(SIMOGWS_PUBBLICAZIONE_APP_35,SIMOGWS_PUBBLICAZIONE_APP_35 + " - Allegato: $1 - $2");
		ErrorList.put(SIMOGWS_PUBBLICAZIONE_APP_36,SIMOGWS_PUBBLICAZIONE_APP_36 + " - Pubblicazione effettuata correttamente");

        ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_37,SIMOGWS_GARALOTTOMANAGER_APP_37 + " - Per la gara non e' prevista la trasmissione dei requisiti");
        ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_38,SIMOGWS_GARALOTTOMANAGER_APP_38 + " - DATI COMUNI NON TROVATI");
        // INT87
        ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_39,SIMOGWS_GARALOTTOMANAGER_APP_39 + " - ERRORE PER LA GARA INDICATA NON E' CONSENTITA L'INTEGRAZIONE DEL DATO");
        
        // MAC #3525 (3.04.2)
        ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_40,SIMOGWS_GARALOTTOMANAGER_APP_40 + " - Data Scadenza: campo non previsto");
        
        // MAC #10525 (3.04.3.1)
        ErrorList.put(SIMOGWS_GARALOTTOMANAGER_APP_41,SIMOGWS_GARALOTTOMANAGER_APP_41 + " - NON E' POSSIBILE INSERIRE IL LOTTO IN QUANTO LA GARA RISULTA GIA' PUBBLICATA/PERFEZIONATA ");
	}
}
